### ISSUE TITLE
How to use HTML character filter?

### ISSUE THREAD

**Issue by coolaj86** [blevesearch/bleve#1008]
I've been searching the docs and the website and I see references to the HTML character filter, but I don't see any specific examples of how to use it.

Could you point me in the right direction?

**Comment by 4ydx** [comment]
Under ~/go/src/github.com/blevesearch/bleve/analysis/analyzer/simple you can see how an analyzer is created.

If you add the following to your code, I believe it will apply the html char filter.  I just started looking at bleve yesterday so I might be off about this.

```
import (
  "github.com/blevesearch/bleve/analysis"
  "github.com/blevesearch/bleve/analysis/char/html"
  "github.com/blevesearch/bleve/registry"
)

const Name = "custom_html"

func AnalyzerConstructor(config map[string]interface{}, cache *registry.Cache) (*analysis.Analyzer, error) {
	htmlCharFilter, err := cache.CharFilterNamed(html.Name)
	if err != nil {
		return nil, err
	}
	rv := analysis.Analyzer{
		CharFilters: []analysis.CharFilter{
			htmlCharFilter,
		},
	}
	return &rv, nil
}

func init() {
	registry.RegisterAnalyzer(Name, AnalyzerConstructor)
}
```

**Comment by steveyen** [comment]
hi - going to mark this closed due to the answer from @4ydx (thanks @4ydx for helping!)
