### ISSUE TITLE
How to use bleve with existing mongodb

### ISSUE THREAD

**Issue by impochi** [blevesearch/bleve#1011]
I am looking at a solution for full text fuxzzy search that combines multiple collections in mongodb

Is bleve the solution that i should goo for ? [I am not to keen on elasticsearch as my backend api's are in golang]

If yes , then any possible places of code snippets ? tutorials ? and how does bleve play with mongodb.
@abhinavdangeti @mschoch

**Comment by sreekanth-cb** [comment]
not sure of a solution for mongodb, but Couchbase full text search is powered by bleve and has Go SDK support.

**Comment by steveyen** [comment]
Hi @impochi -- you'd have to write a golang application to extract documents from mongodb across your multiple collections and use bleve's API's to index them into bleve.  It wouldn't be something that the bleve library itself does directly.  cheers, steve
