### ISSUE TITLE
index by filetype

### ISSUE THREAD

**Issue by laoshaw** [blevesearch/bleve#1013]
I have a repo of c, c++, markdown, js etc, is there a way I can set up bleve to index them based on filetypes, or all the files have to be indexed together? for example, I want to have an index of all markdown files, another index for all *.c and *.h files, etc.

if bleve indeed indexes all files together, at search time, can I designate filetype so I can limit the search based on filetypes, say I only want to search all "memmove" in [*.ch] but not in *.md filetypes.

**Comment by ansjsun** [comment]
parse the suffix to the new field. to search it  like  `+_all:* -suffix:md`
