### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by jlcheng** [blevesearch/bleve#1016]
1) On https://blevesearch.com/docs/Index-Mapping/
"IndexMapping describes how **to** your data model should be indexed" 
should be
"IndexMapping describes how your data model should be indexed

2) On https://blevesearch.com/docs/Index-Mapping/
compostie => composite

3) On https://blevesearch.com/docs/Index-Mapping/
"describing the author field field name and email" 
Suggested rewrite
"describing the author field using sub-fields name and email"

4) On https://blevesearch.com/docs/IndexAlias/
"IndexAliases can also be search to search across multiple"
should be
"IndexAliases can also be used to search across multiple"

**Comment by oskarwojciski** [comment]
Documentation is in different repo, I have created Pull Request there https://github.com/blevesearch/blevesearch.github.io/pull/4

**Comment by jlcheng** [comment]
Thanks. I'll close this issue then.
