### ISSUE TITLE
Build flags need documentation

### ISSUE THREAD

**Issue by kapilt** [blevesearch/bleve#104]
The Building wiki doc leaves it as exercise for the user to grep the source for all the build flags. Just document them on the building wiki page.

**Comment by honza** [comment]
`compile_libs.sh` fails on OSX

**Comment by mschoch** [comment]
The compile_libs.sh is a part of the CLD2 source not bleve.  Though, last time I ran it, it did work for me on OSX.  Can you share any errors or output you're getting.

**Comment by honza** [comment]
Yes, I know — I was just giving you a heads up. The output is:

```
Warning: None of CFLAGS, CXXFLAGS or CPPFLAGS is set; you probably should enable some options.
ld: unknown option: -soname=libcld2.so
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: unknown option: -soname=libcld2_full.so
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mschoch** [comment]
Did you checkout revision 164 as described in the readme?  The text from the output seems to match some changes made to the script in revision 190.

**Comment by honza** [comment]
Aha! That one I missed. I just read the above instructions. It's now compiled and in `/usr/local/lib`.

Here is what I get now:

```
$ go build -tags full
# github.com/blevesearch/bleve/analysis/tokenizers/icu
../../blevesearch/bleve/analysis/tokenizers/icu/boundary.go:17:11: fatal error: 'unicode/utypes.h' file not found
 #include "unicode/utypes.h"
          ^
1 error generated.
```

**Comment by mschoch** [comment]
Do you have ICU installed, with the headers somewhere your compilers expect to find them?

**Comment by saljam** [comment]
@honza

    $ brew icu4c
installed it for me on OS X.

**Comment by honza** [comment]
@saljam I installed it with homebrew, no luck. Same error. I guess I don't need icu for now.

**Comment by mschoch** [comment]
Brew tells me that, 'This formula is keg-only.'

So it may be that it installed everything, but there are no symlinks hooking it up to a place the compiler is looking by default.  I'm not exactly sure as I didn't go this route because previously the brew was very out of date, so I just downloaded ICU, built and installed it myself.

If you can find where brew stuffed things, you could try building with CGO_CFLAGS=-I<path_to_icu_headers>

**Comment by atomotic** [comment]
this works for me on osx:

    export CGO_LDFLAGS=-L/usr/local/opt/icu4c/lib
    export CGO_CFLAGS=-I/usr/local/opt/icu4c/include
    go get -u -v -tags full github.com/blevesearch/bleve
