### ISSUE TITLE
Is blevesearch production ready?

### ISSUE THREAD

**Issue by unisqu** [blevesearch/bleve#1064]
1. Any high traffic sites using it?

2. I like blevesearch a lot but does anyone have any benchmark of it compared with sphinxsearch/manticore? (i dont mind if it's slower but would like to know the difference in speed)

**Comment by ivanjaros** [comment]
I would like to extend this question with mine - can Bleve scale horizontally? I need search service but I expect high loads so multiple instances will be needed. Is there a raft/gossip protocol and replication/sharding support(like cockroachdb)?

**Comment by glycerine** [comment]
@ivanjaros I notice that https://github.com/dgraph-io/dgraph, a graph database, implements full text search using bleve. `dgraph` aims to be horizontally scalable. It uses raft groups for replication and sharding. It provides linearizable transactions and CP consistency.

**Comment by steveyen** [comment]
> I would like to extend this question with mine - can Bleve scale horizontally?

bleve is also used in couchbase server, which scales out horizontally by partitioning documents across  multiple bleve indexes.  The multiple indexes are assigned to live across server nodes.
