### ISSUE TITLE
possible issue with batch PersistedCallback when using upsidedown

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1080]
The recent change #1076 included support for also invoking the callback when using upsidedown, but appears to have received less testing.

I'm observing the following:

```
2018-12-14 20:57:10.8134 error Bleve failed persisting batch of one object ***INDEX PATH REDACTED*** (error: <nil>)(source: /***PROJECT REDACTED***/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:964) 
```

The callback in question looks like this:

```
				b.SetPersistedCallback(func(err error) {
					if err != nil {
						// do something
					} else {
						logrus.WithError(err).Errorf("Bleve failed persisting batch of one object %s", i.Index.Name())
					}
				})
```

In this case, the else block is exectued, but the logged error is nil.  Possibly this is an instance of the nil != nil issue that can occur with Go, although my initial glance at the upsidedown code did not reveal anything obvious.

**Comment by abhinavdangeti** [comment]
Please correct me if I'm mistaken here.. but looks like you're logging an error in the callback when err == nil. Is the expectation - the callback be invoked only in case of err != nil ? Because the callback is invoked regardless of err being nil or not.

**Comment by mschoch** [comment]
Oops, you're absolutely right, the bug is in our callback handler.  We expect it to be called regardless, but some logic was flipped around incorrectly.  Thanks!

**Comment by abhinavdangeti** [comment]
Great :) Happy Friday!
