### ISSUE TITLE
how do i display the full text results?

### ISSUE THREAD

**Issue by unisqu** [blevesearch/bleve#1081]
how do i display the full text results? can it be used like a database? e.g. returning all results based on a search query

**Comment by abhinavdangeti** [comment]
You can use a match_all query to return all documents that have been indexed.
```
{"query": {"match_all": {}}
```

**Comment by unisqu** [comment]
sorry newbie here to blevesearch

how do i do that?
read thru docs cant find. what should i add to the default 

http://blevesearch.com/docs/Getting%20Started/

https://pastebin.com/2ARktdpX

Please help. Thx

**Comment by unisqu** [comment]
i only saw this thread here

https://groups.google.com/forum/#!searchin/bleve/setinternal%7Csort:date/bleve/y39txEMnjLo/m4LExfvhDAAJ

i was thinking is there a better way than setinternal / getinternal?

or as mentioned, 
        
                     {"query": {"match_all": {}}

how do i get it done?

**Comment by unisqu** [comment]
realised need to do GetInternal and Setinternal
