### ISSUE TITLE
Can anyone pls help update this? I'm trying to check how to do connectors

### ISSUE THREAD

**Issue by unisqu** [blevesearch/bleve#1088]
https://gist.github.com/indraniel/1dc0243a27e600e3f297#file-toy-bleve-goleveldb-test-go

./toyleveldb.go:174:30: not enough arguments in call to bleve.NewUsing
        have (string, *mapping.IndexMappingImpl, string, map[string]interface {})
        want (string, mapping.IndexMapping, string, string, map[string]interface {})

**Comment by steveyen** [comment]
The go compiler is saying that there are not enough parameters while trying to call the bleve.NewUsing() method.  The line of code at line 174 is...

	index, err := bleve.NewUsing(indexName, mapping, kvstore, kvconfig)

There are only 4 parameters there on line 174 (the indexName, mapping, kvstore, kvconfig).

And part of the output error message from the compiler is...

        have (string, *mapping.IndexMappingImpl, string, map[string]interface {})

But, actually, the NewUsing() method takes 5 parameters.  The compiler says this when it says...

        want (string, mapping.IndexMapping, string, string, map[string]interface {})

You can see there's a string parameter that's missing from the call on line 174, so need to add that extra string parameter.

-- cheers, steve
