### ISSUE TITLE
support indexing and specialized querying of boolean fields

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#109]

**Comment by mmindenhall** [comment]
I just ran into the case where I have some `bool` fields in structs that aren't getting indexed.  I checked the source code and didn't see where that would be happening, then found this issue.  I see this has been open for over a year...is this especially difficult to do for some reason?  If not, I might give it a shot.

**Comment by mmindenhall** [comment]
As a start, I'd be happy with indexing bools as string "true" or "false", or as numeric 0 or 1.
