### ISSUE TITLE
Update / replace field items feature in blevesearch?

### ISSUE THREAD

**Issue by unisqu** [blevesearch/bleve#1093]
Sorry I can't find anything regarding update / replace items for blevesearch. Is there such a feature or is it in development?

**Comment by steveyen** [comment]
Hi @unisqu -- if one does an Insert() of an item using the same id as from a previous Insert(), that behaves as a replacement or update in the index.  -- cheers, steve

https://godoc.org/github.com/blevesearch/bleve#Batch.Index
