### ISSUE TITLE
Why badgerdb is not supported officially?

### ISSUE THREAD

**Issue by unisqu** [blevesearch/bleve#1094]
badgerdb when compared with boltdb should be faster but I also heard about scorch, where's the official website for scorch coz cant find online but i do prefer badger coz it's purely in golang

**Comment by photostorm** [comment]
scorch is a new index type of bleve, which the current index type is upside-down. 

Here is the README: https://github.com/blevesearch/bleve/tree/master/index/scorch

Also, here is another issue for badgerdb support.

https://github.com/blevesearch/bleve/issues/591

**Comment by unisqu** [comment]
ok thx
