### ISSUE TITLE
option to sort by other fields

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#110]
Sometimes its useful for applications to want the search results sorted by another field, often a date or numeric value.

**Comment by dorsha** [comment]
We would love to have sort functionality on other fields as well (for pagination and etc.)

**Comment by meirwah** [comment]
pagination without sorting is a bit lacking.. is this feature planned anytime soon?

**Comment by mschoch** [comment]
No one is currently working on it.  At the moment I'm focused exclusively on performance, as for our use case sorting/pagination by score is sufficient, but indexing throughput is too low to be usable.

Its not a small job, but its not impossible for someone else to take a look at it in parallel.  There are two main pieces.

1.  A new implementation of the Collector interface, which is responsible for looking at all the scored "hits" and deciding which ones to keep and return to the user.  The current impl looks at score and keeps the top N, after skipping over M hits.  The new impl would look at the "sort" field(s), and keep the highest/lowest results, possibly also breaking ties by using the score.

2.  Part 1 sounds straightforward, but the missing piece is how does it access the value for the sort field(s).  Probably some interfaces need to change to accommodate this, as when users request stored fields we don't load them till later in the process.  Some thought needs to be put into the most efficient way to collect these sort values while we execute the search.

**Comment by acgshare** [comment]
At least, it would be helpful if the search result could be sort by id.

**Comment by slavikm** [comment]
@mschoch is anyone working on this currently? I would like to take a stub at this as we need sort but other fields.

**Comment by caseymrm** [comment]
@slavikm I saw you had one collector commit, is this something you're actively working on?

**Comment by slavikm** [comment]
@caseymrm I started, than had to stop for a while (other stuff came up) and now I'm getting back to it. Hopefully will try and commit something next week.

**Comment by nadoo** [comment]
really need this feature, hope it will be immplemented soon. thank you! @slavikm .

**Comment by gaillard** [comment]
+1 as a need to be able to use the lib

**Comment by mschoch** [comment]
Yes, I understand this is important.  We will prioritize this and make sure we at least get the API to do this into 1.0.

**Comment by gaillard** [comment]
I love to see the work here! :D
