### ISSUE TITLE
Seeing strange results with match query over term with special character(s)

### ISSUE THREAD

**Issue by abhinavdangeti** [blevesearch/bleve#1115]
Not sure if I'm overlooking anything obvious but here's something strange I'm seeing in a test program with a match query over a term that has this character in it "@" (see mq2 below) ..

```
func TestMatchWeird(t *testing.T) {
	idx, err := NewUsing("testidx", NewIndexMapping(), scorch.Name, Config.DefaultKVStore, nil)
	if err != nil {
		t.Fatal(err)
	}

	defer func() {
		err = idx.Close()
		if err != nil {
			t.Fatal(err)
		}

		err := os.RemoveAll("testidx")
		if err != nil {
			t.Fatal(err)
		}
	}()

	// create and insert one document
	batch := idx.NewBatch()
	doc := document.NewDocument("doc")
	doc.Fields = []document.Field{
		document.NewTextField("name", []uint64{}, []byte("name1")),
		document.NewTextField("email", []uint64{}, []byte("name1@email1.com")),
	}
	doc.CompositeFields = []*document.CompositeField{
		document.NewCompositeFieldWithIndexingOptions(
			"_all", true, []string{"text"}, []string{},
			document.IndexField|document.IncludeTermVectors),
	}

	if err = batch.IndexAdvanced(doc); err != nil {
		t.Fatal(err)
	}

	if err = idx.Batch(batch); err != nil {
		t.Fatal(err)
	}

	mq1 := NewMatchQuery("name1")
	mq1.SetField("name")
	sr1 := NewSearchRequest(mq1)

	res, err := idx.Search(sr1)
	if err != nil {
		t.Fatal(err)
	}

	if res.Total != 1 {
		t.Errorf("Expected 1 result, but got: %v", res.Total)
	}

	mq2 := NewMatchQuery("name1@email1.com")
	mq2.SetField("email")
	sr2 := NewSearchRequest(mq2)

	res, err = idx.Search(sr2)
	if err != nil {
		t.Fatal(err)
	}

	if res.Total != 1 {
		t.Errorf("Expected 1 result, but got: %v", res.Total)
	}
}

```

**Comment by abhinavdangeti** [comment]
The term dictionary for the field email indicates that "name1@email1.com" should indeed be searchable ..

```
[19:02:24] abhinav: ~/Documents/go/src/github.com/blevesearch/bleve $ ~/Documents/couchbase/install/bin/cbft-bleve zap dict testidx/store/000000000002.zap  email
dictionary for field starts at 241 (f1)
vellum length: 54
raw vellum data:
 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 90 c4 ca cd d5 cf c8 c5 d0 c2 40 c0 d5 c2 d0 c5 da 01 11 8b 01 00 00 00 00 00 00 00 25 00 00 00 00 00 00 00
dictionary:
 name1@email1.com - 218 (da)
```

I tried setting the match query's (mq2) analyzer to "standard" as well, but it did no good.

**Comment by sreekanth-cb** [comment]
Haven't checked the details.. I would suspect the analyzers first..And a keyword analyzer for the email field seems to work/pass test. May be try with a web analyzer for the email field?
But your vellum content discovery is contradicting this theory though..

**Comment by mschoch** [comment]
Ya quick thought is that it is related to the fact that you're using IndexAdvance method, but don't ever show that bleve knows about the mapping.  Remember that at query time, bleve consults the mapping, to look up which analyzer you used for a particular field.

So, when you run the query scoped to field "email", bleve starts by looking at the mapping for that field.  The mapping doesn't contain anything for it, so it uses the default, which would be the standard analyzer.  But... the content you fed in to through IndexAdvanced isn't what the standard analyzer would have produced...

The standard analyzer turns 'name1@email1.com' into 3 tokens.  But, by using IndexAdvanced you've indexed just a single token.  So at query time there won't be a match.

**Comment by abhinavdangeti** [comment]
Awesome, that was it, thanks for clearing that @mschoch. Cheers.
