### ISSUE TITLE
PostingList API Count() Error in calculation 

### ISSUE THREAD

**Issue by heidawei** [blevesearch/bleve#1139]
when except is not nil, count = n-e, but the except include all delete document internalID, and the postingList bitmap only has docs which has the term, I'm trying to give you my way of doing it.
func (p *PostingsList) Count() uint64 {
	var n, e uint64
	if p.normBits1Hit != 0 {
		n = 1
	} else if p.postings != nil {
		n = p.postings.GetCardinality()
		if p.except != nil {
			e = p.postings.AndCardinality(p.except)
		}
	}
	//var e uint64
	//if p.except != nil {
	//	e = p.except.GetCardinality()
	//}
	//if n <= e {
	//	return 0
	//}
	return n - e
}

**Comment by mschoch** [comment]
Here is the code you provided formatted better:

```
func (p *PostingsList) Count() uint64 {
  var n, e uint64
  if p.normBits1Hit != 0 {
    n = 1
  } else if p.postings != nil {
    n = p.postings.GetCardinality()
    if p.except != nil {
      e = p.postings.AndCardinality(p.except)
    }
  }
  //var e uint64
  //if p.except != nil {
  //  e = p.except.GetCardinality()
  //}
  //if n <= e {
  //  return 0
  //}
  return n - e
}
```

**Comment by mschoch** [comment]
The section of code being discussed is here: https://github.com/blevesearch/bleve/blob/master/index/scorch/segment/zap/posting.go#L265-L281

**Comment by heidawei** [comment]
@mschoch Thanks.
I opened a new [issue#114](https://github.com/blevesearch/bleve/issues/1140) for this discuss and this issue will be closed.
