### ISSUE TITLE
PostingList API Count() Error in Calculation

### ISSUE THREAD

**Issue by heidawei** [blevesearch/bleve#1140]
https://github.com/blevesearch/bleve/blob/cb59b33c8bb0e24675ce5f079307e67e11a0f72c/index/scorch/segment/zap/posting.go#L265-L281

When except is not nil, count = n-e, but the except include all delete document internalID, and the postingList bitmap only has docs which has the term, I'm trying to give you my way of doing it.

```go
func (p *PostingsList) Count() uint64 {
  var n, e uint64
  if p.normBits1Hit != 0 {
    n = 1
  } else if p.postings != nil {
    n = p.postings.GetCardinality()
    if p.except != nil {
      e = p.postings.AndCardinality(p.except)
    }
  }
  //var e uint64
  //if p.except != nil {
  //  e = p.except.GetCardinality()
  //}
  //if n <= e {
  //  return 0
  //}
  return n - e
}
```

**Comment by steveyen** [comment]
Thanks @heidawei !

So, trying an example to make sure I understand.

Let's say I have 100 doc in my index, but only 5 docs have the term "hello".  So, the postings bitmap for "hello" would have 5 bits turned on (cardinality 5).

Then, let's say I delete 40 docs, but I carefully delete 40 completely different docs than those 5 hello docs. 

So the cardinality in the "except" bitmap would be 40.

But, the count would be incorrect since 5 - 40 ==> zero... when, instead the count for the postings-list for "hello" should still be 5.

Great catch!  Thanks!

**Comment by heidawei** [comment]
@steveyen  You are welcome！！！！

**Comment by mschoch** [comment]
That makes sense @steveyen but doesn't the 1-hit encoded case also need to account for that doc being deleted?  That part was lost when the `e` calculation moved into the else if.

**Comment by steveyen** [comment]
Indeed -- the 1-hit encoding case also needs a similar maneuver.

**Comment by steveyen** [comment]
I'm thinking a potential solution in the 1-hit case is that we'd need to check to see if the 1-hit docNum is in the except bitmap and return a count of 1 or 0 accordingly.  Might be other edge situations I'm not thinking of here.

**Comment by mschoch** [comment]
@steveyen yes I agree, but I forgot how(if?) we know what that one hit is at this level, or if it was up-stairs and thus making this harder to fix...  I think it was late and I just closed the tab :)

**Comment by steveyen** [comment]
> ... but I forgot how(if?) ...

This describes me on every Monday morning!! :-)

Taking a look again, I'm thinking the PostingsList itself has enough info or state to know that it's in 1-bit mode, and also knows the exact doc-num when it's in 1-bit mode...

https://github.com/blevesearch/bleve/blob/master/index/scorch/segment/zap/posting.go#L110

**Comment by mschoch** [comment]
Cool, so then something like this:

```
func (p *PostingsList) Count() uint64 {
  var n, e uint64
  if p.normBits1Hit != 0 {
    n = 1
    if p.except != nil && p.except.Contains(uint32(p.docNum1Hit)) {
      e = 1
    }
  } else if p.postings != nil {
    n = p.postings.GetCardinality()
    if p.except != nil {
      e = p.postings.AndCardinality(p.except)
    }
  }
  return n - e
}
```

**Comment by steveyen** [comment]
yah, that looks right to me
