### ISSUE TITLE
Support go.mod

### ISSUE THREAD

**Issue by fproulx-dfuse** [blevesearch/bleve#1147]
Hello,
We use go 1.11 (go.mod) and since some of your transitive dependencies have started to use it too.
When we `go mod tidy` your transitive dependencies follow and we can never be sure that updating them will not have an impact on bleve.

It would be great that you lock the stable dependencies for a tagged version of bleve....

**Comment by mschoch** [comment]
Yes, it would be great.  Unfortunately, I don't know anything about Go modules.  The versions we recommend (and test against) are in the vendor/manifest file.

We will eventually start to support modules.  If the community help us get there faster that would be great.

**Comment by prochac** [comment]
close this
https://github.com/blevesearch/bleve/issues/1350
