### ISSUE TITLE
Panic on range query with unlimited upper when using scorch.

### ISSUE THREAD

**Issue by mervinkid** [blevesearch/bleve#1156]
A panic will be occurred cause `index out of range` when doing range query with unlimited upper by using **scorch**.

There are some logic issue in `RangeIterator` method of `index/scorch/segment/zap/Dictionary` struct.  

https://github.com/blevesearch/bleve/blob/4b5cfbc8d5656cf05bf74d1ae270d2ca505560fc/index/scorch/segment/zap/dict.go#L140-L163

When a range query with unlimited upper invoked, the `end` parameter of this method will be an  empty string. Then the `endBytes` variable will becomes a byte slice without any element. 

```go
	// need to increment the end position to be inclusive
	endBytes := []byte(end)
	if endBytes[len(endBytes)-1] < 0xff {
		endBytes[len(endBytes)-1]++
	} else {
		endBytes = append(endBytes, 0xff)
	}
```

The above code will trying to **access element from empty slice**, so that an `index out of range` panic will be occurred.

This issue found by my colleague @heidawei .
We will submit a merge request soon to fix this problem.

**Comment by heidawei** [comment]
And for fst.Iterator(start, end)，if we want to include max, we need set end is nil, not []byte(nil), so in this case, we need set endBytes = nil to replace the []byte(end) when end is empty string

**Comment by mervinkid** [comment]
Thanks for @heidawei 's supplement.

This issue have been fixed by pull request #1157 .

**Comment by mschoch** [comment]
Thanks for reporting this.

Initially I was having difficulty reproducing this (even though the description made sense).  My confusion was that this doesn't actually affect numeric range searches, due to the their unique implementation.  But it does affect term range searches.

I have reproduced the issue locally, and I'll add a test case to the PR.

**Comment by mervinkid** [comment]
@mschoch 
My pleasure. 
Have a good day.

**Comment by mervinkid** [comment]
The pull request #1157 with fixed this issue have been merged into master branch by @mschoch .
He added some unit tests to this pull request to verify these changes.

This issue will be closed.
