### ISSUE TITLE
infinite loop storeConstructor

### ISSUE THREAD

**Issue by liepumartins** [blevesearch/bleve#1167]
I noticed that sometimes bleve gets stuck in endless loop on this.
`index, err := bleve.Open("products.bleve")`

Deleting the index entirely and creating from scratch helps, but I believe such problem should not occur in the first place. Or at least return an error.

Digging through the code, I ended up at the origin of the issue: https://github.com/blevesearch/bleve/blob/bc8ab4cfdc77585710ffe29c0f759d7a0d63b967/index/upsidedown/upsidedown.go#L308

This is where my newbie golang understanding ends.

**Comment by mschoch** [comment]
Can you provide evidence that this is an endless loop and not that the code is simply blocked?

By default, Bleve uses BoltDB for index storage, and BoltDB can only be opened by a single process at a time.  If you attempt to open the index again from another process, the code will block around this same point (at this same line you mentioned, but deeper inside the boltdb code.

**Comment by liepumartins** [comment]
No other process are involved. Is it possible that BoltDB was open, process died/got killed and left the BoltDB in such state, that new open attempts gets blocked?

But even if it is blocked, which sounds more likely, than infinite loop, should not there be an error about this?

**Comment by mschoch** [comment]
You should get the goroutine dump at the time it hangs to confirm this is the issue.  Some ways to do this are here:

https://stackoverflow.com/questions/19094099/how-to-dump-goroutine-stacktraces

Usually either CTRL+\  or sending SIGABRT works for me.

In my experience on linux and mac, I've only ever seen it happen with a live process, not with a stale lockfile.

If you'd like to add support for the BoltDB timeout option (after which it will return an error), it could be done through the options map, like how some other settings are handled here:

https://github.com/blevesearch/bleve/blob/master/index/store/boltdb/store.go#L71-L87

**Comment by liepumartins** [comment]
Found one way where `defer index.Close()` was missing, that also explains why issue happened only sometimes.
Sorry about troubling You with my code mistakes.

And yes, error on timeout would be great way to solve/point to such failures.
