### ISSUE TITLE
duplicate locations returned after commit b4ac805

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1168]
Prior to the commit b4ac805, a search which finds the same term multiple times returns a single location.  However, after this commit, the same search now returns duplicated location information.  This has broken some applications which do their own highlighting client-side.

The following program prints "FAIL" when duplicates are found, and prints nothing otherwise, git bisect was used with this program to find the commit:

```
package main

import (
	"fmt"
	"log"

	"github.com/blevesearch/bleve"
	"github.com/blevesearch/bleve/analysis/analyzer/keyword"
	"github.com/blevesearch/bleve/search/highlight/highlighter/html"
)

func main() {

	fm1 := bleve.NewTextFieldMapping()
	fm1.Analyzer = keyword.Name
	fm1.Name = "name1"

	dm := bleve.NewDocumentStaticMapping()
	dm.AddFieldMappingsAt("name", fm1)

	m := bleve.NewIndexMapping()
	m.DefaultMapping = dm

	idx, err := bleve.NewMemOnly(m)
	if err != nil {
		log.Fatalf("bleve new err: %v", err)
	}

	err = idx.Index("x", map[string]interface{}{
		"name": "marty",
	})
	if err != nil {
		log.Fatalf("bleve index err: %v", err)
	}

	q1 := bleve.NewTermQuery("marty")
	q2 := bleve.NewTermQuery("marty")
	dq := bleve.NewDisjunctionQuery(q1, q2)
	sreq := bleve.NewSearchRequest(dq)
	sreq.Fields = []string{"*"}
	sreq.Highlight = bleve.NewHighlightWithStyle(html.Name)

	sres, err := idx.Search(sreq)
	if err != nil {
		log.Fatalf("bleve search err: %v", err)
	}
	if len(sres.Hits[0].Locations["name1"]["marty"]) != 1 {
		fmt.Println("FAIL")
	}
}
```

It might be possible to further simplify this program, but it was tweaked over time as various theories were tested to illustrate the problem.

**Comment by steveyen** [comment]
wow.

Looking quickly through that commit, it seems to be some impersonator who writes in my exact coding style who seems to have made that commit!  Have completely paged out those code areas from my head.  :-)

**Comment by steveyen** [comment]
The original code, I think, used to call search.MergeLocations(), which calls MergeTermLocationMap(), which has this relevant comment...
```
// for a given term/document there cannot be different locations
// if they came back from different clauses, overwrite is ok
```https://github.com/blevesearch/bleve/blob/master/search/util.go#L37

**Comment by steveyen** [comment]
(whoops hit wrong button)
