### ISSUE TITLE
batch index 5300 record, it costs 3m41s, how you improve it

### ISSUE THREAD

**Issue by orange-jacky** [blevesearch/bleve#1181]
hi,
i use batch index, 5308 record, it cost 3m41s, how you imporve it?

record fomat :
GlobalAirport struct {
		Id           string `bson:"_id" json:"_id"`
		Cnname       string `bson:"cnname" json:"cnname"`
		Citycode     string `bson:"citycode" json:"citycode"`
		Citycn       string `bson:"citycn" json:"citycn"`
		Enname       string `bson:"enname" json:"enname"`
		Country      string `bson:"country" json:"country"`
		Province     string `bson:"province" json:"province"`
		Cityen       string `bson:"cityen" json:"cityen"`
		Country_code string `bson:"country_code" json:"country_code"`
		Region_code  string `bson:"region_code" json:"region_code"`
		Region_name  string `bson:"region_name" json:"region_name"`
		City_pinyin  string `bson:"city_pinyin" json:"city_pinyin"`
		City_jianpin string `bson:"city_jianpin" json:"city_jianpin"`
	}
a record data: 
{ZVK 沙湾拿吉机场 ZVK 沙湾拿吉 Savannakhet 老挝人民民主共和国  Savannakhet LA AS 亚洲 SHAWANNAJI SWNJ}

my batch index code:
	//Indexing
		mapping := bleve.NewIndexMapping()
		index, err := bleve.New("example.globalAirport", mapping)
		if err != nil {
			panic(err)
		}

		batch := index.NewBatch()
		for _, message := range slice {
			//fmt.Printf("%d %s\n", i, message.Id)
			batch.Index(message.Id, message)
		}

		fmt.Println("start batch indexing....")
		start := time.Now()
		err = index.Batch(batch)
		if err != nil {
			panic(err)
		}
		end := time.Now()
		fmt.Printf("batch index finish. cost %s", end.Sub(start).String())

		// 2 documents have been indexed
		count, err := index.DocCount()
		if err != nil {
			panic(err)
		}
		fmt.Println(count)

		err = index.Close()
		if err != nil {
			panic(err)
		}

		//Querying
		index1, err := bleve.Open("example.globalAirport")
		if err != nil {
			panic(err)
		}
		query := bleve.NewTermQuery("北京")
		searchRequest := bleve.NewSearchRequest(query)
		searchResult, err := index1.Search(searchRequest)
		if err != nil {
			panic(err)
		}

		fmt.Println(searchResult)
		err = index1.Close()
		if err != nil {
			panic(err)
		}

code run ouput:
........
2019/03/27 10:05:39 cannot decode null into a string type
2019/03/27 10:05:39 laod 5308 data from globalAirport
start batch indexing....

batch index finish. cost 3m41.668910688s5308
No matches
1
1 matches, showing 1 through 1, took 95.773µs
    1. example (0.125272)

**Comment by orange-jacky** [comment]
why not notice my issue?

**Comment by mschoch** [comment]
Sorry for not replying sooner, we try to reply as they come in, but sometimes they are missed.

As of today, the default index type for bleve is still the older and slower `upsidedown` implementation which uses key/value stores as it's underlying storage.  Further, the default key/value store is `bbolt` which is not optimal for achieving a high write throughput.

We have been working on a new index implementation called `scorch` which should perform significantly better.  You can try this today by changing the line where you create the index to:

```
index, err := bleve.NewUsing("example.globalAirport", mapping, scorch.Name, scorch.Name, nil)
```
In this code snippet, `scorch` refers to importing the package `github.com/blevesearch/bleve/index/scorch`

I recommend you try this and see if the performance is better.

In a future release (hopefully soon) `scorch` will become the default index type.

**Comment by orange-jacky** [comment]
it work perfect fast

2019/04/19 18:58:13 laod 5308 data from globalAirport
start batch indexing....
batch index finish. cost 1.397715791s5308
1898 matches, showing 1 through 10, took 6.344346ms

**Comment by orange-jacky** [comment]
you can close this issue
