### ISSUE TITLE
another boolean searcher issue

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1185]
I have an index (which unfortunately I cannot share) that exhibits the following behavior.  A search of the form:

a AND (must not b)

produces correct results.  But the same search, written in this form:

must a, must not b

produces incorrect results (some hits violate the must not b portion)

My attempts to reproduce this issue with smaller datasets that are similar to the original have not succeeded.  But, believing there really is an issue that I just haven't been able to figure out yet, I went ahead and did the `git bisect` to see if I could at least demonstrate that this behavior had changed.

Sure enough, this worked, and I see that I get correct results for both forms of the query prior to this commit:

```
dd49ef0aa0a006a46e90b20dcba578265c043c07 is the first bad commit
commit dd49ef0aa0a006a46e90b20dcba578265c043c07
Author: abhinavdangeti <abhinav@couchbase.com>
Date:   Wed Dec 5 17:13:59 2018 -0800

    Advancing boolean searcher's currentID w.r.t currMustNot
    
    + Advance the boolean searcher's nested searchers only if the
      cursor is trailing the lookup ID, additionally if the
      mustNotSearcher has been initialized, ensure that the cursor
      used to track the mustNotSearcher (which isn't tracked by
      the other cursor) is trailing the lookup ID as well, to avoid
      any searcher from advancing incorrectly.
    + Unit test that catches the cornercase:
        TestNestedBooleanMustNotSearcherUpsidedown
```

I'll continue to try and dig deeper, but I wanted to document what I know so far.  (I was really hoping Abhinav's revert the other day was going to fix this, but it did not).

**Comment by mschoch** [comment]
cc @abhinavdangeti

**Comment by abhinavdangeti** [comment]
Hmm, let me try writing up some test cases on this as well.

**Comment by mschoch** [comment]
OK, I now have an independent reproduction.  This can be dropped into top-level index_test.go:

```
func TestBooleanSearchBug1185(t *testing.T) {
	defer func() {
		err := os.RemoveAll("testidx")
		if err != nil {
			t.Fatal(err)
		}
	}()

	of := NewTextFieldMapping()
	of.Analyzer = keyword.Name
	of.Name = "owner"

	dm := NewDocumentMapping()
	dm.AddFieldMappingsAt("owner", of)

	m := NewIndexMapping()
	m.DefaultMapping = dm

	idx, err := NewUsing("testidx", m, "scorch", "scorch", nil)
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		err := idx.Close()
		if err != nil {
			t.Fatal(err)
		}
	}()

	err = idx.Index("17112", map[string]interface{}{
		"owner": "marty",
		"type":  "A Demo Type",
	})
	if err != nil {
		log.Fatal(err)
	}

	err = idx.Index("17139", map[string]interface{}{
		"type": "A Demo Type",
	})
	if err != nil {
		log.Fatal(err)
	}

	err = idx.Index("177777", map[string]interface{}{
		"type": "x",
	})
	if err != nil {
		log.Fatal(err)
	}
	err = idx.Index("177778", map[string]interface{}{
		"type": "A Demo Type",
	})
	if err != nil {
		log.Fatal(err)
	}

	err = idx.Index("17140", map[string]interface{}{
		"type": "A Demo Type",
	})
	if err != nil {
		log.Fatal(err)
	}

	err = idx.Index("17000", map[string]interface{}{
		"owner": "marty",
		"type":  "x",
	})
	if err != nil {
		log.Fatal(err)
	}

	err = idx.Index("17141", map[string]interface{}{
		"type": "A Demo Type",
	})
	if err != nil {
		log.Fatal(err)
	}

	err = idx.Index("17428", map[string]interface{}{
		"owner": "marty",
		"type":  "A Demo Type",
	})
	if err != nil {
		log.Fatal(err)
	}

	err = idx.Index("17113", map[string]interface{}{
		"owner": "marty",
		"type":  "x",
	})
	if err != nil {
		log.Fatal(err)
	}

	matchTypeQ := NewMatchPhraseQuery("A Demo Type")
	matchTypeQ.SetField("type")

	matchAnyOwnerRegQ := NewRegexpQuery(".+")
	matchAnyOwnerRegQ.SetField("owner")

	matchNoOwner := NewBooleanQuery()
	matchNoOwner.AddMustNot(matchAnyOwnerRegQ)

	notNoOwner := NewBooleanQuery()
	notNoOwner.AddMustNot(matchNoOwner)

	matchTypeAndNoOwner := NewConjunctionQuery()
	matchTypeAndNoOwner.AddQuery(matchTypeQ)
	matchTypeAndNoOwner.AddQuery(notNoOwner)

	req := NewSearchRequest(matchTypeAndNoOwner)
	res, err := idx.Search(req)
	if err != nil {
		log.Fatal(err)
	}

	// query 2
	matchTypeAndNoOwnerBoolean := NewBooleanQuery()
	matchTypeAndNoOwnerBoolean.AddMust(matchTypeQ)
	matchTypeAndNoOwnerBoolean.AddMustNot(matchNoOwner)

	req2 := NewSearchRequest(matchTypeAndNoOwnerBoolean)
	res2, err := idx.Search(req2)
	if err != nil {
		log.Fatal(err)
	}

	if len(res.Hits) != len(res2.Hits) {
		t.Fatalf("expected same number of hits, got: %d and %d", len(res.Hits), len(res2.Hits))
	}
}
```

When I run it:

```
$ go test -v -run=TestBooleanSearchBug1185
=== RUN   TestBooleanSearchBug1185
--- FAIL: TestBooleanSearchBug1185 (0.16s)
    index_test.go:2349: expected same number of hits, got: 2 and 4
FAIL
exit status 1
FAIL	github.com/blevesearch/bleve	0.176s
```

**Comment by mschoch** [comment]
Looking at the commit that causes the problem, it seems obviously wrong to me in some cases.  Having said that, we know it fixed a different issue, so now I need to go back and reexamine that issue.

**Comment by abhinavdangeti** [comment]
Ah thanks for the test case @mschoch. I'll spend some time on this issue today.

**Comment by mschoch** [comment]
So, here is my attempt to illustrate what I think is an obvious problem with the previous change.  Consider the following:

Searcher A - will return hits [1, 3, 5]
Searcher B - will return hits [1, 2, 3, 4, 5]
Searcher C - will return hit [5]

Now, imagine them arranged as follows:

A and Boolean(must: B must-not: C)

At some point, the conjunction will tell the boolean searcher to Advance(3).

So, thinking through how this condition will be evaluated:

```
	if (s.currentID == nil || s.currentID.Compare(ID) < 0) &&
		(s.currMustNot == nil || s.currMustNot.IndexInternalID.Compare(ID) < 0) {
```

I believe the boolean searcher currentID would have still been 1, and since 1 < 3 the first part of the condition is satisfied.
The currMustNot reader is pointing at 5, so the second comparison fails, which  means that we do not end up advancing any of the iterators.

Then we return `return s.Next(ctx)` which would return 2, which should not be a hit.

That is not exactly what happens in the unit test though, at least not exactly.  But it is a problem I see reading the current code.  I'm not sure how easily it would be to test my reading of the code at that level (as opposed to the top-level where more things come into play)

**Comment by mschoch** [comment]
I forgot to include my commentary on that, in my mind the Must searcher should be advanced independent of where the MustNot searcher is currently pointing (to me it seems unrelated).  However, there was presumably some compelling reason we made that change, which I have now forgotten.

**Comment by mschoch** [comment]
Actually disregard my example, it does not make sense as currently written, I'll try to refine it.

**Comment by mschoch** [comment]
So, the example is OK, but I should emphasize, the boolean searcher returning 2 isn't wrong, it satisfies the constraints.  But it would be a wrong state after calling Advance(3), violating the definition of how Advance() should behave.  Perhaps the conjunction searcher will still give the right overall behavior, but it would seem to be wrong internally.

**Comment by abhinavdangeti** [comment]
Hey @mschoch , so looking through the code - I think the problem has to do with the problem code that I reverted last Friday (I merged that in this morning).
I can reproduce the test failure with your above test case without the change. With the change, the test passes for me every time.

Do you see your test case failing every time you run it?

**Comment by abhinavdangeti** [comment]
Believe this has been addressed already.
