### ISSUE TITLE
license: missing year / copyright holder

### ISSUE THREAD

**Issue by felixge** [blevesearch/bleve#1199]
See https://github.com/blevesearch/bleve/blob/master/LICENSE#L190

**Comment by mschoch** [comment]
As near as I can tell, the appendix of the index simply provides a helpful example of how to apply the license to a particular file.  This line is essentially a template for how you should structure other files.

Here is the LICENSE file of the apache web server, it has the exact same form: https://github.com/apache/httpd/blob/trunk/LICENSE#L189
