### ISSUE TITLE
No more release?

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [blevesearch/bleve#1201]
this project is getting close? last release was 1 year ago. So,, I guessed so..
I am searching for Elastic alternative which is super heavy and memory consumed.. I hate it.
Can I use this for my project as an alternative of Elastic? Just worry about this project's activity in the future.

**Comment by hubyhuby** [comment]
Hi @NiNJAD3vel0per 
Your question has already been answered here
https://github.com/blevesearch/bleve/issues/1162

**Comment by mschoch** [comment]
We recently made releases on the `v1.0.x` line and development is active.
