### ISSUE TITLE
how to switch to another database such as moss / goleveldb?

### ISSUE THREAD

**Issue by hiqbn** [blevesearch/bleve#1219]
how to switch to another database such as moss / goleveldb?

I'm trying to write my own interface too. where can i start?

**Comment by mschoch** [comment]
> how to switch to another database such as moss / goleveldb?

If you want to use a different key/value store, you pass it's name as a kvstore argument to the `NewUsing` method here:

https://github.com/blevesearch/bleve/blob/master/index.go#L279

The recommended way to do this and ensure that the right packages are imported to your application, is to import the package, and use it's exported Name, like:

https://github.com/blevesearch/bleve/blob/master/index/store/moss/store.go#L35

However, that being said, we encourage everyone to use the new indexing scheme `scorch` as it performs better than the upsidedown indexing scheme (default) no matter which key/value store is used.

> I'm trying to write my own interface too. where can i start?

I'm not exactly sure which interface you mean.  If you want to plug in another key/value store, you have to implement this interface:

https://github.com/blevesearch/bleve/blob/master/index/store/kvstore.go#L22

**Comment by hiqbn** [comment]
looks good but very abstract.

any guidelines to how i can make this redis kvstore backend?

**Comment by mschoch** [comment]
No, there are no guidelines for how you can make a redis kvstore backend.
