### ISSUE TITLE
allocTermFieldReaderDicts leaks PostingsIterator

### ISSUE THREAD

**Issue by fproulx-dfuse** [blevesearch/bleve#1243]
We've noticed a memory leak, but it never was much an issue as those machines are in a "chaos monkey" type cluster where they are restarted on period basis. The leak is getting worse as we have more usage.

We are doing parallel searches on a few thousands indexes (about 10,000 moderate sized). Those are scorch indexes. We have many small indexes, because we create them with realtime data being indexed and where the new index has to be shared in a cluster, so we cannot have one very large index.

We think we have root caused the leak to be when we have queries with AND / OR and each index keeps `PostingIterator` objects in a pre-allocation pool (I guess for performance optimization), but this pool grows, instead of coming to a steady state / size.

We have run `pprof` and the allocation occurs in the `zap/posting.go` at line 225

Is there a way to cap the size or the pool in `allocTermFieldReaderDicts` , if that's indeed the root cause?

-----

```
github.com/blevesearch/bleve/index/scorch/segment/zap.(*PostingsList).iterator+0x701    /bleve/index/scorch/segment/zap/posting.go:225
github.com/blevesearch/bleve/index/scorch/segment/zap.(*PostingsList).Iterator+0x7d    /bleve/index/scorch/segment/zap/posting.go:153
github.com/blevesearch/bleve/index/scorch.(*IndexSnapshot).TermFieldReader+0x2f1    /bleve/index/scorch/snapshot_index.go:474
github.com/blevesearch/bleve/search/searcher.NewTermSearcherBytes+0xb7            /bleve/search/searcher/search_term.go:46
github.com/blevesearch/bleve/search/searcher.NewTermSearcher+0x11c            /bleve/search/searcher/search_term.go:41
github.com/blevesearch/bleve/search/query.(*TermQuery).Searcher+0x6d            /bleve/search/query/term.go:60
github.com/blevesearch/bleve/search/query.(*ConjunctionQuery).Searcher+0x149        /bleve/search/query/conjunction.go:58
github.com/XYZ/search.RunSingleIndexQuery+0x143                    /search/streamquery.go:192
```

**Comment by fproulx-eoscanada** [comment]
Looks like there's a `recycleTermFieldReader` in `IndexSnapshotTermFieldReader`, but it's only ever called upon `Close`, which in our case only happens when process quits.

Could there be a way to force this to occur on period basis, or have a cap as I said.

**Comment by mschoch** [comment]
It sounds like this might be a case where the implementation was optimized by Couchbase with a particular set of constraints in mind.  First, relatively few indexes (tens) and second, relatively steady stream of mutations coming in to the index (which introduces new root snapshots, eventually allowing older snapshots to be GC'd)

In the scenario you described, searches on 10,000 indexes would each end needing (and then caching) the TFRDicts.  If most of the indexes aren't receiving any mutations, these allocations hang around.  If you were to look at a memory profile, you'd see a large number of live objects allocated at that point.

I'm not ruling out an actual leak, as that is certainly possible, this is just an initial thinking through how it might be working in your particular use case.  I'd like to hear what @steveyen thinks as well.

**Comment by fproulx-eoscanada** [comment]
Our indices are immutable once we rotate to next shard. How could we limit this growth of TFRDicts or reset the cache ?

**Comment by fproulx-eoscanada** [comment]
@steveyen any feedback on this ?

**Comment by sreekanth-cb** [comment]
@steveyen is currently on a vacation, and I totally agree with Marty. 
@mschoch, Shall we move these recycle optimisations under a CB overridable flag?

**Comment by mschoch** [comment]
@sreekanth-cb I don't know, we have seen similar complains come up with vellum...

**Comment by steveyen** [comment]
(hi folks, I'm back in gear!)  @mschoch's theory here sounds totally plausible, imho.  One suggested next step is to try to get a simple reproduction -- then we'll know if a optional "want-the-optimization" flag does the trick or if there are other angles to this?

**Comment by markovichecha** [comment]
Hi. I've faced the same problem as OP. Do you have any plans on implementing max cap or periodic recycling? I can try to help with that. @abhinavdangeti

**Comment by sreekanth-cb** [comment]
@markovichecha, I shall be addressing this soon with a max cap solution.

**Comment by markovichecha** [comment]
@sreekanth-cb thank you :pray:
