### ISSUE TITLE
go get -u github.com/blevesearch/bleve@master failed

### ISSUE THREAD

**Issue by orange-jacky** [blevesearch/bleve#1248]
macbookpro:beleve_exam fredlee$ go get -u github.com/blevesearch/bleve@master
go: finding github.com/blevesearch/bleve master
go: downloading github.com/blevesearch/bleve v0.7.1-0.20190613153557-26d2099fa968
go: extracting github.com/blevesearch/bleve v0.7.1-0.20190613153557-26d2099fa968
go: finding github.com/etcd-io/bbolt v1.3.3
go: downloading github.com/etcd-io/bbolt v1.3.3
go: extracting github.com/etcd-io/bbolt v1.3.3
 github.com/blevesearch/bleve/index/scorch/segment/zap
../../../../pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190613153557-26d2099fa968/index/scorch/segment/zap/dict.go:287:2: not enough arguments to return
../../../../pkg/mod/github.com/blevesearch/bleve@v0.7.1-0.20190613153557-26d2099fa968/index/scorch/segment/zap/dict.go:287:14: i.itr.Exists undefined (type vellum.Iterator has no field or method Exists)

**Comment by mschoch** [comment]
We recently updated the vellum dependency.  It looks like you need to update it.

**Comment by orange-jacky** [comment]
how to update vellum dependency?

**Comment by mschoch** [comment]
Try

```
go get -u github.com/couchbase/vellum
```

**Comment by orange-jacky** [comment]
macbookpro:Downloads fredlee$ go get -u github.com/couchbase/vellum
go: finding github.com/couchbase/vellum latest
go: downloading github.com/couchbase/vellum v0.0.0-20190610201045-ec7b775d247f
go: extracting github.com/couchbase/vellum v0.0.0-20190610201045-ec7b775d247f
go build golang.org/x/sys/unix: no Go files in 

it update successful?

**Comment by mschoch** [comment]
That looks like the correct version, please try `go get` on bleve again and see if it works this time.

**Comment by orange-jacky** [comment]
it output :
acbookpro:Downloads fredlee$ go get -u github.com/blevesearch/bleve@master
go: finding github.com/blevesearch/bleve master
go: finding github.com/blevesearch/segment latest
go: finding github.com/steveyen/gtreap latest
go: finding github.com/golang/protobuf/proto latest
go: finding github.com/couchbase/vellum/levenshtein2 latest
go: finding github.com/couchbase/vellum/regexp latest
go: finding github.com/couchbase/vellum latest
go build golang.org/x/sys/unix: no Go files in 
macbookpro:Downloads fredlee$

**Comment by mschoch** [comment]
Closing this now as we have now adopted Go modules, and this should be working correctly.  Please open a new issue if you still have problems.
