### ISSUE TITLE
size of origin data is 1MB, bleve index it use 64MB, how to reduce use memory

### ISSUE THREAD

**Issue by orange-jacky** [blevesearch/bleve#1251]
size of origin data is 1MB, about 5000 records, when i use bleve index my origin data, it use large memory about 64MB, it's not too expensive, how to do something to reduce use memory?

my go profile
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20 -cum
Showing nodes accounting for 76.36MB, 65.65% of 116.31MB total
Dropped 16 nodes (cum <= 0.58MB)
Showing top 20 nodes out of 77
      flat  flat%   sum%        cum   cum%
         0     0%     0%    63.51MB 54.61%  github.com/blevesearch/bleve/index.AnalysisWorker
       3MB  2.58%  2.58%    63.51MB 54.61%  github.com/blevesearch/bleve/index/scorch.(*Scorch).Analyze
         0     0%  2.58%    46.44MB 39.93%  catweb_server/internal/async.Repeat.func1
         0     0%  2.58%    46.44MB 39.93%  catweb_server/internal/async.Repeat.func2
         0     0%  2.58%    44.01MB 37.84%  github.com/blevesearch/bleve/document.(*TextField).Analyze
   38.51MB 33.11% 35.69%    38.51MB 33.11%  github.com/blevesearch/bleve/analysis.TokenFrequency
         0     0% 35.69%    34.94MB 30.04%  github.com/blevesearch/bleve.(*indexImpl).Batch
         0     0% 35.69%    34.94MB 30.04%  github.com/blevesearch/bleve/index/scorch.(*Scorch).Batch
         0     0% 35.69%    25.62MB 22.03%  catweb_server/util.indexGlobalAirport
         0     0% 35.69%    23.35MB 20.08%  github.com/blevesearch/bleve/index/scorch/segment/mem.NewFromAnalyzedDocs
    3.39MB  2.91% 38.60%    21.35MB 18.36%  github.com/blevesearch/bleve/index/scorch/segment/mem.(*Segment).initializeDict
         0     0% 38.60%    20.82MB 17.90%  catweb_server/util.indexAircompany
   16.50MB 14.19% 52.79%    16.50MB 14.19%  github.com/blevesearch/bleve/analysis.TokenFrequencies.MergeAll
         0     0% 52.79%    16.50MB 14.19%  github.com/blevesearch/bleve/document.(*CompositeField).Compose
   14.96MB 12.86% 65.65%    14.96MB 12.86%  github.com/blevesearch/bleve/index/scorch/segment/mem.(*Segment).initializeDict.func1
         0     0% 65.65%    11.50MB  9.89%  github.com/blevesearch/bleve.(*Batch).Index
         0     0% 65.65%    11.09MB  9.53%  github.com/blevesearch/bleve/index/scorch/segment/zap.NewSegmentBase
         0     0% 65.65%    11.09MB  9.53%  github.com/blevesearch/bleve/index/scorch/segment/zap.persistBase
         0     0% 65.65%    10.50MB  9.03%  github.com/blevesearch/bleve/mapping.(*IndexMappingImpl).MapDocument
         0     0% 65.65%     8.50MB  7.31%  github.com/blevesearch/bleve/mapping.(*DocumentMapping).walkDocument

**Comment by orange-jacky** [comment]
my code load data from mongo
//--------------------------------------------------
type (
	GlobAirport struct {
		Id           string `bson:"_id" json:"id"`
		Cnname       string `bson:"cnname" json:"cnname"`
		Citycode     string `bson:"citycode" json:"citycode"`
		Citycn       string `bson:"citycn" json:"citycn"`
		Enname       string `bson:"enname" json:"enname"`
		Country      string `bson:"country" json:"country"`
		Province     string `bson:"province" json:"province"`
		Cityen       string `bson:"cityen" json:"cityen"`
		Country_code string `bson:"country_code" json:"country_code"`
		Region_code  string `bson:"region_code" json:"region_code"`
		Region_name  string `bson:"region_name" json:"region_name"`
		City_pinyin  string `bson:"city_pinyin" json:"city_pinyin"`
		City_jianpin string `bson:"city_jianpin" json:"city_jianpin"`
	}
	GlobAirports struct {
		filename string
		sli      []GlobAirport
		citys    map[string][]*GlobAirport //key是城市三字码
		airports map[string]*GlobAirport   //key是机场三字码
	}
)

func NewGlobAirports(filename string) *GlobAirports {
	return &GlobAirports{filename: filename}
}

func (m *GlobAirports) LoadFromDb() (num int, err error) {
	var sli []GlobAirport
	mgoc := MongoRead()
	handler := func(client *mongo.Client) (err error) {
		collection := client.Database(mgoc.Database).Collection(GetGlobalAirportCollection().Collection)
		ctx, cancle := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancle()
		cur, err := collection.Find(ctx, bson.D{})
		if err != nil {
			return
		}
		defer cur.Close(ctx)
		for cur.Next(ctx) {
			var result GlobAirport
			err := cur.Decode(&result)
			if err != nil {
				continue
			}
			// do something with result....
			sli = append(sli, result)
		}
		if err = cur.Err(); err != nil {
			return
		}
		return
	}
	err = mgoc.Do(handler)
	if err != nil {
		return
	}

	num = len(sli)
	if num > 0 {
		oldSli := m.sli
		m.sli = sli
		oldSli = oldSli[:0]
	}
	return
}


build index code

const (
	IndexPathRoot          = "conf/autogen/index/"
	IndexPathGlobalAirport = IndexPathRoot + "example.globalAirport"
)

func buildGlobalAirportIndexMapping() (mapping.IndexMapping, error) {
	// a generic reusable mapping for english text
	englishTextFieldMapping := bleve.NewTextFieldMapping()
	englishTextFieldMapping.Analyzer = en.AnalyzerName

	// a generic reusable mapping for keyword text
	//	keywordFieldMapping := bleve.NewTextFieldMapping()
	//	keywordFieldMapping.Analyzer = keyword.Name

	docMapping := bleve.NewDocumentMapping()

	docMapping.AddFieldMappingsAt("id", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("cnname", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("citycode", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("citycn", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("enname", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("country", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("province", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("cityen", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("city_pinyin", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("city_jianpin", englishTextFieldMapping)

	indexMapping := bleve.NewIndexMapping()
	indexMapping.DefaultAnalyzer = "en"
	indexMapping.DefaultMapping = docMapping
	indexMapping.IndexDynamic = true

	return indexMapping, nil
}

func indexGlobalAirport() {
	_mylog := mylog.GetMylog().Log()
	bufLog := mempool.BytesBufferPool.Get()

	defer func() {
		if bufLog.Len() > 0 {
			_mylog.Infof("%s", bufLog.Bytes())
			mempool.BytesBufferPool.Put(bufLog)
		}
	}()

	common.CreateDir(IndexPathGlobalAirport)

	//Indexing
	indexPath := IndexPathGlobalAirport
	var err error
	var index bleve.Index
	if _, err = os.Stat(indexPath); os.IsNotExist(err) {
		//mapping := bleve.NewIndexMapping()
		mapping, _ := buildGlobalAirportIndexMapping()
		index, err = bleve.NewUsing(indexPath, mapping, scorch.Name, scorch.Name, nil)
		//index, err = bleve.New(indexPath, mapping)
		if err != nil {
			bufLog.WriteString(fmt.Sprintf("%v", err))
			return
		}
	} else {
		index, err = bleve.Open(indexPath)
		if err != nil {
			bufLog.WriteString(fmt.Sprintf("%v", err))
			return
		}
	}

	batch := index.NewBatch()
	g := GlobalAirportInstance()
	slice := g.GetAllRec()
	for i := range slice {
		batch.Index(slice[i].Id, slice[i])
	}

	start := time.Now()
	err = index.Batch(batch)
	if err != nil {
		bufLog.WriteString(fmt.Sprintf("%v", err))
		return
	}
	end := time.Now()

	// 2 documents have been indexed
	count, err := index.DocCount()
	if err != nil {
		bufLog.WriteString(fmt.Sprintf("%v", err))
		return
	}

	err = index.Close()
	if err != nil {
		bufLog.WriteString(fmt.Sprintf("%v", err))
		return
	}
	bufLog.WriteString(fmt.Sprintf("batch index %d records, cost %s", count, end.Sub(start).String()))
}

/////////////////////////////////////////////////////////////
type indexGlobalAirportClass struct {
	cancel context.CancelFunc // The cancellation function.
}

var (
	indexGlobalAirportC      *indexGlobalAirportClass
	indexGlobalAirportC_once sync.Once
)

func IndexGlobalAirportInstance() *indexGlobalAirportClass {
	indexGlobalAirportC_once.Do(func() {
		interval := 60
		indexGlobalAirportC = &indexGlobalAirportClass{
			cancel: async.Repeat(context.Background(), time.Duration(interval)*time.Second, indexGlobalAirport),
		}
	})
	return indexGlobalAirportC
}

func (m *indexGlobalAirportClass) Stop() {
	if m.cancel != nil {
		m.cancel()
	}
}


my repeat code

// Repeat performs an action asynchronously on a predetermined interval.
func Repeat(ctx context.Context, interval time.Duration, action func()) context.CancelFunc {

	// Create cancellation context first
	ctx, cancel := context.WithCancel(ctx)
	safeAction := func() {
		defer handlePanic()
		action()
	}
	// Perform the action for the first time, syncrhonously
	safeAction()
	timer := time.NewTicker(interval)
	go func() {

		for {
			select {
			case <-ctx.Done():
				timer.Stop()
				return
			case <-timer.C:
				safeAction()
			}
		}
	}()
	return cancel
}

// handlePanic handles the panic and logs it out.
func handlePanic() {
	if r := recover(); r != nil {
		log.Printf("async panic recovered: %s %s\n", r, debug.Stack())
	}
}

**Comment by orange-jacky** [comment]
no reply?

**Comment by mschoch** [comment]
@orange-jacky 

1.  You pasted a lot of code, and it isn't formatted in a way that is easy to read.  Providing the code is helpful, but understand that due to the volume it takes time for others to understand it.
2.  It isn't clear to me if you're asking about reducing the size of the index on disk, or if you're trying to reduce the memory overhead of the process.

**Comment by orange-jacky** [comment]
i can send my program code to you , can you give me a email?

**Comment by orange-jacky** [comment]
@mschoch 
i had sent a email to marty.schoch@gmail.com,  my email is blade2iron@gmail.com
hope that you can help me to fix the two issue

**Comment by orange-jacky** [comment]
hope your reply

**Comment by hubyhuby** [comment]
Dear @orange-jacky 
You may want to have a look at a very similar topic here :
https://github.com/blevesearch/bleve/issues/1186
The "regular " behaviour with the old index is an index size x100 the original data set. With the new it is much improved at x7. Hopes are to get it at X1

**Comment by orange-jacky** [comment]
@hubyhuby  could i send my project code to your email, and you can reproduce my issue.  first i will look in #1186 and i hope you and @mschoch  can help anlayse my project code

**Comment by orange-jacky** [comment]
@mschoch @hubyhuby  my issue is  the flowing content, it's different from #1186

i use bleve as my search engine for my program, than i found that size of origin data is 1MB, building index by bleve it use 50~60MB memory, it’s too larger than 1MB.
        i send my program code to you , and hope than you can guide me fix two issue. one is how to reduce memory size when building index by bleve, the other is when i use net/http/pprof and top command profile my program, the size of RES is about 440MB, can you guide me how to reduce res of top command.

    hope to your reply
    best wishes


go tool pprof ouput
File: catweb_server
Build ID: 99aa39b005b084eec789b8ae15f82e39d410cffa
Type: inuse_space
Time: Jun 19, 2019 at 10:18am (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top20 -cum
Showing nodes accounting for 51.13MB, 51.28% of 99.72MB total
Showing top 20 nodes out of 100
      flat  flat%   sum%        cum   cum%
         0     0%     0%    52.01MB 52.16%  github.com/blevesearch/bleve/index.AnalysisWorker
       1MB  1.00%  1.00%    52.01MB 52.16%  github.com/blevesearch/bleve/index/scorch.(*Scorch).Analyze
         0     0%  1.00%    40.47MB 40.58%  catweb_server/internal/async.Repeat.func1
         0     0%  1.00%    40.47MB 40.58%  catweb_server/internal/async.Repeat.func2
         0     0%  1.00%    40.01MB 40.12%  github.com/blevesearch/bleve/document.(*TextField).Analyze
   36.51MB 36.61% 37.61%    36.51MB 36.61%  github.com/blevesearch/bleve/analysis.TokenFrequency
         0     0% 37.61%    27.85MB 27.93%  github.com/blevesearch/bleve.(*indexImpl).Batch
    0.52MB  0.53% 38.14%    27.85MB 27.93%  github.com/blevesearch/bleve/index/scorch.(*Scorch).Batch
         0     0% 38.14%    22.49MB 22.55%  catweb_server/util.indexGlobalAirport
         0     0% 38.14%    17.98MB 18.03%  catweb_server/util.indexAircompany
         0     0% 38.14%    16.95MB 16.99%  github.com/blevesearch/bleve/index/scorch/segment/mem.NewFromAnalyzedDocs
    2.10MB  2.10% 40.24%    14.45MB 14.49%  github.com/blevesearch/bleve/index/scorch/segment/mem.(*Segment).initializeDict
         0     0% 40.24%    12.62MB 12.65%  github.com/blevesearch/bleve.(*Batch).Index
         0     0% 40.24%       12MB 12.04%  github.com/blevesearch/bleve/mapping.(*IndexMappingImpl).MapDocument
      11MB 11.04% 51.28%       11MB 11.04%  github.com/blevesearch/bleve/analysis.TokenFrequencies.MergeAll
         0     0% 51.28%       11MB 11.04%  github.com/blevesearch/bleve/document.(*CompositeField).Compose
         0     0% 51.28%       10MB 10.03%  github.com/blevesearch/bleve/mapping.(*DocumentMapping).processProperty
         0     0% 51.28%       10MB 10.03%  github.com/blevesearch/bleve/mapping.(*DocumentMapping).walkDocument
         0     0% 51.28%     9.38MB  9.40%  github.com/blevesearch/bleve/index/scorch/segment/zap.NewSegmentBase
         0     0% 51.28%     9.38MB  9.40%  github.com/blevesearch/bleve/index/scorch/segment/zap.persistBase
(pprof) 


top command output
top - 10:20:01 up 2 days, 19:27,  3 users,  load average: 0.08, 0.15, 0.14
Tasks: 130 total,   1 running, 129 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.8 us,  5.2 sy,  0.0 ni, 90.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  1917016 total,   534460 free,   837892 used,   544664 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   858220 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                     
27832 ubuntu    20   0  780468 445708  22076 S  0.0 23.3   1:28.53 catweb_server               
 2589 999       20   0 1140188 198548      0 S  0.0 10.4   2:09.72 mysqld                      
 2728 999       20   0 1176112  49980      0 S  0.0  2.6  11:46.38 mongod                      
 1167 root      20   0  458124  33088   2540 S  0.0  1.7   0:48.45 dockerd                     
 1176 root      20   0  416736  19016   2544 S  0.0  1.0   1:22.56 containerd                  
 1366 root      20   0  578940  17948   4900 S  0.7  0.9  11:10.36 YDService                   
 1976 root      20   0  507308  12472   3204 S  0.3  0.7  13:10.80 barad_agent                 
 1975 root      20   0   56544  10324   3044 S  0.0  0.5   2:08.36 barad_agent                 
 1101 root      20   0  195864  10088   6752 S  0.0  0.5   0:03.83 snapd                       
 3067 ubuntu    20   0  119304   9620   2436 S  8.3  0.5 179:17.09 oa_server                   
 1974 root      20   0   53696   7868   1356 S  0.0  0.4   0:03.49 barad_agent                 
  667 root      20   0   92676   6532   5632 S  0.0  0.3   0:00.00 sshd                        
16170 ubuntu    20   0   21876   5040   2884 S  0.0  0.3   0:00.35 bash                        
    1 root      20   0   38052   4952   2848 S  0.0  0.3   0:08.38 systemd                     
31989 ubuntu    20   0   21840   4768   2648 S  0.0  0.2   0:00.06 bash

**Comment by sreekanth-cb** [comment]
@orange-jacky , didn't check your code thoroughly. But looks like you use the default NewTextFieldMapping which sort of enables all the indexing options internally. ref: https://github.com/blevesearch/bleve/blob/9b6e89951d4e9207356a833a7d99577cfe249208/mapping/field.go#L66

Also noted that indexMapping.IndexDynamic = true

Perhaps you should revisit these mappings/indexing options to suit your exact query time requirements.

A quick glance for the implications of these indexing options can be found in a related topic here: https://blog.couchbase.com/full-text-search-indexing-best-practices/

As you mentioned about MongoDB here,  
Couchbase already has this FTS functionality fully integrated(bleve based), abstracted and ready to use for customers.
