### ISSUE TITLE
Indexing URL

### ISSUE THREAD

**Issue by SystemR** [blevesearch/bleve#1260]
Hello, I saw this commit: https://github.com/blevesearch/bleve/commit/e472b3e807398a2ceba1ed36c9e2219d9e5129f4 and I thought it would fix the indexing of URL. However the following test fails:

```golang
func main() {
	// open a new index
	index, _ := bleve.NewMemOnly(bleve.NewIndexMapping())

	index.Index("1", "www.google.ca")
	index.Index("2", "Bing Search www.bing.com")
	index.Index("3", "www.google.com")

	// Correct
	query := bleve.NewMatchQuery("bing")
	searchResults, _ := index.Search(bleve.NewSearchRequest(query))
	fmt.Println(searchResults.Hits[0].ID == "2")

	// No matches
	query = bleve.NewMatchQuery("google")
	searchResults, _ = index.Search(bleve.NewSearchRequest(query))
	fmt.Println(searchResults)

	// No matches
	matchPhraseQuery := bleve.NewMatchPhraseQuery("google")
	searchResults, _ = index.Search(bleve.NewSearchRequest(matchPhraseQuery))
	fmt.Println(searchResults)

	// No matches
	fuzzyQuery := bleve.NewFuzzyQuery("google")
	searchResults, _ = index.Search(bleve.NewSearchRequest(fuzzyQuery))
	fmt.Println(searchResults)
}
```

**Comment by mschoch** [comment]
There are several things going on here.

1.  The commit you referenced introduces a new analyzer named `web`, but your index mapping here does not use it.
2.  The data you're indexing has no fields, just a top-level string, this may work, but is likely to cause more issues unrelated to the one you want to focus on.  Put data in struct (with exported fields) or map to  remove this issue.
3.  The `web` analyzer isn't going to do what you want anyway.  In fact, what it does is try to keep web-like-things intact as a single token, so that you can do exact matching on them as a whole, not deconstructing them to find parts.

Somewhat counter-intuitively, the analyzer that does what you want (but does lots of other things wrong) is the `simple` analyzer.

```
package main

import (
	"fmt"

	"github.com/blevesearch/bleve/analysis/analyzer/simple"

	"github.com/blevesearch/bleve"
)

func main() {
	// open a new index
	m := bleve.NewIndexMapping()
	m.DefaultAnalyzer = simple.Name
	index, _ := bleve.NewMemOnly(m)

	index.Index("1", map[string]string{"url":"www.google.ca"})
	index.Index("2", map[string]string{"url":"Bing Search www.bing.com"})
	index.Index("3", map[string]string{"url":"www.google.com"})

	// Correct
	query := bleve.NewMatchQuery("bing")
	searchResults, _ := index.Search(bleve.NewSearchRequest(query))
	fmt.Println(searchResults.Hits[0].ID == "2")

	// No matches
	query = bleve.NewMatchQuery("google")
	searchResults, _ = index.Search(bleve.NewSearchRequest(query))
	fmt.Println(searchResults)

	// No matches
	matchPhraseQuery := bleve.NewMatchPhraseQuery("google")
	searchResults, _ = index.Search(bleve.NewSearchRequest(matchPhraseQuery))
	fmt.Println(searchResults)

	// No matches
	fuzzyQuery := bleve.NewFuzzyQuery("google")
	searchResults, _ = index.Search(bleve.NewSearchRequest(fuzzyQuery))
	fmt.Println(searchResults)
}
```

**Comment by abhinavdangeti** [comment]
Using bleve.NewIndexMapping() without any further changes to it sets the default_analyzer to "standard", which analyses the text "www.google.ca" and generates tokens ["www.google.ca"] for it. If you're just searching for google, and expect a hit, I would recommend setting the DefaultAnalyzer to "simple" perhaps. Here's how you can do it ..

    import (
        "github.com/blevesearch/bleve/analysis/analyzer/simple"
    )
    ...
    indexMapping := bleve.NewIndexMapping()
    indexMapping.DefaultAnalyzer = simple.Name
    index, _ := bleve.NewMemOnly(indexMapping)
    ... 

The simple analyzer would generate tokens ["www", "google", "ca"] for your text. Here's a service we support that you could use in understanding what tokens are generated by any analyzer for a provided text: http://bleveanalysis.couchbase.com/analysis

**Comment by abhinavdangeti** [comment]
Hah @mschoch was quicker :)

**Comment by SystemR** [comment]
Ooh, thanks everyone! Even with `simple` analyzer though, if I try to do:
```golang
        query = bleve.NewMatchQuery("goog")
	searchResults, _ = index.Search(bleve.NewSearchRequest(query))
	fmt.Println(searchResults)
```

the search for `goog` still doesn’t return 1 and 3. 

http://bleveanalysis.couchbase.com/analysis should be on the doc site!

**Comment by abhinavdangeti** [comment]
If you want to match "goog" with "google", set fuzziness for the match query to 2.
The link is here on this page: http://blevesearch.com/videos/

**Comment by SystemR** [comment]
That feels arbitrary. Is there a query type that would, by default match, a subset of the value? like `goog`,  `oog`, `oogle` would match the token `www.google.com` and `www.google.ca`.

**Comment by abhinavdangeti** [comment]
Yea you could build a custom analyzer -> create an n-gram token filter for it.
If the length of tokens are ranging from 3-5, set min for the n-gram to 3, and max to 5.

**Comment by SystemR** [comment]
I’ll give that a try. Thanks @abhinavdangeti!
