### ISSUE TITLE
Scorch indexing performance

### ISSUE THREAD

**Issue by tmm1** [blevesearch/bleve#1266]
I've been running some tests with scorch, trying to switch from upsidedown/leveldb.

My dataset is approximately 30k documents, which I index in batches of 500.

I'm noticing severe performance degradation as the size of the index increases. The first few batches of 500 documents are indexed within milliseconds. However, once I get towards the end each batch takes upwards of 20s to index.

Is this a known issue? Would be helpful for me to write a small reproduction?

**Comment by mschoch** [comment]
This is expected when scorch is run in "safe" mode (which is the default).  In this mode, a ball to Index() or Batch() won't return until the data is actually on disk.  In scorch there are some background operations running currently with your indexing.  One of them merges smaller segments into larger ones.  I believe that at some point we will actually block indexing because the merger is too far behind (not sure if that is happening in your case or not, cc @sreekanth-cb)

If your goal is to get the data searchable as soon as possible (even if the data is not persisted to disk yet), you could consider the `unsafe_batch` mode (poorly named).  In this mode, Batch() operations will return as soon as the data is searchable, and you can immediately continue indexing more data.  Obviously, this consumes space on the heap as it takes time for data to be persisted to disk (at which point we mmap the data, and it will be accessible without consuming heap space)

**Comment by sreekanth-cb** [comment]
As there is only 30k documents with a batch size of 500, it will be just 60 batch operations and at the max 60 files on disk. The default disk files threshold number (~1000) upon which the persister pauses for the file merger to catch up is of lesser probability here.
The persister also has a pause-ing mechanism for the memory merger to progress, but for that config knob of PersisterNapTimeMSec has to be explicitly configured.

Also, I guess memory pressure triggered indexing slow down isn't applicable too in this case.

So trying unsafe batch seems like the work around here.

@tmm1 , can you confirm whether you are on the latest bleve master Or a any older commit version.

**Comment by tmm1** [comment]
I was using v0.7.1-0.20190703014854-f9e403422719 in my test.

I will try with unsafe_batch to see what happens.

**Comment by mschoch** [comment]
@tmm1 v0.7 is quite old and had known issues similar to what you've reported.  See: https://github.com/blevesearch/bleve/issues/1037

I suggest trying master while we work to make a new release.

**Comment by tmm1** [comment]
I'm using go modules and that's the version number it assumes based on the tags. The actual revision is f9e403422719 which is only a couple commits behind.

**Comment by mschoch** [comment]
Right, unfortunately we don't support Go modules yet.

**Comment by tmm1** [comment]
When a project doesn't support go modules itself, importing it basically makes up a version number based on the closest matching tag. The version number doesn't really matter, the date and commit sha appended to it dictate what is being used.

Thanks for linking #1037 for some more context. If couchbase is using `unsafe_batch` by default, it seems like that might be the way for me to go as well.

**Comment by mschoch** [comment]
Couchbase and another major vendor I have contracted for both use `unsafe_batch`.

It is "safe" provided:
- you're not using bleve for primary storage
- you have some way to track which items *actually* made it to disk, so that upon a restart of your bleve process you can re-index any items which may have been lost (this can be done internally by recording sequence numbers in bleve internal storage, or externally using the persisted callback on your batches.

**Comment by tmm1** [comment]
Wonder, appreciate that explanation! Sounds perfect for my use-case, as I'm basically just building a searchable local cache.

You mentioned that memory usage could increase in unsafe_batch mode. Is there a way to set a limit? Some of my devices are memory constrained although the vast majority are not.

**Comment by tmm1** [comment]
I re-ran my test with `unsafe_batch` and the results are much more consistent. Each batch takes 1s to complete!

**Comment by mschoch** [comment]
Controlling memory usage in Go is difficult, but we try...

The scorch index implementation (need to access it directly) exposes a MemoryUsed() method:

https://github.com/blevesearch/bleve/blob/master/index/scorch/scorch.go#L555

This gives an estimate of how much heap space bleve is using for this index.  It does not account for running queries, which can also consume significant amounts of memory.

If you're concerned about query memory usage as well, we have:

https://github.com/blevesearch/bleve/blob/master/search.go#L571

This too isn't a complete estimate as parts of it are hard to estimate before running the query, but it can be used to reject executing a query that you know will require a lot of memory, if you're already in a high memory situation.

All of this just lets you account for memory, but what can you do about it when it's too high?

Scorch has an eventCallback:

https://github.com/blevesearch/bleve/blob/master/index/scorch/scorch.go#L116

One of the events is `EventKindBatchIntroductionStart`, and what Couchbase does is use it to check if the memory is high, and if so, you can block here until the memory situation improves.

The actual couchbase impl is a bit more complicated, but may be helpful to refer to here:

https://github.com/couchbase/cbft/blob/master/cmd/cbft/app_herder.go

**Comment by tmm1** [comment]
It looks like once I removed my usage of `SetInternal` (in #1267), indexing performance has stabilized and is consistently the same with and without `unsafe_batch`.

**Comment by mschoch** [comment]
That also makes some sense.  As I said scorch isn't really optimized for a lot of data being stored with `SetInternal` so that could have been related to the indexing slowdown you were observing.

**Comment by tmm1** [comment]
Looks like I am hitting some memory related issues during scorch indexing:

>error opening new segment at search/store/000000000225.zap, cannot allocate memory

(I am NOT using `unsafe_batch`)

> One of the events is `EventKindBatchIntroductionStart`, and what Couchbase does is use it to check if the memory is high, and if so, you can block here until the memory situation improves.

Is this the only way to control memory usage, by stalling in-between batches when memory usage is high in order to let them process and persist to disk in the background?

Is there any other knob available on the scorch backend to tell it to make batch submission slower in favor of lower memory usage?

How does batch size come into play here? I'm using batches of 500 records, but I'm guessing changing that doesn't matter much as the scorch persister will still hold them in RAM an read more records as it tries to combine zap files together?

**Comment by tmm1** [comment]
> Is there any other knob available on the scorch backend to tell it to make batch submission slower in favor of lower memory usage?

@mschoch @sreekanth-cb any pointers here?

**Comment by sreekanth-cb** [comment]
@tmm1 , usually these memory pressure handling/slowing down the ingestion is done at a higher level and I have never explored much on the direct bleve/scorch level tunings.

But one option you could explore is that - can you set DefaultPersisterNapUnderNumFiles to zero
https://github.com/blevesearch/bleve/blob/master/index/scorch/persister.go#L61 and try the indexing.

My thinking here is that - this would let the persister to skip any in-between naps / pauses to result in aggressively persisting the in-memory segments [from batches] to at least have more room before it goes out of memory. (ie this would result in more segment files on disk and more work for merger or memory pressure from segment merging.  Not sure whether it would give enough relief in your case as this may not help if you a high velocity indexing of batches)

So if you have continuous stream of incoming batches for indexing, a better solution has to control the batch ingestions externally by carefully listening and acting on those callbacks during those events like indexing/merging/searching etc at the scorch level.
 
Above app_herder sample is a good starting point..

It would be nice to know the observations you had with  DefaultPersisterNapUnderNumFiles = 0.

**Comment by tmm1** [comment]
Thanks @sreekanth-cb!

So I would pass options as so to bleve.NewUsing:

              "scorchPersisterOptions": map[string]interface{}{
                    "PersisterNapUnderNumFiles": 0,
                },

Would this ensure the unspecified fields still get initialized to their default values?

**Comment by sreekanth-cb** [comment]
yes

**Comment by tmm1** [comment]
Changing PersisterNapUnderNumFiles=0 did not help with the "cannot allocate memory" errors.

**Comment by tmm1** [comment]
Sorry I did it wrong. Changing bleve.NewUsing doesn't make sense because the index already exists. Is there any way to pass opens to bleve.Open?
