### ISSUE TITLE
Scorch Index Compression?

### ISSUE THREAD

**Issue by tmm1** [blevesearch/bleve#1267]
I'm evaluating scorch as a replacement for upsidedown/leveldb.

Currently I use leveldb with snappy enabled, which leads to highly compressed index size. 

With a test set of 50k documents, my leveldb index is 250MB while the same data in scorch is 1.8GB.

Are there any plans to add compression to scorch?

**Comment by tmm1** [comment]
Interesting.. it's the root.bolt file that's the bulk of the space. Is that where the documents are stored?

```
$ ls -alh airings/store
total 1.8G
-rw-------  1 tmm1 staff  12M Jul 24 10:40 000000000018.zap
-rw-------  1 tmm1 staff  34M Jul 24 10:41 000000000057.zap
-rw-------  1 tmm1 staff 7.2M Jul 24 10:41 000000000092.zap
-rw-------  1 tmm1 staff  32M Jul 24 10:42 00000000009c.zap
-rw-------  1 tmm1 staff 7.4M Jul 24 10:41 00000000009d.zap
-rw-------  1 tmm1 staff 9.0M Jul 24 10:42 0000000000aa.zap
-rw-------  1 tmm1 staff  12M Jul 24 10:42 0000000000b9.zap
-rw-------  1 tmm1 staff  13M Jul 24 10:42 0000000000cb.zap
-rw-------  1 tmm1 staff  16M Jul 24 10:43 0000000000e1.zap
-rw-------  1 tmm1 staff 5.8M Jul 24 10:43 0000000000ea.zap
-rw-------  1 tmm1 staff 1.7G Jul 24 10:50 root.bolt
```

**Comment by mschoch** [comment]
This doesn't match what we have observed, but I've never used bleve/leveldb in production.

Compared to bleve/boltdb scorch is like 6x smaller, and I think compared to moss it was about 2x smaller.

**Comment by mschoch** [comment]
Ah, that is suspicious, the root.bolt is only used to store index meta-data.

Are you using bleve internal storage?

**Comment by tmm1** [comment]
> Are you using bleve internal storage?

Aha, it looks like I am.

I guess in the case of leveldb the internal storage was going into compressed ldb files, whereas now its going uncompressed into the bolt database.

**Comment by mschoch** [comment]
Can I ask how you're using it?

Heavy use of internal storage is not really supported in scorch design.

**Comment by tmm1** [comment]
I'm using it to store a copy of the entire original document. At the time this was the easiest way to take advantage of the existing leveldb kv store. Now it probably makes more sense for me to use a dedicatd k/v store that's separate from bleve.

The actual zap index files in my test amount to only ~150MB, so scorch is doing great in terms of disk space. I'm going to close this issue.

**Comment by mschoch** [comment]
One suggestion would be to add a field your index called "_source" that is stored, but not indexed.  Then you can put some representation of your original document there.

This isn't suitable for primary storage, but can be a cleaner way to keep a copy of the original.

If you do this, the data will be snappy compressed.

**Comment by tmm1** [comment]
> This isn't suitable for primary storage, but can be a cleaner way to keep a copy of the original.

Thanks. I will try this.



> If you do this, the data will be snappy compressed.

How so.. does scorch use snappy somewhere? Where does this `_source` field end up when I use scorch?

**Comment by mschoch** [comment]
> How so.. does scorch use snappy somewhere? Where does this `_source` field end up when I use scorch?

Yes, there is nothing special about the `_source` field or name, it just consistent with what Elasticsearch uses for the same purpose.

The zap file format, used by scorch for storing segments will snappy compress all of the stored field data.  You can read more about the format here: https://github.com/blevesearch/bleve/blob/041857ee861b9cc2493bc773964eca0787deffbd/index/scorch/segment/zap/zap.md#stored-fields

**Comment by tmm1** [comment]
Gotcha, that sounds like what I should have been doing all along.

The source document in my case is a byte blob (encoded with gob).

What's the best mapping to use in this case? Would this be optimal:

```
&mapping.FieldMapping{
	Type:  "text",
	Store: true,
}
```

**Comment by mschoch** [comment]
That looks right to me.

**Comment by tmm1** [comment]
Hmm, I think I must be doing something incorrect because I can't get it to work.

I recreated my mapping with a new field:

```
	source := &mapping.FieldMapping{
		Type:  "text",
		Store: true,
	}
	airing := bleve.NewDocumentStaticMapping()
	...
	airing.AddFieldMappingsAt("_Airing", source)
```

then in my searches I ask for that new field:

```
	searchRequest.Fields = []string{"_Airing"}
	searchResult, err := index.Search(searchRequest)
	for _, hit := range searchResult.Hits {
				if data, ok := hit.Fields["_Airing"].([]byte); !ok {
					log.Printf("[WRN] unknown type %T for _Airing", hit.Fields["_Airing"])
				}
```

and I'm seeing messages like:

>2019/07/24 12:47:50 [WRN] unknown type <nil> for _Airing

I'm pretty sure the data is going into the index correctly since indexing time increased when I switched from SetInternal.

Am I doing the right thing in terms of storing and retrieving this new field?

**Comment by mschoch** [comment]
Can you remove the type assertion to `[]byte` and verify that data is at least coming back?  I expect it to be type `string`, but it would be better to verify that you see something first.

**Comment by tmm1** [comment]
It's not coming back at all, as shown by `%T` saying `<nil>`. I also tried to print out `hit.Fields` and its empty. When I use `searchRequest.Fields = []string{"*"}` I get back a couple of fields but not _Airing.

**Comment by tmm1** [comment]
Okay if I change the input document from []byte to string, then it gets stored as expected and comes back as a string in `hit.Fields`.
