### ISSUE TITLE
Listing all uniq terms.

### ISSUE THREAD

**Issue by mephux** [blevesearch/bleve#127]
Is there a way to list all uniq terms indexed? Sorry if I missed something in the docs.. could find any info on it. Would it be easy to add a func Terms() []string to the bleve.Index interface?

**Comment by mschoch** [comment]
The new methods available on the Index interface to support enumerating terms used in a field are:

```
	FieldDict(field string) (index.FieldDict, error)
	FieldDictRange(field string, startTerm []byte, endTerm []byte) (index.FieldDict, error)
	FieldDictPrefix(field string, termPrefix []byte) (index.FieldDict, error)
```

These all return an index.FieldDict interface, which returns terms using the Next() method.  Terms are returned in sorted order (useful if you're building another datastructure for fuzzy matching in the future).  Be sure to call Close() when you are done, as many of the underlying datastores hold resources open while we traverse the terms.

**Comment by mephux** [comment]
@mschoch awesome work man.

**Comment by tmm1** [comment]
Would `FieldDict` for a field have better performance compared to a `FacetRequest` on the same field (with a `NewMatchAllQuery` of size=0)?

**Comment by mschoch** [comment]
I would expect FieldDict to perform better, as it doesn't concern itself with any of the document information in the index.  The FacetRequest also has to build up (potentially large) maps finding all the unique terms, whereas the FieldDict simply accesses it directly.

**Comment by tmm1** [comment]
Thanks, that makes sense.

If I'm tokenizing my terms (say to lowercase them), and have `Store = true` on my analyzer, is there a way for either facets or the field dict to return the original term that was stored? The field dict probably has no idea what the stored values are, but could facets potentially have an option to return the stored value?

**Comment by mschoch** [comment]
The philosophy is that stored fields are not used for anything inside bleve
(except highlighting).  The only thing we do is store them, and return them
back to you.

Facets are built using the doc values (which are the indexed terms, not the
stored values)

marty
