### ISSUE TITLE
Question: locking

### ISSUE THREAD

**Issue by fi0** [blevesearch/bleve#1281]
When there're new data being written into the index, a read-only operation seems to be blocked.

What're the best practice on using bleve.Open while allowing read operations concurrently?

**Comment by mschoch** [comment]
We recommend you use the scorch index format (not the default, you must pass `scorch.Name` to the indexType and kvStore parameters of `NewUsing`.

In the scorch index, writes do not block reads.  Reads execute immediately on the data that is already indexed.

**Comment by fi0** [comment]
indexer side
```
mapping := bleve.NewIndexMapping()
index, err = bleve.NewUsing(dir, mapping, scorch.Name, scorch.Name, nil)
...
defer index.Close()
time.Sleep(10000 * time.Millisecond)
```

query side
```
runtimeConfig := map[string]interface{}{
		"read_only": true,
}
index, err := bleve.OpenUsing(dir, runtimeConfig)
```

On the query side, I can only get the results after the index is closed on the indexer side. How do I fix this? Thank you!

**Comment by mschoch** [comment]
The index can only be opened by one thing at a time.  Are you attempting to read and write from the index in separate processes?

**Comment by fi0** [comment]
Yes, I was using 2 processes incorrectly. 1 for indexing, and another for querying.
Thank you for the explanation!
