### ISSUE TITLE
"Access denied" removing .zap files on Windows

### ISSUE THREAD

**Issue by networkimprov** [blevesearch/bleve#1289]
On Windows 7, I see the following errors recurring:
```
2019/09/27 11:50:33 got err removing file: 000000000002.zap,
 err: remove store/svc/Blue/index.bleve\store\0000000002.zap: Access is denied.
2019/09/27 11:50:33 got err removing file: 000000000003.zap,
 err: remove store/svc/Blue/index.bleve\store\0000000003.zap: Access is denied.
```

This is due to a bug in the mmap package; details in https://github.com/blevesearch/bleve/issues/1289#issuecomment-536932932

I built with bleve 0.8.1 and Go 1.12.5.

**Comment by networkimprov** [comment]
For GOOS=windows, you cannot remove or rename opened files; that yields a "sharing violation" error. There is a plan to fix this, see https://github.com/golang/go/issues/32088.

I've patched syscall.Open() to lift that limitation (recommended by Microsoft). With the patch, you must rename before remove in order to reuse a filename immediately (i.e. before close). The error I'm seeing may be due to reusing the name.

Here is that patch. I set the flag true in a xyz_windows.go file. 
```
diff --git a/src/syscall/syscall_windows.go b/src/syscall/syscall_windows.go
index de05840..e1455d5 100644
--- a/src/syscall/syscall_windows.go
+++ b/src/syscall/syscall_windows.go
@@ -245,6 +245,8 @@ func makeInheritSa() *SecurityAttributes {
        return &sa
 }

+var Open_FileShareDelete = false
+
 func Open(path string, mode int, perm uint32) (fd Handle, err error) {
        if len(path) == 0 {
                return InvalidHandle, ERROR_FILE_NOT_FOUND
@@ -270,6 +272,9 @@ func Open(path string, mode int, perm uint32) (fd Handle, err error) {
                access |= FILE_APPEND_DATA
        }
        sharemode := uint32(FILE_SHARE_READ | FILE_SHARE_WRITE)
+       if Open_FileShareDelete {
+               sharemode |= FILE_SHARE_DELETE
+       }
        var sa *SecurityAttributes
        if mode&O_CLOEXEC == 0 {
                sa = makeInheritSa()
```

**Comment by mschoch** [comment]
The design of scorch is such that:

- zap segment files should never be renamed/moved
- zap file names should not be reused
- zap files should be closed before they are removed

That doesn't mean that isn't what is happening, but if that is happening, it should not be.

I also noted that in the original log you shared, the paths have a mix of `/` and `\` characters.  This is another possible source of the problem we should check.

**Comment by networkimprov** [comment]
I looked into mixing of `/` & `\` in pathnames; it's allowed by the Windows API. And it worked on the command line. Possible that Go is choking on it, I suppose...

**Comment by networkimprov** [comment]
In case it matters, my bleve folder is in a subdirectory of the app's working/current directory. I checked the properties for the .zap files; none of them show "read-only".

My app uses os.Remove() elsewhere without errors.

Possibly relevant Windows API docs
  https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-deletefilea

**Comment by networkimprov** [comment]
I'm hoping to get a release out this week, so any guidance you can offer on running this down would be great...

I tried looping the os.Remove() with 1s delays on failure in case the problem is transient; that didn't help.

I added some logging code around .zap files, here's results of 3 trials...

1: Files can be removed on command line:
```
C:\...>winbleve.exe
## open  winblevesub\t.index\store\000000000002.zap

C:\...>winbleve.exe
## open  winblevesub\t.index\store\000000000004.zap
## remove  winblevesub\t.index\store\000000000002.zap
2019/09/30 09:45:20 got err removing file: 000000000002.zap,
 err: remove winblevesub\t.index\store\000000000002.zap: Access is denied.

C:\...>del winblevesub\t.index\store\000000000004.zap
C:\...>del winblevesub\t.index\store\000000000002.zap
```
2: Early remove works
```
C:\...>winbleve.exe
## open  winblevesub\t.index\store\000000000002.zap

C:\...>winbleve.exe
## open  winblevesub\t.index\store\000000000004.zap
## remove  winblevesub\t.index\store\000000000002.zap
2019/09/30 09:49:08 got err removing file: 000000000002.zap,
 err: remove winblevesub\t.index\store\000000000002.zap: Access is denied.

C:\...>winbleve.exe
## remove  winblevesub\t.index\store\000000000002.zap
## open  winblevesub\t.index\store\000000000006.zap
## remove  winblevesub\t.index\store\000000000004.zap
2019/09/30 09:49:14 got err removing file: 000000000004.zap,
 err: remove winblevesub\t.index\store\000000000004.zap: Access is denied.

C:\...>winbleve.exe
## remove  winblevesub\t.index\store\000000000004.zap
## open  winblevesub\t.index\store\000000000008.zap
## remove  winblevesub\t.index\store\000000000006.zap
2019/09/30 09:49:34 got err removing file: 000000000006.zap,
 err: remove winblevesub\t.index\store\000000000006.zap: Access is denied.
```
3: Same starting point as (2), but different result
```
C:\...>winbleve.exe
## open  winblevesub\t.index\store\000000000002.zap

C:\...>winbleve.exe
## open  winblevesub\t.index\store\000000000004.zap

C:\...>winbleve.exe
## open  winblevesub\t.index\store\000000000006.zap
## remove  winblevesub\t.index\store\000000000002.zap
## remove  winblevesub\t.index\store\000000000004.zap
2019/09/30 10:03:25 got err removing file: 000000000004.zap,
 err: remove winblevesub\t.index\store\000000000004.zap: Access is denied.

C:\...>winbleve.exe
## remove  winblevesub\t.index\store\000000000004.zap
## open  winblevesub\t.index\store\000000000008.zap
## remove  winblevesub\t.index\store\000000000006.zap
2019/09/30 10:39:49 got err removing file: 000000000006.zap,
 err: remove winblevesub\t.index\store\000000000006.zap: Access is denied.
```

**Comment by networkimprov** [comment]
The problem is due to a bug in the mmap package, recently fixed here: https://github.com/edsrzf/mmap-go/commit/115d2333

I fixed my go.mod by doing:
`$ go get github.com/edsrzf/mmap-go@master`

Note that github.com/couchbase/vellum has a go.mod that should be updated.

This would have been easy to trace if Segment.DecRef() errors weren't ignored :-/

**Comment by tmm1** [comment]
@networkimprov thanks for tracking this down 🙏

**Comment by mschoch** [comment]
Sorry we didn't fully appreciate the impact of this earlier.  We now have the unit tests running on Windows which highlighted the need to address this.  We have switched to a fork of the mmap-go library, because the author seems to have not tagged a release containing that commit for over a year.  The latest released versions of bleve and zap all use this new fork, which has a release including the fix.

**Comment by networkimprov** [comment]
Was couchbase/vellum also updated?

**Comment by mschoch** [comment]
@networkimprov yes, here: https://github.com/couchbase/vellum/commit/4bff22cfb1863be33a3dcbb319b9e07aae629b16

That commit is part of the `v1.0.1` release as well.
