### ISSUE TITLE
Fuzzy search doesn't work when applying CharFilter

### ISSUE THREAD

**Issue by AlmogBaku** [blevesearch/bleve#1290]
I applied a custom CharFilter which replace multiple unicode characters with others.

Regular search(with the original value, or the equivalent after replacement) works as expected.
However, fuzzy search doesn't seem to work(when removing the CharFilter it works).

Is there an option to do fuzzy search on the original value?

**Comment by mschoch** [comment]
It doesn't seem likely there is a direct connection here, as the char filter just alters what is put into the index, and the fuzzy search does not search analyze terms, only attempts to match on what has already been put into the index.

Can you provide the following information so we can attempt to reproduce the issue:
- char filter transformation, which chars are you replacing with which other chars?
- source string (presumably containing a character to be replaced)
- search term, and fuzzy value you expect to match?

With this info it should be possible to create a unit test reproducing the issue.

**Comment by AlmogBaku** [comment]
1. I'm replacing (`l =>i`;`m => rn`): i.e "almog" =>  "airnog"
2. Then I'm trying to search for "allmog"
3. The iterator on `search_fuzzy.go:107` get a term `airnog` and calculate the Levenshtein Distance between it and `allmog` (which obviously exceed my limit)

**Comment by mschoch** [comment]
Thanks for clarifying.  The char filter alters the data put into the index.  The original term `almog` is not indexed.

Char filters are limited in what they can do, and this is only to modify the original byte stream prior to tokenization.  If you want the text indexed both with and without this transformation, it would have to be done in the token filter phase.  You would most likely need a custom token filter which can alter them as you want, and also index the original terms as well.

**Comment by AlmogBaku** [comment]
Thanks for the clarification! that worked.
However, I found out that the fuzzy search doesn't go through the CharFilter, is that expected?

**Comment by AlmogBaku** [comment]
this code exists in `query.MatchQuery.Searcher()`, but doesn't exist in the `query.FuzzyQuery.Searcher()`:

```go
	analyzerName := ""
	if q.Analyzer != "" {
		analyzerName = q.Analyzer
	} else {
		analyzerName = m.AnalyzerNameForPath(field)
	}
	analyzer := m.AnalyzerNamed(analyzerName)

	if analyzer == nil {
		return nil, fmt.Errorf("no analyzer named '%s' registered", q.Analyzer)
	}

	tokens := analyzer.Analyze([]byte(q.Match))
```

**Comment by AlmogBaku** [comment]
@mschoch ping?

**Comment by mschoch** [comment]
@AlmogBaku fuzzy query works this way by design.  We modeled this on how Elasticsearch offered the same functionality.  If you look at the Elasticsearch documentation, you'll see that fuzzy query is in the category called term-level queries:

https://www.elastic.co/guide/en/elasticsearch/reference/current/term-level-queries.html

This means that they do not perform analysis on the search terms.

Try using the MatchQuery (which will perform analysis) and set the fuzziness property on that query:

https://github.com/blevesearch/bleve/blob/master/search/query/match.go#L105
