### ISSUE TITLE
"got err removing file" on Windows

### ISSUE THREAD

**Issue by tmm1** [blevesearch/bleve#1296]
> got err removing file: 0000000003e6.zap, err: remove store\0000000003e6.zap: Access is denied.

https://github.com/blevesearch/bleve/blob/25d45a14eb3d1b42806ab32afe02703ecf0df935/index/scorch/persister.go#L904

I think this happens on Windows if the file is still open/in-use

**Comment by mschoch** [comment]
Likely same as this thread:

https://github.com/blevesearch/bleve/issues/1289
