### ISSUE TITLE
index.Batch cost large memory, how to reduce it

### ISSUE THREAD

**Issue by orange-jacky** [blevesearch/bleve#1304]
hi
    in my project, i do a compare  index.Index with index.Batch,i found that

 index  is bleve index instance
 method 1:
 ```
g := GlobalAirportInstance()
    slice := g.GetAllRec()
    for i := range slice {
	index.Index(slice[i].Id, &slice[i])
    }


```  
   cost detail：
    run  about 60 second, use 20MB memory

  method 2:
   ```
 batch := index.NewBatch()
	defer func() {
			batch.Reset()
		}()

	g := GlobalAirportInstance()
	slice := g.GetAllRec()
	for i := range slice {
	    batch.Index(slice[i].Id, &slice[i])
	}
```
   cost detail：
    run  about 100 millsecond, use 300MB memory

i need to batch method , hope run about 100 ms, and use about 60MB, how to do it and improve it.

thanks

**Comment by orange-jacky** [comment]
@avsej  how to improve score index use lots memory?

**Comment by will7200** [comment]
Try running a fixed number of Indexes per batch, like 100, keep repeating until you are done with list. Obviously 100 is arbitrary and it is something that you will have to test with depending on your data.  The reason it is so big (and fast) is because all those entries are being saved to the batch's internal data structure before writing to the index.

**Comment by orange-jacky** [comment]
@will7200 
thank you, it works, now it use about 2s and use memory about 50MB.

copy my code 
//
	index := b.index
	var err error
	batch := index.NewBatch()

	//分批次创建索引
	batchIndex := func(sli []GlobAirport) (err error) {
		batch.Reset()
		for i := range sli {
			batch.Index(sli[i].Id, &sli[i])
		}
		err = index.Batch(batch)
		return
	}
	g := GlobalAirportInstance()
	items := g.GetAllRec()
	batchSize := 200 //每次batch处理多少条数据

	start := time.Now()
loop:
	itemsLen := len(items)
	if batchSize <= itemsLen {
		batchIndex(items[:batchSize])
		items = items[batchSize:]
		goto loop
	} else {
		batchIndex(items[:itemsLen])
	}
	end := time.Now()
