### ISSUE TITLE
not find word  with a character "-"

### ISSUE THREAD

**Issue by beho1der** [blevesearch/bleve#1333]
I have a Russian word: "Сибиряков-Гвардейцев",  I find full text in bleve.NewMatchQuery("Сибиряков-Гвардейцев") and not find this word ,all words without "-", find successfully and if find: bleve.NewWildcardQuery("Сибиряков*"), this word find too.
I found a similar bug https://github.com/blevesearch/bleve/issues/103 , but the current commit is not relevant.

**Comment by mschoch** [comment]
The bug you linked to was related to parsing the `-` character, which has special meaning in QueryString query.

The first thing to check is how your text is being analyzed.  I checked this text using the Bleve analysis wizard here: http://analysis.blevesearch.com/analysis

Using either "standard" or the "ru" analyzer, the text is split into 2 separate tokens:

1	сибиряк	0	18
2	гвардейц	19	39

So when these analyzers are used, Bleve searches will not find the text containing those two words together, they can only be searched for independently.

The only way to change this behavior would be to configure an analyzer with a custom tokenizer that keeps the hyphenated word intact as a single token.

**Comment by beho1der** [comment]
Thanks, option with "keyword" work fo me!
