### ISSUE TITLE
Scorch index fails to function after the Close and Open index api calls

### ISSUE THREAD

**Issue by sreekanth-cb** [blevesearch/bleve#1352]
If we Close an existing scorch index and tries to open it again using Open api, the index stops functioning. 

As a part of the Close call, we perform a closing of the closeCh here - https://github.com/blevesearch/bleve/blob/master/index/scorch/scorch.go#L258

Today, during the open API call we don't reinitialise the closeCh and hence the scorch's introducer main loop will get exited here -https://github.com/blevesearch/bleve/blob/master/index/scorch/introducer.go#L62

**Comment by mschoch** [comment]
@sreekanth-cb I think this can be closed, please reopen if you think it isn't fixed.
