### ISSUE TITLE
go get error with bbolt

### ISSUE THREAD

**Issue by navono** [blevesearch/bleve#1360]
go get github.com/blevesearch/bleve

error:
```
go: github.com/blevesearch/bleve imports
        github.com/blevesearch/bleve/index/scorch imports
        github.com/etcd-io/bbolt: github.com/etcd-io/bbolt@v1.3.4: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/etcd-io/bbolt
```

Notice there's a [pr 1357](https://github.com/blevesearch/bleve/pull/1357) for this.

**Comment by mschoch** [comment]
Merged the PR, can you confirm that addresses the issue?

We have better modules support coming soon, so we'll be more plugged into these issues: https://github.com/blevesearch/bleve/issues/1350

**Comment by navono** [comment]
After get master branch, it works. Thanks for quick response.
