### ISSUE TITLE
makeslice: len out of range after moving index across hosts

### ISSUE THREAD

**Issue by bmhatfield** [blevesearch/bleve#1363]
Traceback here:

```
runtime error: makeslice: len out of range

panic(0x1cdeee0, 0x2135590)
        /usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:967 +0x166
github.com/blevesearch/bleve/index/scorch/segment/zap.(*SegmentBase).loadFieldDocValueReader(0xc0001aa000, 0xc0006eb740, 0x14, 0x792856, 0x798112, 0x0, 0x0, 0x0)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/docvalues.go:111 +0xf6
github.com/blevesearch/bleve/index/scorch/segment/zap.(*SegmentBase).loadDvReaders(0xc0001aa000, 0x0, 0x0)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/segment.go:561 +0x1e3
github.com/blevesearch/bleve/index/scorch/segment/zap.Open(0xc0008f9d00, 0x7c, 0x6b, 0x1ec4dd5, 0x1, 0xc00020a261)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/segment/zap/segment.go:80 +0x2a7
github.com/blevesearch/bleve/index/scorch.(*Scorch).loadSegment(0xc000b8b400, 0xc0004c81c0, 0x1, 0x1, 0xc0004c81c0)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/persister.go:740 +0xdb
github.com/blevesearch/bleve/index/scorch.(*Scorch).loadSnapshot(0xc000b8b400, 0xc0004c8140, 0x1, 0x1, 0xc0004c8140)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/persister.go:716 +0x1f4
github.com/blevesearch/bleve/index/scorch.(*Scorch).loadFromBolt.func1(0xc0001840e0, 0x0, 0xc0001840e0)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/persister.go:637 +0x1ea
github.com/etcd-io/bbolt.(*DB).View(0xc000165e00, 0xc000a891d8, 0x0, 0x0)
        /Users/bhatfield/go/pkg/mod/go.etcd.io/bbolt@v1.3.4/db.go:725 +0x8e
github.com/blevesearch/bleve/index/scorch.(*Scorch).loadFromBolt(0xc000b8b400, 0x75, 0x180)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/persister.go:614 +0x55
github.com/blevesearch/bleve/index/scorch.(*Scorch).openBolt(0xc000b8b400, 0x2b9c220, 0xc000b8b400)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/scorch.go:211 +0x57c
github.com/blevesearch/bleve/index/scorch.(*Scorch).Open(0xc000b8b400, 0x6, 0xc0000cc450)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index/scorch/scorch.go:160 +0x2f
github.com/blevesearch/bleve.openIndexUsing(0xc0002fe000, 0x65, 0xc000a89550, 0xc0000d4230, 0x0, 0x0)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index_impl.go:174 +0x516
github.com/blevesearch/bleve.OpenUsing(...)
        /Users/bhatfield/go/pkg/mod/github.com/blevesearch/bleve@v0.8.1/index.go:294
```

This is _probably_ a corrupt index as outlined in https://github.com/blevesearch/bleve/issues/1306, as I can reproduce this somewhat (80% of the time) reliably by tarring up the index with all its files and unpacking it elsewhere. It is more reliable if it just create the index locally and then read from it after closing.

Given the timing/order of operations (build, close, tar, move to another location), it appears that Bleve may still be mutating the index when I go to tar up it's files, even though I have already called `index.Close()` on it.

Short of stopping the process entirely, is there anything I can do to ensure that the index is in a consistent state after I call `index.Close()`?

**Comment by mschoch** [comment]
Once `Close()` has returned, none of the index files should be modified.

We did recently find a race condition in the `Close()` path, but our understanding had been that it only resulted in leaked file descriptors of files that were opened read-only.

If you are able to share a program and some steps that reproduce it, we are certainly interested in figuring out why this is happening.

**Comment by bmhatfield** [comment]
Thank you for the info! I just noticed that 0.8.2 is available, and I am 0.8.1 - I will update to pick up those changes and see if I can still reproduce.

**Comment by bmhatfield** [comment]
Alright, after much troubleshooting, I think I have a lead!

I now strongly think that the cause of the above trace is indeed a corrupted index, but I no longer believe the cause is Bleve.

After much troubleshooting, I believe there's something wrong with my code that is untaring a replacement index over an existing one (overwriting indexes is not a normal use-case for us; this is occurring due to my development process only).

BSD tar on my mac works fine; untar in Go results in corrupted files when overwriting them. I am not sure why, just yet, but I am able to reliably reproduce this path.

I'll close this! Thank you for your response, and apologies for wasting your time by being confused about the cause of this stacktrace!

**Comment by bmhatfield** [comment]
For anyone landing here after the fact, the difference/resolution in the code resulting in corrupted files when overwriting was:

```diff
- f, err := os.OpenFile(target, os.O_CREATE|os.O_RDWR, os.FileMode(header.Mode))
+ f, err := os.Create(target)
```

(I then later set the file mode from the header in call to `f.Chmod`)
