### ISSUE TITLE
Tracking persisted documents

### ISSUE THREAD

**Issue by connorgorman** [blevesearch/bleve#1374]
Effectively, I want to be able to track the documents that have been successfully persisted to the index. The use case is that I can't rebuild the index every time on startup, but would like to be able to use unsafe batch for performance reasons as I index lots of documents individually so they can be immediately searchable and thus become expensive when merging.

Is there any way to get the IDs persisted from bleve or should I write my own logic within a PersistedCallback and always use Batch?

Thanks in advance!

**Comment by mschoch** [comment]
If I understand you correctly, then PersistedCallback was added to do exactly that.  It is the only way to know when a batch was actually persisted when using unsafe batches.  In scorch today, indexing a single document or a batch with only one document is going to perform the same.  Internally, that is how it is implemented: https://github.com/blevesearch/bleve/blob/master/index/scorch/scorch.go#L296-L300

**Comment by connorgorman** [comment]
Awesome, thanks! Just wanted to make sure that my understanding was correct
