### ISSUE TITLE
IndexBuilder producing larger indexes

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1397]
I just gave it a try on an index with 4 million documents and a batch size of 10k. Compared to my old approach of indexing batches, the new builder:
* Took 60% longer (which seems to be due the additional latency of merging segments during the call to `Close()`).
* Creates an index that takes 4x more disk space. A compressed tarball of the index is about 20% bigger.

Is that the expected result?

_Originally posted by @tylerkovacs in https://github.com/blevesearch/bleve/pull/1282#issuecomment-628271514_

**Comment by mschoch** [comment]
See also: https://github.com/blevesearch/bleve/pull/1282#issuecomment-628381814

**Comment by mschoch** [comment]
At least part of the problem is in zap v12 and not the IndexBuilder.  I've confirmed larger indexes with all other parameters the same:

```
798M	bleve-scorch-default.bleve
930M	bleve-scorch-zapv12.bleve
```

**Comment by mschoch** [comment]
Actually, perhaps not, seems like for some reason my `zapv12` run did not actually use zap v12:

```
$ zap footer bleve-scorch-zapv12.bleve/store/0000000000a6.zap 
Length: 149146170
CRC: 0x82399566
Version: 11
Chunk Factor: 1024
Fields Idx: 149146102 (0x8e3c9f6)
Stored Idx: 99590 (0x18506)
DocValue Idx: 149146040 (0x8e3c9b8)
Num Docs: 12300
```

**Comment by sreekanth-cb** [comment]
thats good.. I was checking the zap12 code.

**Comment by mschoch** [comment]
The first problem is a bug in the config parsing when using JSON files.  I now have it actually using zap v12 and the index is even larger:

```
1.6G	bleve-scorch-zapv12-e.bleve
```

That's actually helpful, as it's so much larger it's clearly signal and not noise.

**Comment by sreekanth-cb** [comment]
I tried to index ~531K documents and created a single partitioned fts index and a single partitioned, single segment index. (tighter merge policy) with numSnapshotsToKeep as 1. 
The documents were generated from the cbworkloadgen tool having 3 text fields and 1 numeric field and those were loaded to the existing travel-sample.
Tried the mappings with and without term vectors enabled and in both cases single segment index is equal or smaller. 
Without term vectors, index size were roughly same.
With term vectors, 
usual index size -~286MB
single segment index size - 278MB

The sizes aren't much different here mostly due to the unique terms generated by the tool. All of them would have got into a 1 hit optimisation except the travel-sample's 31K doc.

But even this data set used to create size bloating of 2X before, when I was testing the forceMerge api 5 months back.

```Length: 195819053
CRC: 0x6469c59
Version: 12
Chunk Mode: 1025
Fields Idx: 195818961 (0xbabf5d1)
Stored Idx: 7372488 (0x707ec8)
DocValue Idx: 195818836 (0xbabf554)
Num Docs: 531591
```
@mschoch , just wanted to be sure that the new format is getting into effect in your trials..

**Comment by mschoch** [comment]
Thanks @sreekanth-cb I think we should ignore the single-segment issue for the moment, as in my testing it is unrelated to the problem.  In all of my tests, v12 produces a larger index than v11.  Do you have a repeatable test that shows otherwise?  Is there anyway we can use the same documents in a pure bleve test (and hopefully reduce the size as well so we can actually look at the files produced)?

**Comment by sreekanth-cb** [comment]
Yes @mschoch , it is consistently reproducible.
With v11/existing zap version produces a multi segment index of 790MB vs 286MB in v12
and a single segment of 2.37GB vs 278MB in v12.

**Comment by sreekanth-cb** [comment]
@mschoch , with term vectors off, a single segment index created 199.2MB file in v11 and 476MB in V12. So the root cause if confirmed. 

Lets go for v13 then? :)

**Comment by mschoch** [comment]
@tylerkovacs an update, we have found that there was an unexpected interaction between two different optimizations included in zap v12.  In particular, if you have fields in your mapping with term vectors disabled, low cardinality terms will take more space to encode.  We are working on a solution to this, can you confirm that in your case you have term vectors disabled for some fields?

**Comment by tylerkovacs** [comment]
@mschoch Yes, I have term vectors disabled for most fields. Sounds like found the problem!

**Comment by mschoch** [comment]
zap v13 up for review: https://github.com/blevesearch/zap/pull/15

**Comment by sreekanth-cb** [comment]
Index size came down to 209.5MB from 472MB for 531K documents without term vectors with v13.

**Comment by mschoch** [comment]
@sreekanth-cb was that single segment? and is are these runs identiical?  Because you previously quoted, "a single segment index created 199.2MB file in v11", suggesting v13 is somehow still larger or at least no better than v11?

**Comment by tylerkovacs** [comment]
I just tried the recently merged v13 and I'm still getting significantly larger index sizes using `IndexBuilder`.

Some observations:
* Right before the call to `Close()`, my index is 28GB.
* After `Close()` completes and everything is merged into a single segment, the index is 61GB.

For comparison, without `IndexBuilder`:
* v12 index size is 15.6GB
* v13 index size is 14.9GB

**Comment by mschoch** [comment]
Hmmn, can you share your mapping?  I'm out of ideas.

**Comment by mschoch** [comment]
So, one other thing I can think of.  When we introduced dynamic chunk factor in `zapv12` we only used it to change the chunk factor for extremely low cardinality field terms (<1024) to be a single chunk, otherwise, we still have (numdocs/1024) chunks.  See: https://github.com/blevesearch/zap/blob/master/chunk.go#L29-L54

So, if your dataset has many field/terms with cardinality >1025 (but still low relative to total number of docs in the entire dataset), then considerable space will still be wasted (and it is magnified in single segment indexes).

Question:  Can you provide your max docs, and some sense of how the data is distributed?  Do field/terms with the cardinality described above seem likely to match your use case?

Proposal:  Another new zap format, one that expands on current solution, but dynamically scales the the chunk size.  High cardinality fields still use something close to 1024 docs/chunk, lowest cardinality fields use single chunk, everything else is scaled evenly in between.

**Comment by tylerkovacs** [comment]
Here's is my mapping:

```
// First, define a few helpers to create field mappings.
func newFacetFieldMapping() *mapping.FieldMapping {
	m := bleve.NewTextFieldMapping()
	m.Store = false
	m.IncludeTermVectors = false
	m.Analyzer = whitespacePlaceholderAnalyzerName
	m.IncludeInAll = false
	return m
}

func newNumericFieldMapping() *mapping.FieldMapping {
	m := bleve.NewNumericFieldMapping()
	m.Store = true
	m.IncludeTermVectors = false
	m.IncludeInAll = false
	return m
}

func newBooleanFieldMapping() *mapping.FieldMapping {
	m := bleve.NewBooleanFieldMapping()
	m.Store = false
	m.IncludeInAll = false
	return m
}

func newGeoFieldMapping() *mapping.FieldMapping {
	m := bleve.NewGeoPointFieldMapping()
	m.Store = true
	m.IncludeTermVectors = false
	m.IncludeInAll = false
	return m
}

func _newTextFieldMapping() *mapping.FieldMapping {
	m := bleve.NewTextFieldMapping()
	m.Store = false
	m.IncludeTermVectors = false
	m.IncludeInAll = false
	return m
}

func newTextFieldMappingWithSimpleAnalyzer() *mapping.FieldMapping {
	m := _newTextFieldMapping()
	m.Analyzer = simple.Name
	return m
}

func newTextFieldMappingWithStemmingAnalyzer() *mapping.FieldMapping {
	m := _newTextFieldMapping()
	m.Analyzer = stemmerAnalyzerName
	return m
}

// Now define all the field mappings used in the DocumentMapping
facetFieldMapping := newFacetFieldMapping()
numericFieldMapping := newNumericFieldMapping()
booleanFieldMapping := newBooleanFieldMapping()
geoMapping := newGeoFieldMapping()
merchantNameFieldMapping := newTextFieldMappingWithSimpleAnalyzer()
stemmerFieldMapping := newTextFieldMappingWithStemmingAnalyzer()
```

The `DocumentMapping` consists of 62 field mappings with the following distribution:
* 43 facetFieldMapping
* 14 numericFieldMapping
* 2 stemmerFieldMappings
* 2 booleanFieldMappings
* 1 geoMapping
* 1 merchantNameFieldMapping

My `IndexMapping` has only this single `DocumentMapping`.

I'll send cardinality estimates shortly.

**Comment by tylerkovacs** [comment]
I'm currently indexing 4 million documents but using `MultiSearch` to shard them across 8 separate indexes, each index contains about 500k documents.

Cardinality estimates for each field mapping are below. I have left out the text and geo field mappings under the assumption that they aren't relevant, though please let me know if this assumption is wrong. Each text field contains between 2-5000 words.

Format is:
* Field name (for my own reference): Cardinality

* AlexaRankFieldName: very high, each value is unique
* AppIdentifiersFieldName: 1,484 distinct values
  * note: this field is a slice of strings, in case that matters, and there are 1484 distinct strings that can appear in each slice.
* AppInstallCountFieldName: 613 distinct values
* AverageProductPriceFieldName: very high, each value is unique
* CategoriesFieldName: 399 values
* Category1FieldName: 35 values
* Category2FieldName: 187 values
* Category3FieldName: 177 values
* CombinedFollowerCountFieldName: very high, almost all values are unique
* CountryCodeFieldName: 251 values
* CreatedAtYYYYMMFieldName: 42 values
* CreatedAtYYYYMMDDNoCutoffFieldName: 730 values 
* CreatedAtYYYYMMDDFieldName: 177 values
* CreatedAtYYYYQFieldName: 15 values
* CurrencyCodeFieldName: 158 values
* DatabaseCreatedAtYYYYMMFieldName: 516 values
* DatabaseCreatedAtFieldName: 638,047 values
* DomainFeaturesFieldName: 7 values
* DomainPlanFieldName: 6 values
* DomainProviderFieldName: 14 values
* DomainLastProviderFieldName: 24 values
* DomainLastProviderChangeAtFieldName: 22,413 values
* DomainStateFieldName: 3 values
* EmployeeCountFieldName: 4,565 values
* EmployeeCountBucketFieldName: 8 values
* EstimatedRevenueFieldName: 67,760 values
* IdentifierTypesFieldName: 9 values
* IsProviderDomainFieldName: 2 values
* LanguageFieldName: 209 values
* ListIDsFieldName: 250 values
* LocationCityFieldName: 25,523 values 
* LocationStateFieldName: 1,998 values
* MagentoMajorVersionFieldName: 2 values
* MagentoVersionFieldName: 77 values
* MonthlyAppSpendFieldName: 4,750 values
* PhoneCountryCodeFieldName: 207 values
* PlatformRankFieldNameL very high, all values unique
* ProductCountFieldName: very high, almost all values unique
* ProductCountBucketFieldName: 12 values
* RankFieldName: very high, all values unique
* RegionFieldName: 6 values
* SubRegionFieldName: 23 values
* TechnologiesFieldName: 131 values
* TLDFieldName: 1,744 values
* ThemeCostFieldName: 5 values
* ThemeVersionFieldName: 434 values
* ThemeNameFieldName: 115,414 values
* ThemeVendorNameFieldName: 31 values
* ThemeStyleFieldName: 184 values
* UsesGmailFieldName: 2 values
* VendorCountFieldName: 3,133 values

**Comment by tylerkovacs** [comment]
> So, if your dataset has many field/terms with cardinality >1025 (but still low relative to total number of docs in the entire dataset), then considerable space will still be wasted (and it is magnified in single segment indexes).

I have 6 fields with cardinality in the 1,025 - 50k range. Sounds like those would be the ones that would cause considerable space wastage under zap v13.

**Comment by tylerkovacs** [comment]
I should also mention that I have some dynamic fields that are not part of the `DocumentMapping`. These are fields with very sparse data and there are a few thousand distinct fields that are only present in a handful of documents (ranging from a few dozen to a few thousand documents)

**Comment by tylerkovacs** [comment]
If I remove the dynamic fields and the 7 fields in the 1,025-70k cardinality range, I get the following index sizes using zap v13

* Using regular batch indexes: 9.9GB (down from 14.9GB with all fields)
* Using `IndexBuilder`: 36GB (down from 61GB with all fields)
  * Note: index size was 18GB when `Close()` started so it still doubled the size of the index.

**Comment by mschoch** [comment]
In that case I don't know what to suggest.  There are no other known reasons why a single segment representation should be larger than multiple segments for the same data.  For now, you should simply not use the IndexBuilder.

What operating system are you using, what filesystem are you using, and how are you measuring these values?  The fact that you always see a doubling seems suspicious to me.  Obvious, in the sense that the merging will in many cases double the data size in the temp directory, but we then move the final segment out to a different path.  We expect that the space utilization of that final single segment should be better, and have theories about why it might not be in some cases, but seeing it as 2x is very surprising.

**Comment by tylerkovacs** [comment]
I'm running Ubuntu, kernel version 4.15.0-101-generic with ext4 filesystem and using `du -sh` to measure index size.

Yes, I'll simply not run IndexBuilder for now. I'll try to find the time to see if I can narrow down the problem to individual fields and maybe a pattern will emerge.

Thanks for your help here and for Bleve itself. It is terrific.

**Comment by sreekanth-cb** [comment]
@tylerkovacs ,

> While Close() is running, it balloons to 70GB before shrinking to 58GB when it completes. So index size is more than doubling as a result of the call to Close().

Just to get the sense of the issue now, With v11/default zap format your index size out of builder was 58GB and with v13 it again amplified to 61GB now?

If so, this is surprising given that the term vector disabling alone should have shown some improvements as that wasn't optimised in earlier v11/default version.

@mschoch , perhaps this is just a perfect example which exposes the fundamental problem with the chunking logic we have today. For example, this will always create size bloating issue, if a given term of cardinality of a few thousands in a corpus of a few millions, with a sparse occurrence of once in every 1024 documents.

Feels like the current chunking logic will always fail for one use case or another.

**Comment by mschoch** [comment]
@sreekanth-cb first, we have still not implemented proper dynamic chunking where we actually choose the correct value for any cardinatlity, so it would be premature to say we've already proven some fundamental problem.

Second, I actually am coming to a different conclusion.  Chunking was never the serious problem that you led me to believe.  At one point you had persuaded me that because of chunking we wrote out numerous completely empty chunks, but as I've reviewed the code closer, that simply isn't the case.  Here are the facts as I understand them now:

1.  Previously we always wrote at least one chunk, even if no items were recorded (this has been addressed)
2.  For every chunk that is needed (at least one doc num in that chunk has some information to record), we record a chunk (which has some overhead associated with it).  We sometimes still choose a less-than-optimal number of chunks to achieve the purpose of chunking in the first place (a bound on the time required to seek to an arbitrary place in long list of things)

So, item 1 has been addressed, and I have a proposal for item 2, which I might as well just code up now so we can end this part of the debate.

@sreekanth-cb if you have another proposal, let's try it.  Only Couchbase has sufficient performance testing to know how query latency/throughput is affected by these changes.

**Comment by sreekanth-cb** [comment]
> Second, I actually am coming to a different conclusion. Chunking was never the serious problem that you led me to believe. At one point you had persuaded me that because of chunking we wrote out numerous completely empty chunks, but as I've reviewed the code closer, that simply isn't the case. Here are the facts as I understand them now:

I never had an empty chunks theory. My points were 

1. Due to low cardinality terms there will be lots of sparsely populated or empty chunks..which will result in lots of empty chunk metadata slice. for eg: if the term's occurrence was on the max docID in a segment.  And I think - this is what happens here in those 7 fields of moderate cardinality in this use case.

2. Second is - when the term vectors are disabled, a lot of empty chunk lens of (zero) will get written to the disk  as a part of the meta data. Won't be a bigger contributor to sizing though, this was un necessary.

https://github.com/blevesearch/bleve/blob/mad-hatter-release/index/scorch/segment/zap/merge.go#L197

https://github.com/blevesearch/bleve/blob/mad-hatter-release/index/scorch/segment/zap/intcoder.go#L115

Both the issues are sort of on chunk metadata, as without data in a chunk its the meta data which takes the space IIRC.

And these findings - had proven with sample data sets from cbworkloadgen. 
Chunking problems and the fixes I perceived are verifiable in a toy build.

I  believe chunking is the root of problem here.. , lets see..
My new chunking proposal is shared over an email..

**Comment by mschoch** [comment]
My proposal for a v14 (chunk mode 1026) is here:

https://play.golang.org/p/yJKBnakKmJu

The improvement would be for what I call the "low-med" case.  In v12/v13 we have lots of really sparse chunks: `num_chunks_needed: 3906 docs/chunk: 1`.  In my proposed v14 we improve that significanlty to: `num_chunks_needed: 4 docs/chunk: 1000`

**Comment by mschoch** [comment]
@tylerkovacs we released bleve v1.0.9, this includes zap v14 and a very important bug fix related to using custom zap version with the Builder.

Here are the sizes of 1M wiki docs, when using zap v11-v14 with the Builder:

```
9083488	bleve-builder-scorch-zapv11-mil.bleve
3127756	bleve-builder-scorch-zapv12-mil.bleve
3100816	bleve-builder-scorch-zapv13-mil.bleve
3056260	bleve-builder-scorch-zapv14-mil.bleve
```

We believe v12 and v13 do include important improvements, this dataset/mapping just hides them due to many features being disabled.

If you could try again with bleve v1.0.9, and configure the builder to use zap v14, hopefully we finally see some improvement.

**Comment by tylerkovacs** [comment]
Success! With [latest master](https://github.com/blevesearch/bleve/commit/2b80a2aedf6bb1746054c6771d0625866a0dcabe) and zap v14 my index size is:
* 14.2GB with `IndexBuilder`
* 15.0GB without `IndexBuilder`

:+1:

**Comment by mschoch** [comment]
Closing this for now, re-open or file a new issue if anything comes up.
