### ISSUE TITLE
How to convert field.Value () to float64?

### ISSUE THREAD

**Issue by Breezess** [blevesearch/bleve#1409]
doc, err := index.Document("a")

A float64 field  Stored in doc, how do I get it?

How to use [] byte to float64?

**Comment by mschoch** [comment]
If it was indexed as a NumericField you can call `Number()` instead of `Value()` to get the float value.  Or if you want to do it yourself, look at the code inside the Number function.

https://github.com/blevesearch/bleve/blob/master/document/field_numeric.go#L99-L109

**Comment by Breezess** [comment]
Can you provide some more examples?
For example: I want to query the range of float64 in the field

I want query  abc < 100.1529496 

This document is not very clear

**Comment by Breezess** [comment]
bleve.NewNumericRangeQuery  

i want Set a field query.
How should this be done?

**Comment by mschoch** [comment]
OK, my previous answer was a bit confusing.  Here is an example:

```
package main

import (
	"fmt"
	"github.com/blugelabs/bleve"
	"log"
)

func main() {
	// default mapping
	m := bleve.NewIndexMapping()

	// open index using scorch
	idx, err := bleve.NewUsing("test-numeric.bleve", m, "scorch", "scorch", nil)
	if err != nil {
		log.Fatal(err)
	}
	defer idx.Close()

	// index 3 documents
	err = idx.Index("1", map[string]interface{}{
		"abc": 450.6,
	})
	if err != nil {
		log.Fatal(err)
	}
	err = idx.Index("2", map[string]interface{}{
		"abc": 99.9,
	})
	if err != nil {
		log.Fatal(err)
	}
	err = idx.Index("3", map[string]interface{}{
		"abc": 1000.05,
	})
	if err != nil {
		log.Fatal(err)
	}

	// search for documents with abc < 100.1529496
	max := 100.1529496
	q := bleve.NewNumericRangeQuery(nil, &max)
	q.SetField("abc") // scope search to the abc field
	req := bleve.NewSearchRequest(q)
	req.Fields = []string{"abc"} // request stored value be loaded for abc field
	res, err := idx.Search(req)
	if err != nil {
		log.Fatal(err)
	}

	// print results (this prints the float value 99.9)
	//fmt.Println(res)

	// but, let's access it directly
	for _, hit := range res.Hits {
		if abcField, ok := hit.Fields["abc"]; ok {
				if abcFloat, ok := abcField.(float64); ok {
					// now you have the number back as a float
					fmt.Printf("id: %s, abc float: %f\n", hit.ID, abcFloat)
				}
		}
	}
}
```
If that's not what you're trying to do, can you share some of your code?

**Comment by Breezess** [comment]
@mschoch Thank you for your answer! !
bleve is great!
I am a novice and I have not used other projects of the same type.
I read through the bleve documentation and test file writing are simple ways.
Most examples are not complete and lack practice.
