### ISSUE TITLE
Possible mishandling of errors

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1442]
Because of the condition `err != nil`, the `err` variable is never assigned to.

https://github.com/blevesearch/bleve/blob/master/index/scorch/snapshot_index.go#L306

I believe the intention was to record the first error (`err == nil`).

I'm assuming we don't break out of the loop so that all the data is read from the channel.

@abhinavdangeti @sreekanth-cb thoughts?

**Comment by abhinavdangeti** [comment]
Looks like we're handling the err incorrectly, yes I agree. If the intention were to record the first error, then I'd change the conditional. I'd also avoid unnecessarily setting an entry into a map that we're going to throw away in case of any error.

```
...
if asr.err != nil {
    if err == nil {
        err = asr.err
    }
} else if err == nil {
    rv.iterators[asr.index] = asr.docs.Iterator()
}
...
```

**Comment by mschoch** [comment]
Yeah, I thought about breaking out of the loop, but presumably we want to drain that channel.  But you're right, we can still avoid the additional work with the result.
