### ISSUE TITLE
another mishandled error?

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#1444]
Here we attempt to close a resource, storing the error in `cerr`, and if it's not nil, we assign it back to `err`.  But then we never check `err` before eventually overwriting it again.

https://github.com/blevesearch/bleve/blob/master/search/searcher/search_numeric_range.go#L77-L79

It's not exactly clear to me what we were trying to do here.  Possibly once upon a time this was deferred, but as written here it seems like we can use use `err` directly, and if we got an error closing, we should return that error.

@abhinavdangeti @sreekanth-cb thoughts?

**Comment by abhinavdangeti** [comment]
Good spot, think we should just return err in case fd.Close() fails.
Also, I'm not sure I understand what you imply could've been deferred in the past?

**Comment by mschoch** [comment]
@abhinavdangeti oh, just because it was named `cerr` it sort of implied that one of our static checking tools warned us about shadowing the `err` variable, which usually comes up when you're in some sort of closure.  Often times when that error is related to closing we use the name `cerr` instead of something like `err2`.  I did not look at the history to see...

**Comment by abhinavdangeti** [comment]
Ah right. It seems to have been introduced by this here commit: https://github.com/blevesearch/bleve/commit/7e5b7c200faf569915e2417393916bc36126a6e7

**Comment by mschoch** [comment]
@abhinavdangeti @sreekanth-cb I suspect there is some shared history with this code:

https://github.com/blevesearch/bleve/blob/master/search/searcher/search_geoboundingbox.go#L137-L146

Note it is very similar, but this version IS inside a defer as I suspected...

**Comment by mschoch** [comment]
And in that version, the `cerr=err` is effective, as `err` is a named return variable...

**Comment by abhinavdangeti** [comment]
Right, makes sense in the geoboundingbox code as err is actually returned. Thanks for pointing it out.
