### ISSUE TITLE
Facets filters

### ISSUE THREAD

**Issue by teamon** [blevesearch/bleve#1469]
Hi,

Given documents like:

```
id=1 color=red   size=s
id=2 color=red   size=m
id=3 color=blue  size=s
id=4 color=blue  size=s
id=5 color=green size=m
```

The resulting facets are:

```
color:
  red (2)
  blue (2)
  green (1)
size:
  s (3)
  m (2)
```

Now, when adding term filter to the query like `color=red` the resulting facets are

```
color:
  red (2)
size:
  s (1)
  m (1)
```

Is there a way to make facets counters exclude the term for each facet, so that the above query would result in:

```
color: # color facet ignores color value
  red (2)
  blue (2)
  green (1)
size: # size facet uses color filter
  s (1)
  m (1)
```

and when searching for `color=red`, `size=s` the facets results would be:

```
color: # color facet uses size filter
  red (1)
  blue (2)
size: # size facet uses color filter
  s (1)
  m (1)
```

?

**Comment by mschoch** [comment]
I don't see how we could do this.  The way facets work is they actually count documents that are seen.  In the example where you search with a term query color=red, we do not see any blue or green shirts, so we could no compute those counts.

**Comment by teamon** [comment]
What I'm looking forward is something like https://madewithlove.com/faceted-search-using-elasticsearch/ , especially the last part:

```
{
   "query": {
       "and": [
           {
               "terms": {"country": ["be", "fr"]}             
           },
           {
               "terms": {"category": ["books", "movies"]}
           }
       ]
   },
   "aggregations": {
      "all_products": {
         "global": {},
         "aggregations": {
            "countries": {
               "filter": {
                  "and": [
                     {
                        "terms": {"category": ["books","movies"]}
                     }
                  ]
               },
               "aggregations": {
                  "filtered_countries": {
                     "terms": {"field": "country"}
                  }
               }
            },
            "categories": {
               "filter": {
                  "and": [
                     {
                        "terms": {"country": ["be","fr"]}
                     }
                  ]
               },
               "aggregations": {
                  "filtered_categories": {
                     "terms": {"field": "category"}
                  }
               }
            }
         }
      }
   }
}
```

where each facet aggregation gets own set of filters.

I guess the only way to do this with bleve, would be to perform N searches, one for each facet with different query filters, right?

**Comment by mschoch** [comment]
Correct, you would have to run searches with all the alternate combinations of filters/facets you want to see.
