### ISSUE TITLE
Choose analyzer dynamically based on field name?

### ISSUE THREAD

**Issue by Nic0S** [blevesearch/bleve#1471]
Hello, apologies if this is already possible or a dupe issue!

I have a possible use case where the fields in a document would be dynamic, but the keys would reveal the type of analyzer to use. For example, a field in the doc with key "my_field_text_en" would use a standard English analyzer, "my_field_text_es" a standard Spanish analyzer, "my_field_token" a token analyzer etc.

I took a quick look at the code, and it _seems_ like this could be added to mapping/index.go::AnalyzerNameForPath, using a map from regex (or even just suffix) to its corresponding analyzer. Does that seem right?

If this seems doable, I'm wondering if it's hypothetically something that would get merged if I submitted a PR? We're considering a couple indexers and I think this feature would be huge for us.

**Comment by Nic0S** [comment]
I thought a little bit more about this, it seems like this could actually be accomplished by using sub-document mappings right? Instead of 

```
{
  "my_field_text_en": "value"
}
```

You could have
```
{
  "text_en": {
    "my_field": "value"
  }
}
```

Where all subfields of "text_en" can be analyzed the same way..

**Comment by mschoch** [comment]
@Nic0S yes, if you have control of the source documents, then you could arrange them as you described, and then use Bleve's ability to set different default analyzers for the different sub-documents.

Another option is to take full control of the document mapping yourself.  This has become an increasingly popular option, as changes to the way mapping work have backwards compatibility issues, and yet often times the functionality isn't what users want.  The basic idea is that you can build your own bleve *document.Document and then pass it to the IndexAdvanced() method on a batch.  Using this approach, you can use whatever ever analyzer you want for any field you want.

**Comment by Nic0S** [comment]
Oh nice, I wasn't aware of the IndexAdvanced method. Pretty powerful to be able to choose indexers on the fly.

Sounds like our use case is really well covered here already, thanks for the advice!
