### ISSUE TITLE
Documentation says simple analyzer uses unicode tokenizer

### ISSUE THREAD

**Issue by nkovacs** [blevesearch/bleve#1486]
[According to the documentation](http://blevesearch.com/docs/Analyzers/), the simple analyzer uses the unicode tokenizer. It doesn't. [It uses the letter tokenizer](https://github.com/blevesearch/bleve/blob/master/analysis/analyzer/simple/simple.go#L27).

**Comment by mschoch** [comment]
@nkovacs proposed fix: https://github.com/blevesearch/blevesearch.github.io-hugo/pull/23

**Comment by mschoch** [comment]
The fix has been merged.

**Comment by nkovacs** [comment]
Thank you!
