### ISSUE TITLE
Using wrong unicode normalisation form

### ISSUE THREAD

**Issue by rboulton** [blevesearch/bleve#149]
At https://github.com/blevesearch/bleve/blob/master/analysis/token_filters/unicode_normalize/unicode_normalize.go#L31
the code reads

```
NFKD: norm.NFKC,
```

It should probably say NFKD on the right hand side.

**Comment by mschoch** [comment]
Yep thats definitely a bug.  Unfortunately, the tests must have been wrong as well, because now they fail.  I have to re-remember what is going on here to make sure the tests are correct.
