### ISSUE TITLE
Improve analysis of Arabic text

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#150]
Meta-issue to track progress, will close when we're satisfied with the behavior of the Arabic adapter.

Current next steps:

- #28 (blocker)
- Implement Arabic analyzer using the following
    - unicode tokenization
    - lowercase filter
    - arabic stop word filter
    - arabic normalization filter
    - arabic stemmer (see #28)
- Compare results of some ad-hoc some inputs with Lucene
- Identify larger corpus of Arabic text for analysis (possibly wikipedia)

**Comment by saljam** [comment]
I can start playing with a more sophisticated arabic stemmer and try to evaluate it against wikipedia or some other corpus. I've a bunch of modern and premodern texts—I suspect they're all in the public domain, but I'll double check the copyright situation.

**Comment by mschoch** [comment]
Sounds good, I have the analyzer working.  But one of the test cases is failing.  I think its a bug in the normalizer, but I may go ahead and push it and have you help me figure out where the problem is.

**Comment by saljam** [comment]
Another TODO for me: normalise characters in the Presentation Form blocks to their respective characters in the standard Arabic block. (see http://en.wikipedia.org/wiki/Arabic_Presentation_Forms-B)

I'm not sure the lower case filter is necessary, there's no case in arabic.

**Comment by saljam** [comment]
Sounds good, I'll have a look.

**Comment by mschoch** [comment]
The components used in the analyzer came from the lucene defintion here:

https://github.com/apache/lucene-solr/blob/trunk/lucene/analysis/common/src/java/org/apache/lucene/analysis/ar/ArabicAnalyzer.java#L133-L142

For some languages I think they keep the lower-case filter, in case there are English or other languages that are sometimes mixed in with the language itself.  I don't know if this is common or rare with Arabic text.

**Comment by saljam** [comment]
Yeah I guessed, it's actually quite common.

**Comment by mschoch** [comment]
The failing test is here:

https://github.com/blevesearch/bleve/blob/master/analysis/language/ar/analyzer_ar_test.go#L73-L83

Initially I thought it was the normalization of the 'AlefHamzaAbove', but now I think that might be transformed correctly, instead it might be stemming at the other end.

**Comment by saljam** [comment]
Yes, good catch!

The Lucene stemmer strips multiple suffixes, while the one I added only strips one. Fix incoming.

**Comment by mschoch** [comment]
I've redeployed the analysis wizard with the Arabic analyzer now available.  You can play with it here:

http://analysis.blevesearch.com/

**Comment by mschoch** [comment]
Closing this for now as we got the basics working.  Can move future work to new issues.
