### ISSUE TITLE
NewSearchRequest only returns 10 results

### ISSUE THREAD

**Issue by suntong** [blevesearch/bleve#1545]
Hi

I found that `bleve.NewSearchRequest()` only returns 10 search results. 

Is it really so? thx

**Comment by mschoch** [comment]
It returns the top 10 results by default.  If you would like a different number returned you can use:

```
func NewSearchRequestOptions(q query.Query, size, from int, explain bool) *SearchRequest
```

Pass a number other than 10 as the `size` argument.

**Comment by suntong** [comment]
Oh, thanks for the confirmation and quick reply!
