### ISSUE TITLE
bleve.SearchResult return 0 as total sometimes although results are returned

### ISSUE THREAD

**Issue by svera** [blevesearch/bleve#1547]
With bleve 2.0.1 and 1.0.14 versions, doing the following search returns 0 sometimes in the `Total` field of `searchResults`

```
query := bleve.NewMatchQuery(keywords)
searchOptions := bleve.NewSearchRequestOptions(query, resultsPerPage, (page-1)*resultsPerPage, false)
searchOptions.Fields = []string{"Title", "Author", "Description"}
searchResults, err := index.Search(searchOptions)
if err != nil {
	return nil, err
}
```

**Comment by mschoch** [comment]
It would be helpful if you could provide additional information.  Do you have an index you can share where there is happens?

I have reviewed the code, and the way the total is calculated, its hard to see how this can happen.  By any chance are you using index aliases or does this happen directly searching an index?

**Comment by mschoch** [comment]
Additional questions:

1. Was the code known to work correctly on some previous version of Bleve?
2. Can you expand on what you mean by "sometimes"?

**Comment by svera** [comment]
Hi @mschoch , thank you for the promptly response!
I've found out that this is related with the fact that I'm trying to index documents in different languages. So, this is the code that indexes the documents

```
func CreateBleve(dir string) (*BleveIndexer, error) {
	indexMapping := bleve.NewIndexMapping()
	addLanguageMappings(indexMapping, []string{es.AnalyzerName, en.AnalyzerName, fr.AnalyzerName, de.AnalyzerName, it.AnalyzerName, pt.AnalyzerName})
	index, err := bleve.New(dir+"/coreander/db", indexMapping)
	if err != nil {
		return nil, err
	}

	return &BleveIndexer{index}, nil
}

func addLanguageMappings(indexMapping *mapping.IndexMappingImpl, languages []string) {
	for _, lang := range languages {
		bookMapping := bleve.NewDocumentMapping()
		bookMapping.DefaultAnalyzer = lang
		languageFieldMapping := bleve.NewTextFieldMapping()
		languageFieldMapping.Index = false
		bookMapping.AddFieldMappingsAt("language", languageFieldMapping)
		indexMapping.AddDocumentMapping(lang, bookMapping)
	}
}
```
There is something that I must be doing wrong, because all the docs are in spanish at the moment and should be indexed as such.

**Comment by abhinavdangeti** [comment]
> With bleve 2.0.1 and 1.0.14 versions, doing the following search returns 0 sometimes in the Total field of searchResults

@svera By what you're saying you're probably not getting any results at all when you see total:0. Can you confirm this?

**Comment by svera** [comment]
@abhinavdangeti I get results, but the `Total` field is 0.

**Comment by mschoch** [comment]
Getting results with total 0 is unexpected regardless of anything to do with language analysis.  We would like to reproduce this behavior locally so we can fix this issue.

**Comment by abhinavdangeti** [comment]
Yes to what @mschoch says above^

As for your code that builds the index mapping, you're creating 6 fields named "language" each under 6 different document mappings, and indexing them all into the composite field "_all". 

1. Your query does not specify a field, so it's directed to the composite field _all. While all 6 fields' content analyzed in 6 different ways will be available in the _all field, the match query which uses the "defaultAnalyzer" for the index mapping (which is standard) is likely not matching any of the indexed terms (sometimes!).
2. To address the problem of what analyzer to use for your match query, you could specify the "analyzer" for the match query like this ..
    ```
    query := bleve.NewMatchQuery(keywords)
    query.Analyzer = es.AnalyzerName
    ```

**Comment by svera** [comment]
Ss the index I'm working on is fairly big, let me prepare one with a more manageable size and attach it to the issue. Is that OK for you @mschoch ?

**Comment by svera** [comment]
@abhinavdangeti Thank you for your answer. Regarding 1, is there a more correct way of specifying a different language for each document?

**Comment by mschoch** [comment]
@svera yes, an example that returns 1 result with total 0 would be sufficient.

**Comment by abhinavdangeti** [comment]
> Regarding 1, is there a more correct way of specifying a different language for each document?
> About point 2, the problem is that we don't know the language to use beforehand

Since it's 6 languages you want to search across, you could try using a disjunction query ..
    
    ```
    qEs := bleve.NewMatchQuery(keywords)
    qEs.Analyzer = es.AnalyzerName
    qFr := bleve.NewMatchQuery(keywords)
    qFr.Analyzer = fr.AnalyzerName
    ...

    query := NewDisjunctionQuery(qEs, qFr, ..)
    ...
    ```

**Comment by mschoch** [comment]
Regarding indexing and searching text when you don't know the language ahead of time there are various techniques.

Often times the document text is of sufficient length, that you can you use a library to detect the language somewhat reliably, and index it accordingly.  Based on this determination, it is helpful to index a field with an analyzer set for the appropriate language.  If you're not certain of the language, you could use multiple fields, and in the worst case, it could even be all languages you support.

At query time, the query text might also be of unknown language, but usually it's too short to detect reliably.  For this reason, often times you want to "try all the languages" and hope that the right one matches, and scores highest.

EDIT while I'm typing this I see @abhinavdangeti just gave an example of how you can build a disjunction, and feed the users text in to search across all the possibly language specific fields.

**Comment by svera** [comment]
@mschoch here you have an example. To reproduce the issue, search for the term `everest`. You must do a query with an offset, as this

`searchOptions := bleve.NewSearchRequestOptions(query, resultsPerPage, (page-1)*resultsPerPage, false)`

Issue happens when `page > 1`. Never seen it with offset 0. As I said, it doesn't happen always, so keep trying several times (hopefully not too much)

[db.zip](https://github.com/blevesearch/bleve/files/5852446/db.zip)

**Comment by mschoch** [comment]
OK, I banged out a quick driver program for this, here is what I'm using:

```
package main

import (
	"fmt"
	"log"
	"github.com/blevesearch/bleve/v2"
	_ "github.com/blevesearch/bleve/v2/analysis/lang/es"
	_ "github.com/blevesearch/bleve/v2/analysis/lang/de"
	_ "github.com/blevesearch/bleve/v2/analysis/lang/pt"
	_ "github.com/blevesearch/bleve/v2/analysis/lang/it"
	_ "github.com/blevesearch/bleve/v2/analysis/lang/fr"
)

func main() {

	idx, err := bleve.Open("db")
	if err != nil {
		log.Fatal(err)
	}

	resultsPerPage := 1
	page := 1

	query := bleve.NewMatchQuery("everest")
	searchOptions := bleve.NewSearchRequestOptions(query, resultsPerPage, (page-1)*resultsPerPage, false)
	searchOptions.Fields = []string{"Title", "Author", "Description"}
	searchResults, err := idx.Search(searchOptions)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("total: %d, num results: %d\n", searchResults.Total, len(searchResults.Hits))

	err = idx.Close()
	if err != nil {
		log.Fatal(err)
	}
}
```

However, when I run this, I either get:

```
total: 13, num results: 1
```

Or:

```
total: 0, num results: 0
```

I'm still not sure why the results are changing, but I still never see total 0, with actual hits returned.

**Comment by svera** [comment]
@mschoch have you tried with `page := 2` and `resultsPerPage := 10`?

**Comment by mschoch** [comment]
> @mschoch have you tried with page := 2 and resultsPerPage := 10?

Using these values I get either:

```
total: 13, num results: 3
```
or
```
total: 0, num results: 0

**Comment by svera** [comment]
@mschoch weird, I'm still getting 0 sometimes :( I'll keep looking at it tomorrow and keep you informed. Thank you for your help, really appreciated! 🥇

**Comment by mschoch** [comment]
Here is the reason sometimes the results change (though I still don't see what you're seeing)

The match query tries to find the correct analyzer to use for the _all field, and this is non-deterministic.  So, the search term is analyzed differently on different executions, this means we look for different terms, and sometimes there are matches, sometimes there are not.

So, this goes back to how the mapping is being built.  It seems as though you have defined different document types for the different languages.  This is what leads to the analyzer lookup non-deterministic behavior (if you have multiple types with the same field, we don't know what to do).

**Comment by svera** [comment]
@mschoch @abhinavdangeti finally I found out what is causing the issue, which is a combination of getting 0 results sometimes due to the languages mappings, with code which manages the page requested by the user. Definitely NOT an issue in Bleve but in my own code.

Thank you very much for the assistance and the advice to enhance the code. Closing this.
