### ISSUE TITLE
Question: same document type , but different years, limit search on given year

### ISSUE THREAD

**Issue by Zambiorix** [blevesearch/bleve#1551]
Hi All,

I'm new to Bleve and I'm trying to figure out how to implement the following scenario:
We have an index with a 1 document type and about 15000 documents created per year.

How do I search the index only within a given year?

Creating an index per year? Seems clumsy ..
Creating a different document type per year? And filter somehow?
Other way?

I'm a bit stuck at this and searching for the correct approach...

Thanks!
Gerd

**Comment by mschoch** [comment]
Since your dataset is small, I agree there is no need to partition data by year into separate indexes.

I would suggest you add a field to documents named "year", and simply index the year as a string.

Then when searching, if you want to scope a query to a single year, you would build a ConjunctionQuery with 2 clauses, the first is your original query, and the second is a TermQuery to match the year you're interested in.

**Comment by Zambiorix** [comment]
Thanks!

This is my indexed document, I use default index mapping
```
// ParticipantSearchDocument ...
//
type ParticipantSearchDocument struct {
	event string
	Startnumber int `json:"startnumber"`
	OrderCode string `json:"orderCode"`
	Secret string `json:"secret"`
	FirstName string `json:"firstname"`
	LastName string `json:"lastname"`
	Address string `json:"address"`
	Email string `json:"email"`
	VoucherCode string `json:"voucherCode"`
}
```
`event` is the string representation of the the year. So, I will have to include it in my document.

Currently I'm searching with `Query String Query`
Notice that I also have a number `Startnumber` in my document. 
What happens if a user seaches for startnumber `2020`.
If I use a conjunction query, my first `Query String Query` will return 15000 results, all from `event` from last year.
So, how do I exclude `event` in my first query?

Thanks again!

**Comment by mschoch** [comment]
Still not exactly sure I understand.  What I think you're saying is that the string "2020" is a valid term which might occur in other fields, and you don't want it a users search to match documents that have year "2020" but not in the other fields.  If that is correct, you can configure the year field (event) to set the flag `IncludeInAll` to false:

https://github.com/blevesearch/bleve/blob/2522dc2ba12135da30c368a302df339c68cbe361/mapping/field.go#L58

This will prevent the event year from being included in the _all field, which is what searches run again when not specifying a field.  Then in the term query on the event field for year 2020, you have to explicitly call SetField() to make it search against the event field.

Does this help?

**Comment by Zambiorix** [comment]
Yup, that did help! And that was exactly  what I was looking for
Thank you very much :-)

I've read somewhere that it would be recommended to set:
```
fieldMappingEvent.Analyzer = keyword.Name
```
To prevent my `event` from being analyzed? Is that correct?

**Comment by mschoch** [comment]
Yes that is a good idea, as you want to index the exact values you set.
