### ISSUE TITLE
Underlying db is boltdb for scorch? in that case possible to change to badger?

### ISSUE THREAD

**Issue by hiqsociety** [blevesearch/bleve#1555]
Underlying db is boltdb for scorch? in that case possible to change to badger?

**Comment by mschoch** [comment]
No, that is not correct.  Scorch uses boltdb to store a small amount of meta-data, not to store the index.  There is no reason to switch to badger for this, in fact I hope to eventually remove the use of a database for this entirely.

In [Bluge](https://github.com/blugelabs/bluge) the new search library I'm working on, we write the snpashot meta-data directly to files, just the index segment data.

**Comment by hiqsociety** [comment]
ok thx
