### ISSUE TITLE
Difference in batch execution time in bleve v2

### ISSUE THREAD

**Issue by liorblob** [blevesearch/bleve#1560]
We're working on upgrading bleve to v2, and currently experiencing a major difference in execution times after the upgrade.

We have the following objects:
`Index           bleve.Index`
`Batch         *bleve.Batch`

And we perform the following operation:
`Index.Batch(Batch)`

On the previous version, this operation, on the first execution, took `0.162936` seconds, and in v2, this operation takes `2.084980` seconds (on the first execution only, afterwards the times are pretty on par with the previous version).

We're trying to figure out where this difference is coming from as the only thing we changed is the version. 

I'm not very familiar with the implementation, but one thing I noticed in debugging was that the `Batch` operation was performed in `scorch.go` in v2, and in `upsidedown.go` in the previous version.

Any help would be appreciated.

**Comment by mschoch** [comment]
The default index type changed in v2 to scorch.  If your application creates new indexes using the New() method, it would have created upsidedown indexes in the past, and now will create scorch indexes.  These indexes are not interchangeable, so calls to Open() are not affected, the correct implementation is used.

As for why the first batch takes longer, there are a few follow-up questions:
- Which KV store were using with upsidedown?  If you were just using the New() method above, it would be boltdb.
- How big is the batch?
- Are you reusing batch objects?
- When you describe the execution time of the batch method, are you calling in synchronously?  Or do you have multiple goroutines executing batches?

**Comment by liorblob** [comment]
Thanks for the prompt response.
We're using boltdb as KV store.
I used a test which is indexing just one item. 
We're executing batches in goroutines but in this case it's just this one item.

**Comment by mschoch** [comment]
Scorch doesn't handle batches of size 1 very well.  Each batch becomes an initial segment file on disk, which later gets merged into more appropriate segment sizes.  That still doesn't explain why the first batch is slower than the others, unless there is something else going on with how they're being measured.

Is it possible to change the test to use batch sizes more similar to your real application?
Is it possible for you to share the test?

**Comment by liorblob** [comment]
I'll look into the test and update.

**Comment by liorblob** [comment]
it seems like we're already initializing bleve with scorch index type, yet the batch was done in upsidedown in the previous version and now with v2 it's in scorch. is it possible? or is there something I'm missing?

**Comment by mschoch** [comment]
@liorblob no that doesn't really make sense.  The two implementations are completely different and incompatible.  You will have to provide more details about what your code is actually doing.

**Comment by liorblob** [comment]
so it seems like we do use upsidedown for some indexes. In my test there's indexing of of 2 items, one uses upsidedown and the other uses scorch.
The degradation in the execution time is actually in the upsidedown type.

**Comment by mschoch** [comment]
Nothing substantial has changed in upsidedown for years.  To track this down further, it would be helpful if you could share a runnable test case which illustrates this difference (v1 fast, v2 slow).

**Comment by liorblob** [comment]
The issue was the default index type for bleve. It did switch from upsidedown to scorch on some use cases which caused the difference. Thanks for the assistance.
