### ISSUE TITLE
Possible to bring back a version that we can use our own storage layer backend?

### ISSUE THREAD

**Issue by hiqsociety** [blevesearch/bleve#1561]
Possible to bring back a version that we can use our own storage layer backend?

A forked development of it.

The latest bleve is too restricted.

**Comment by mschoch** [comment]
We have not yet removed support for any of the older storage technologies.

However, we do plan to.  Can you provide more details about how the latest bleve is too restrictive?

**Comment by hiqsociety** [comment]
your storage layer is not optimum (sorry to say) but we can do better than use the default storage u are building now. besides, u changed many times from moss to scorch and to... not sure what's the latest. will use our own storage. possible to open up api or give us an opportunity to try our own storage?

**Comment by mschoch** [comment]
The index implementation is an interface, you are already free to use your own implementation.  If you really think that using the old upsidedown index with your own customer storage is better, then you can already do that today.  You should fork the upsidedown implementation, and be prepared to maintain that code yourself.  Also, over time we will be modifying the index interface, and it will be your responsibility to keep your implementation compatible.

We're trying to run an open-source project, and so your vague concerns without any actual alternative isn't helpful (sorry to say).  The scorch index implementation isn't perfect, but it's the one the team and most of the community is actively working on to make better.  Comments about how you're "not sure what's the latest" reveal that you've not really made any attempt to participate in the community, so we don't really owe you anything.
