### ISSUE TITLE
Match entire phrase instead of isolated word

### ISSUE THREAD

**Issue by Matias-Barrios** [blevesearch/bleve#1565]
Hi folks. This I posted it here : https://stackoverflow.com/questions/66460738/matching-text-to-images-using-fuzzy-search
but Im bringing it here as I  was not able to make it work :

I am using this package: https://github.com/blevesearch/bleve to create a mapping of products2images.

It is working fine when I use single terms, but not at all if I use an entire phrase. For instance, if I use this :

    query := bleve.NewFuzzyQuery("lacteo")

it will correctly map the right image. However, If I do this :

    query := bleve.NewFuzzyQuery("lacteo leche yogurt cebolla")

It will not match anything at all.

What am I doing wrong here ?

Set DB :

    package main
    
    import (
    	"github.com/blevesearch/bleve"
    )
    
    func main() {
    	message := []struct {
    		Id   string
    		Body string
    	}{
    		{
    			Id:   "lacteos.jpg",
    			Body: "lacteo leche yogurt cebolla",
    		},
    		{
    			Id:   "cafe.jpg",
    			Body: "café yerba té",
    		},
    		{
    			Id:   "queso.jpg",
    			Body: "lacteo leche yogurt cebolla queso",
    		},
    		{
    			Id:   "harina.jpg",
    			Body: "harina",
    		},
    	}
    	mapping := bleve.NewIndexMapping()
    	index, err := bleve.New("example.bleve", mapping)
    	if err != nil {
    		panic(err)
    	}
    	index.Index(message[0].Id, message[0])
    	index.Index(message[1].Id, message[1])
    	index.Index(message[2].Id, message[2])
    	index.Index(message[3].Id, message[3])
    }

Search for something :

    package main
    
    import (
    	"fmt"
    	"log"
    
    	"github.com/blevesearch/bleve"
    )
    
    func main() {
    	index, _ := bleve.Open("example.bleve")
    	query := bleve.NewFuzzyQuery("lacteo leche yogurt cebolla queso")
    	query.SetFuzziness(2)
    	searchRequest := bleve.NewSearchRequest(query)
    	searchResult, err := index.Search(searchRequest)
    	if err != nil {
    		log.Fatal(err.Error())
    	}
    	for _, v := range searchResult.Hits {
    		fmt.Println(v.ID)
    		fmt.Println(v.Score)
    		fmt.Println("-------------")
    	}
    }

**Comment by mschoch** [comment]
The main problem is that FuzzyQuery operates only on individual terms, not phrases.

Doing a fuzzy phrase query would be possible, but would require implementing a new searcher.  NOTE: it would potentially be quite expensive as fuzzy term matching can expand to lots of terms, so there would be significantly more possible location matches to consider.

I took a quick search to see if ES does this, or how it could be done with ES, and found a few posts like this:

https://stackoverflow.com/questions/53652765/elastic-search-match-phrase-fuzziness

Apparently, you can accomplish it using span queries.  Span queries are sort of a generalization of phrase queries.  But unfortunately Bleve does not yet have support for span queries.

**Comment by Matias-Barrios** [comment]
Thanks so much for the information!
