### ISSUE TITLE
Open bleve index from 2 different program

### ISSUE THREAD

**Issue by shashank-sachan** [blevesearch/bleve#1571]
Hi,

I just started to use bleve and trying to run query from 2 different program on same index but look like whichever program open & read the index first, keeps an lock and doesn't release it until it close the connection and other program is able to read after that only.
Is there any way to read the same index in parallel from different programs. Or is there any flag that I need to pass so bleve knows that we are opening the index for read only and it is ok to read it by more than one programs as it will not modify any data.

`index, err = bleve.Open(indexLocation)`

Thanks,

**Comment by lboquan** [comment]
I use OpenUsing() to set read only flag.  But I am curious if we should open and close index everytime we search or should we keep index object for reuse.

`
index, err := bleve.OpenUsing(indexLocation, map[string]interface{}{
		"read_only":    true,
		"bolt_timeout": "10s",
})
if err==nil {
     defer index.Close();
}
`

**Comment by mschoch** [comment]
@shashank-sachan by default the index is opened in read/write mode, and only one process can access the index in this mode.  As @lboquan indicated, you can open the index read-only using this setting, however this too has limitations.  While you can have multiple read-only processes, they are exclusive of any read-write process.  This means that if you ever have to open the index for writing, no other processes will be able to access the index at that time.

I have an experimental off-shoot of Bleve called Bluge which attempts to address this problem: https://github.com/blugelabs/bluge/  It uses operating system locking primitives to organize shared access to older snapshots, allowing read-only processes to keep operating while a separate read-write process updates the index.

I'm attempting to back-port this functionality to bleve, but currently none of the companies sponsoring my work need this functionality, so progress has been slow.

**Comment by shashank-sachan** [comment]
> I use OpenUsing() to set read only flag. But I am curious if we should open and close index everytime we search or should we keep index object for reuse.
> 
> `index, err := bleve.OpenUsing(indexLocation, map[string]interface{}{ "read_only": true, "bolt_timeout": "10s", }) if err==nil { defer index.Close(); }`

Thanks @lboquan. I think we should keep the the index open and don't close the connection everytime because opening an connection everytime will take some time if you have alot of documents.

**Comment by shashank-sachan** [comment]
> @shashank-sachan by default the index is opened in read/write mode, and only one process can access the index in this mode. As @lboquan indicated, you can open the index read-only using this setting, however this too has limitations. While you can have multiple read-only processes, they are exclusive of any read-write process. This means that if you ever have to open the index for writing, no other processes will be able to access the index at that time.
> 
> I have an experimental off-shoot of Bleve called Bluge which attempts to address this problem: https://github.com/blugelabs/bluge/ It uses operating system locking primitives to organize shared access to older snapshots, allowing read-only processes to keep operating while a separate read-write process updates the index.
> 
> I'm attempting to back-port this functionality to bleve, but currently none of the companies sponsoring my work need this functionality, so progress has been slow.

Thanks @mschoch for pointing this out. I was thinking to maintain an seperate index data for write and then keep an snapshot for reading only. And somehow update the snapshot whenever there is write on the original index data. I'm not sure how I'll do it but I'll keep digging.
Thanks again for awesome library.

**Comment by shashank-sachan** [comment]
So I also see that when I'm opening the connection in read only mode then during that time, we cannot open the connection in read/write mode. Is this expected behaviour?

**Comment by mschoch** [comment]
@shashank-sachan yes, as I said in my comment:

>  While you can have multiple read-only processes, they are exclusive of any read-write process.

This is a known limitation of the library today.  As I also said in my comment, we know how to work around it, you can use the Bluge library (linked above) if you must have it right now.  We are planning to back-port this change from Bluge to Bleve, but it will take some time as many unrelated pieces have to come together.

**Comment by dpanic** [comment]
Sorry for off topic, but what is the difference between Bludge and Bleve?

**Comment by bartmika** [comment]
@lboquan @mschoch @shashank-sachan Thank you so much for explaining this issue and the technical discussion here. I am having the same problem and decided to go a different route.

I decided to create a standalone server to allow multiple applications to access `bleve`. This is just in case in the future I want to move the standalone server to another machine to handle the workload. The code can be found at [bleve-server](https://github.com/bartmika/bleve-server) for anyone else who stumbles upon this issue. Currently it only supports Golang RPC standard package for inter-process communication with applications.

Thanks again to the team whom build `bleve`!
