### ISSUE TITLE
Searching with url or random string returns every row. 

### ISSUE THREAD

**Issue by candtechsoftware** [blevesearch/bleve#1573]
Search: https://github.com/example/somethin

Using 

```
// For loop 
qString := bleve.NewQueryStringQuery(fmt.Sprintf(`%s~1`, strippedTerm))
queries = append(queries, qString)
// end loop 
query := bleve.NewConjunctionQuery(queries...)
request := bleve.NewSearchRequestOptions(query, 90, 0, false)
request.Fields = []string{"*"} // return all fields
request.SortBy([]string{"Last Name", "First Name", "Facility Name"})
```

There is no value in the index but it is returning all the results (up to 90 but If it raise it it returns more) 
I am not sure why this is doing this. I have tried an exact match query and it does the same

**Comment by mschoch** [comment]
It's hard for us to debug this without a complete example illustrating the issue.

My best explanation for what is happening is that you have URLs that were analyzed with the standard analyzer, which creates separate tokens like:

```

Position | Term | Start | End
-- | -- | -- | --
1 | https | 0 | 5
2 | github.com | 8 | 18
3 | example | 19 | 26
4 | somethin | 27 | 35
```

Then at search time, when you're searching the URL, it too is tokenized the same way, and if all of your documents have some URL with "https" or "github.com" they all end up matching.  But I can't be sure that is correct without a more complete example seeing data, mapping, and search results.

Also, you say the same happens for "exact match" query, but you haven't explained how you're trying to do that.
