### ISSUE TITLE
Bleve is not working on GO 1.16.2 ?

### ISSUE THREAD

**Issue by metalwolf** [blevesearch/bleve#1578]
My environment works perfectly on GO 1.15.5
When I upgrade to 1.16.2 I just get at start this error:

goroutine 1 [running]:
syscall.(*mmapper).Mmap(0x7fdf67f002a0, 0x7, 0x0, 0x8000, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/syscall/syscall_unix.go:75 +0x173
syscall.Mmap(...)
        /usr/local/go/src/syscall/syscall_linux.go:1230
go.etcd.io/bbolt.mmap(0xc000128800, 0x8000, 0x0, 0x0)
        /home/sites/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/bolt_unix.go:52 +0xa5
go.etcd.io/bbolt.(*DB).mmap(0xc000128800, 0x0, 0x0, 0x0)
        /home/sites/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:360 +0x245
go.etcd.io/bbolt.Open(0xc000022510, 0x12, 0x7fdf00000180, 0xc00063e8c0, 0xfa2ce0, 0xfa5068, 0x1)
        /home/sites/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:277 +0x38d
github.com/blevesearch/bleve/index/store/boltdb.New(0x7fdf679e9c78, 0x7fdf67ff89c0, 0xc0002278c0, 0x6, 0xc0002a1750, 0xc0002278f0, 0x7fdf675848e0)
        /home/sites/go/pkg/mod/github.com/blevesearch/bleve@v1.0.10/index/store/boltdb/store.go:83 +0x2a7
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Open(0xc000100580, 0x0, 0x0)
        /home/sites/go/pkg/mod/github.com/blevesearch/bleve@v1.0.10/index/upsidedown/upsidedown.go:308 +0x116
github.com/blevesearch/bleve.openIndexUsing(0x7fdf67479f51, 0xc, 0x0, 0xc00028a070, 0x0, 0x0)
        /home/sites/go/pkg/mod/github.com/blevesearch/bleve@v1.0.10/index_impl.go:173 +0x542
github.com/blevesearch/bleve.Open(...)
        /home/sites/go/pkg/mod/github.com/blevesearch/bleve@v1.0.10/index.go:286
kiwilimon/entities/blevesearch.init.0()
        /home/sites/kiwi7/app7/kiwilimon/entities/blevesearch/blevesearch.go:63 +0x187
plugin.open(0xc000454080, 0x1f, 0xc00008ec00, 0x54, 0xfa2ce0)
        /usr/local/go/src/plugin/plugin_dlopen.go:101 +0xc1e
plugin.Open(...)
        /usr/local/go/src/plugin/plugin.go:32
github.com/webability-go/xamboo/applications.Link()
        /home/sites/go/pkg/mod/github.com/webability-go/xamboo@v1.6.0/applications/linker.go:108 +0xcd6
github.com/webability-go/xamboo.Run(0x7fff86cc7225, 0xa, 0x0, 0x0, 0x0, 0x0, 0x12)
        /home/sites/go/pkg/mod/github.com/webability-go/xamboo@v1.6.0/runner.go:50 +0xf4
main.main()
        /home/sites/kiwi7/xamboo.go:25 +0x115
exit status 2

Seems there is some incompatilibity with bbolt and go 1.16.2 ?

**Comment by shashank-sachan** [comment]
I'm using it with go 1.16.2 and it's working fine for me.

**Comment by mschoch** [comment]
I just updated to 1.16.2 and the unit tests all pass for me.

**Comment by metalwolf** [comment]
Ok. I am going to isolate the error into a tiny code to reproduce

**Comment by metalwolf** [comment]
After some fast tests it's due to the same error I had on plugins (bleve is loaded through a plugin) , already reported and corrected in the go core... will have to wait for go 1.16.3 to work I guess

https://github.com/golang/go/issues/44956

**Comment by metalwolf** [comment]
Speaking about the wolf....
They just released today go 1.16.3 and the error is gone. Compiling and working fine again.
So basically bbolt / syscall.Mmap is not working con Go 1.16.1 and 1.16.2 as a **plugin**
