### ISSUE TITLE
Alias query

### ISSUE THREAD

**Issue by shashank-sachan** [blevesearch/bleve#1579]
Hi,

I'm trying to use alias. If I understand correctly, alias is useful if we have long running process but if I'm running code which close the connection as soon as it completes write, is it useful?
Also if we want to use alias, then we need to open the connection with actual path and then create the alias using that?
It's not something where we create alias and it get saved somewhere and then we can open the connection using alias name directly? 

Thanks

**Comment by mschoch** [comment]
Aliases actually have 2 separate use cases (unfortunate in hindsight).

1.  You can atomically switch from pointing to one index to another.  This is useful if logically your application always searches the same thing, but your implementation is swapping in different physical indexes underneath.  For example, users always only search against the last quarter of sales data.  Periodically, you have to swap the physical indexes, and you don't want any downtime for your application.  So you start with the alias "salesData" -> "salesDataQ1" and you switch it to "salesData" -> "salesDataQ2".
2.   You can have an alias point to multiple indexes at the same time, and run a search query across all of them, merging the results.  This is useful if you partition your data by something (domain, time, etc) but need to run the search on all of them.  For example, your data is partitioned into separate indexes for users, blogs, and comments.  To search, the application queries an alias "seachData" which points to "users", "blogs" and "comments".

To assist your further it would help to understand which of these you plan to use.

Finally, yes the aliases are in memory only and not persisted.  While your application can create them and use them for a long time, in some applications I've worked on they are ephemeral, created on demand at search time, and thrown away immediately after (this is useful for dynamic systems, where the indexes are on remote machines which may come and go).

**Comment by shashank-sachan** [comment]
My use case is point 1 where I'm creating indexes like salesDataQ1 and then later at some point salesDataQ2.
So write now if I have to create an alias for salesDataQ1 then I'll do something like this:

        index, _ := bleve.Open("IndexPath") // in this case salesDataQ1 path
	aliasImpl := bleve.NewIndexAlias()
	aliasImpl.SetName("salesDataQ1")
	aliasImpl.Add(index)
	
From this point we can do the query using this alias.
Now later at some point if I create salesDataQ2 then I have to change the above code (stop the process, change the indexPath to salesDataQ2, start the process).
So if we have to open the connection with original index path then how alias is useful here as we need to be aware about the original index always. I was thinking we can directly open the index (bleve.Open) using alias name.

**Comment by mschoch** [comment]
So, here:

> later at some point if I create salesDataQ2

You don't stop the process, you invoke:

```
alias.Swap([]Index{oldIndex}, []Index{newIndex})
```

All searches against the alias continue without any interruption.  At some point, there is atomic switch from searching the old to the new.

**Comment by mschoch** [comment]
Sorry I got that backwards, it should be:

```
alias.Swap([]Index{newIndex}, []Index{oldIndex})

**Comment by shashank-sachan** [comment]
okay so I can run alias.Swap from seperate process and all the existing running process will start running the query against the new index

**Comment by mschoch** [comment]
No, everything in bleve is single process.

**Comment by shashank-sachan** [comment]
Sorry I'm confused here. All my queries are running on index "salesDataQ1" using alias "salesData". I'm in quarter1 so I cannot

**Comment by shashank-sachan** [comment]
> So, here:
> 
> > later at some point if I create salesDataQ2
> 
> You don't stop the process, you invoke:
> 
> ```
> alias.Swap([]Index{oldIndex}, []Index{newIndex})
> ```
> 
> All searches against the alias continue without any interruption. At some point, there is atomic switch from searching the old to the new.

Sorry I'm confused here, I can swap only when I'm in Quarter2. So if my code is running from quarter1 then how can we call the swap without editing & re-running the existing it.

**Comment by mschoch** [comment]
Sorry I'm just as confused, I don't understand the question.  You call Swap when you want the change to take effect.

I don't know what the statement "my code is running from quarter 1" means.

**Comment by mschoch** [comment]
The alias use case 1 above is designed for a long running process, that is running when the switch from Q1 to Q2 happens.

It sounds like you have multiple process coming and going.  In which case, nothing in Bleve will help with this.

**Comment by shashank-sachan** [comment]
Ok, I think I understand. My process is not long running that's why it's not applicable in my case.
