### ISSUE TITLE
search query with multiple fields & boosting

### ISSUE THREAD

**Issue by shashank-sachan** [blevesearch/bleve#1580]
Hi,

I'm trying to build search query. Bleve documentation tells about the search query (Query String Query) on multiple fields and boost each field by ^ sign but I'm not sure how to do it if I'm building my query using `query.NewMatchQuery`.
For example: if I have a searchTerm `home` and I want to search it in title & description field and want to give more importance to title. Is something like this correct?

                searchQuery1 := query.NewMatchQuery("home")
		searchQuery1.SetField("title")
		searchQuery1.SetBoost(5)
		
	        searchQuery2 := query.NewMatchQuery("home")
		searchQuery2.SetField("description")
		searchQuery2.SetBoost(4)

               should := []query.Query{searchQuery1, searchQuery2}
               must := []query.Query{}
               mustNot := mustNot

               queryGroup := query.NewBooleanQuery(must, should, mustNot)
               queryGroup.SetMinShould(1)
               
Thanks,

**Comment by mschoch** [comment]
Yes that looks correct to me.  However, you should be aware that the scoring of disjunction queries has something called a coordination factor.  This is useful in many (but not all) cases.  I mention it here because it sometimes makes it hard to get boosting to work the way you expect.  You may have to play with the boost values to find what works.

There is a PR to disable the coordination factor here: https://github.com/blevesearch/bleve/pull/1191

However, we have not acted on that yet.

**Comment by shashank-sachan** [comment]
okay, thanks @mschoch! But one thing that I'm not clear if I have 2 more term query and that 1 of them should match then how do I query that. 

       // At least one match between set1SearchQuery1 & set1SearchQuery2
        set1SearchQuery1 := query.NewMatchQuery("home")
	set1SearchQuery1.SetField("title")
	
        set1SearchQuery2 := query.NewMatchQuery("home")
	set1SearchQuery2.SetField("description")

        // At least one match between set2Filter1 & set2Filter2
         set2Filter1 := query.NewTermQuery("open")
         filter.SetField("status")
         
         set2Filter2 := query.NewTermQuery("true")
         filter.SetField("published")
         
Now I need to query like -> where ('home' in title OR 'home' in description) AND (status is 'open' OR published is 'true')
I'm not sure how can we write the query for this. It looks like nested must/should. Is it possible to query like this?

**Comment by mschoch** [comment]
All of these queries can be nested.  Conjunction is AND, disjunction is OR.  Boolean just combines conjunctions and disjunctions in a way that is more compact.

For your case, you want something like:

- Conjunction
    - Disjunction
        - 'home' in title
