### ISSUE TITLE
Multiple read connection increased connection time

### ISSUE THREAD

**Issue by shashank-sachan** [blevesearch/bleve#1581]
Hi,

I was doing load test and I observed if I open multiple read connection concurrently then connection time is getting increased.
This is the code for connecting:

```
runtimeConfig := map[string]interface{}{"read_only": true, "bolt_timeout": "2s"}
bleveSession, err := bleve.OpenUsing(indexLocation, runtimeConfig)
```

Load Test:

```
for i := 0; i < 1000; i++ {
    wg.Add(1)
    go run(&wg, i) // run will create a read only connection and perform some search query
}
```

(There are no write connection)
Is something wrong here or there is some restriction by bleve or OS?

Thanks,

**Comment by mschoch** [comment]
Within a single process, it would not be recommended to do it this way, instead we'd recommend you open the index once, and share the bleve instance (it is thread safe).

However, from previous conversations, I suspect you're really interested in (and seeing performance degradation in) multiple processes acquiring read-only access to the same index.  While this is supported, it's not something that has received much (if any) testing.  You'll have to do some investigating on your own.

**Comment by shashank-sachan** [comment]
I'm actually trying to build the search in serverless environment using AWS lambda. As it doesn't run on a single server can be run concurrently, it opens the multiple connections.
