### ISSUE TITLE
new import path for bitset

### ISSUE THREAD

**Issue by agentabstract** [blevesearch/bleve#1595]
Whenever I do a go get -u I'm getting this:

go get: github.com/willf/bitset@v1.1.11 updating to
        github.com/willf/bitset@v1.2.0: parsing go.mod:
        module declares its path as: github.com/bits-and-blooms/bitset
                but was required as: github.com/willf/bitset

I looked in my vendor folder and it's being imported in bleve.  You'll need to update this import.  It's moved. 

Thanks!

**Comment by mschoch** [comment]
Thanks, this has been reported: https://github.com/blevesearch/bleve/pull/1592
