### ISSUE TITLE
Configuration parameter override in index FTS

### ISSUE THREAD

**Issue by nelsonxx1** [blevesearch/bleve#1603]
Hello Couchbase friends. I have a problem with the parameter setting to increase the size of the number of documents returned by the FTS indexes (bleveMaxResultWindow).

When I modify it with via REST API like this:

`curl -XPUT -H "Content-type: application / json" http: // <username>: <password> @ <ip>: 8094 / api / managerOptions -d '{"bleveMaxResultWindow": "999999999"}'`

When the cluster had only one node, it worked fine. But when adding 2 more nodes to the cluster, the default configuration values are taken which is 10,000

I already tried putting environment variable

CBFT_ENV_OPTIONS = bleveMaxResultWindow = 999999999

but it doesn't work either.

According to the documentation it seems that this parameter is to configure the node, but the cluster configuration overwrites the parameter with the default value.

Couchabse 6.6.0
Ubuntu 20 OS
1 cluster, 3 nodes

**Comment by abhinavdangeti** [comment]
This is NOT a bleve issue.
Feel free to open a Couchbase support ticket or raising it in the Couchbase forums and we'll help you out with it.
