### ISSUE TITLE
scorch_segment_api still imports an old version of RoaringBitmap

### ISSUE THREAD

**Issue by orius123** [blevesearch/bleve#1619]
Need to align to `v0.7.3` like all the other packages, no?

https://github.com/blevesearch/scorch_segment_api/blob/master/go.mod#L6

**Comment by mschoch** [comment]
Should? yes.  Need? I don't know.

**Comment by orius123** [comment]
Any reason against aligning it?

**Comment by mschoch** [comment]
The reason is that Go modules is difficult, we are human, and we missed it.

**Comment by abhinavdangeti** [comment]
https://github.com/blevesearch/scorch_segment_api/pull/13

**Comment by orius123** [comment]
> The reason is that Go modules is difficult, we are human, and we missed it.

Go modules is indeed difficult..
Thanks for all the hard work fighting with it!!

**Comment by josephGuo** [comment]
github.com/RoaringBitmap/roaring@0.94
