### ISSUE TITLE
Cannot search against indexes in folders without write access

### ISSUE THREAD

**Issue by ckollett** [blevesearch/bleve#1623]
If a Bleve index is in a folder that the current user does not have write access to, searching fails when you attempt to open the index, even with the read only option selected as follows:
`index, err := bleve.OpenUsing(pathToIndex, map[string]interface{}{"read_only": true})`

The underlying issue seems to be that, by default, BoltDB will always attempt to open files using CREATE permissions. Here is the code from BoltDB that does this:
`db.openFile(path, flag|os.O_CREATE, mode)`

Given that BoltDB allows calling code to override the default function used to open the bolt file, it is possible to work around this issue in Bleve by creating a function that will open the bolt file without requiring CREATE permission.

For more information, please see [my post to the Bleve Google Group](https://groups.google.com/g/bleve/c/b89GwDqlL4I).

**Comment by abhinavdangeti** [comment]
So `openFile(path, os.O_RDONLY|os.O_CREATE, mode)` should fail with "_permission denied_" only if the file at the path you are attempting to access does not exist.

So the bleve.Index you're attempting to access hasn't been created yet?
 
Would you share the following ..

- the path you're passing in for the index
- the permissions of the directories in your path (note that they should at least be 0500) 
- exact error message you see

**Comment by ckollett** [comment]
Thanks for your response.

I am working on Windows, and can reproduce this behavior using either a UNC path or a mapped drive.

The index that I am attempting to access exists in a folder with permissions rwxr-xr-x (755). The root.bolt file itself has permissions rw-r--r-- (644). I am not the owner of these files so I cannot write to the folder or modify the file.

The exact error message is:
```
error(*io/fs.PathError) *{Op: "open", Path: "\\\\<path to index>\\bleve_index\\store\\root.bolt", Err: error(syscall.Errno) ERROR_ACCESS_DENIED (5)}
```

I can easily reproduce this behavior with the following code. When I run this the first code block successfully opens my root.bolt file, whereas the second block will throw an error.
```
// First try opening the file with read-only permissions
_, err1 := os.OpenFile(filePath, os.O_RDONLY, 0600)
if err1 == nil {
    fmt.Println("Successfully opened file " + filePath)
} else {
    fmt.Println("Error opening file " + filePath)
}
```
```
// Now try opening with read only and create permissions
_, err2 := os.OpenFile(filePath, os.O_RDONLY|os.O_CREATE, 0600)
if err2 == nil {
    fmt.Println("Successfully opened file " + filePath)
} else {
    fmt.Println("Error opening file " + filePath)
}
```

**Comment by abhinavdangeti** [comment]
Interesting. Seems like this is possibly windows-only behavior then.
I've tried to do the exact same steps and things work OK on osX.

Doing an os.CREATE and a read-only mode should let you create a file that is only writeable by that process. So, if you close and try it again - you'd see a permissions error.  It seems that's Bolt's design there.

I've created a PR for this - https://github.com/blevesearch/bleve/pull/1624

**Comment by ckollett** [comment]
Interestingly enough, I _can_ reproduce this on a Mac. Perhaps it has something to do with the type of file system that we use for creating archives of our builds, and goes beyond just the setting file permissions. In any case, thank you for your attention to the issue. This is a blocking issue for us and I'm really happy you have been able to get to it so quickly!

**Comment by ckollett** [comment]
In case it helps understand the problem better, I added the following to scorch_test.go. The test fails when run against Bleve as-is, but passes with a fix similar to the one that you wrote in place. This was on Windows; I haven't tried running the test on Mac.
```
func TestReadOnlyIndex(t *testing.T) {
	// Basic test setup.
	cfg := CreateConfig("TestReadOnlyIndex")
	err := InitTest(cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		err := DestroyTest(cfg)
		if err != nil {
			t.Log(err)
		}
	}()

	analysisQueue := index.NewAnalysisQueue(1)
	writeIdx, err := NewScorch(Name, cfg, analysisQueue)
	if err != nil {
		t.Fatal(err)
	}
	err = writeIdx.Open()
	if err != nil {
		t.Fatalf("error opening index: %v", err)
	}
	writeIdxClosed := false
	defer func() {
		if !writeIdxClosed {
			err := writeIdx.Close()
			if err != nil {
				t.Fatal(err)
			}
		}
	}()

	// Add a single document to the index.
	doc := document.NewDocument("1")
	doc.AddField(document.NewTextField("name", []uint64{}, []byte("test")))
	err = writeIdx.Update(doc)
	if err != nil {
		t.Errorf("Error updating index: %v", err)
	}
	writeIdx.Close()
	writeIdxClosed = true

	// After the index is written, change permissions on every file
	// in the index to read-only.
	var permissionsFunc func(folder string)
	permissionsFunc = func(folder string) {
		entries, _ := ioutil.ReadDir(folder)
		for _, entry := range entries {
			fullName := filepath.Join(folder, entry.Name())
			if entry.IsDir() {
				permissionsFunc(fullName)
			} else {
				os.Chmod(fullName, 0555)
			}
		}
	}
	permissionsFunc(cfg["path"].(string))

	// Now reopen the index in read-only mode and attempt to read from it.
	cfg["read_only"] = true
	readIdx, err := NewScorch(Name, cfg, analysisQueue)
	defer func() {
		err := readIdx.Close()
		if err != nil {
			t.Fatal(err)
		}
	}()

	if err != nil {
		t.Fatal(err)
	}
	err = readIdx.Open()
	if err != nil {
		t.Errorf("error opening index: %v", err)
	}
	reader, err := readIdx.Reader()
	if err != nil {
		t.Fatal(err)
	}
	docCount, err := reader.DocCount()
	if err != nil {
		t.Fatal(err)
	}
	if docCount != 1 {
		t.Errorf("Expected document count to be %d got %d", 1, docCount)
	}
}
```

**Comment by abhinavdangeti** [comment]
Ya like I noted earlier, the test passes on my computer (osX) - without the fix.
