### ISSUE TITLE
DateRagne with QueryString between two dates?

### ISSUE THREAD

**Issue by prologic** [blevesearch/bleve#1629]
How do you perform a search between two dates using thee query string language?

**Comment by abhinavdangeti** [comment]
@prologic you're first required to index the particular field as a `datetime` type field.

Say the field name were "dateX", your query string should look like ..
```
+dateX:>=2021-01-01" +dateX:<=2021-10-04"
```
.. the query implying a conjunction of dates greater than less than the chosen values.
 
Note that the date string used within the query string will need to conform to [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by prologic** [comment]
Oh thank you! 🙇‍♂️ The conjunction wasn't obvious to me from reading the docs on they QuerySring matched 👌

**Comment by prologic** [comment]
Confirmed to be working:

https://search.twtxt.net/search?q=%2Bcreated%3A%3E%3D%222021-09-01%22+%2Bcreated%3A%3C%3D%222021-09-30%22

I _believe_ the Syntax is:

Example:
```
+created:>="2021-09-01" +created:<="2021-09-30"
```

Thanks! 🙇‍♂️
