### ISSUE TITLE
roundTook timings incorrect for IndexAliases

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#163]
From an app that's using a bleve alias, the search timings seem to be incorrect (the "roundTook" response field).  One unconfirmed guess is that the bleve alias implementaiton might be summing up the times across various alias targets.

https://github.com/couchbaselabs/intrapop/issues/20

In the app, the workaround was to use client-side JS instead of relying on roundTook.

**Comment by mschoch** [comment]
round took is not actually a response field (that is the massaged for human beings field generated in the js)

The response does contain a "took" field.  The problem we have is that "took" is not really the full search time anyway, its just the time it took to find/score results.

So, I could change the alias code to produce a more meaningful value (by say timing how long it takes to query all the constituents).  But, then its a fundamentally different metric than what is returned for non-aliased indexes.

I think first we should agree on what "took" should mean, and then apply it to all implementations.
