### ISSUE TITLE
paging and aliases doesn't work after first page

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#164]
bleve's alias doesn't seem to work correctly with paging (the From/Size request params) when searching for page >= 2.

The issue seems to be during a MultiSearch(), bleve creates internal child search requests, but copies over the Size field from the parent search request.  Since the child request has From always pegged to 0, that feels incorrect and instead might need to be an unlimited child request Size (but I don't have a quick test case to prove it).  The code I was looking at was here..

https://github.com/blevesearch/bleve/blob/master/index_alias_impl.go#L368

    func createChildSearchRequest(req *SearchRequest) *SearchRequest {
    	rv := SearchRequest{
    		Query:     req.Query,
    		Size:      req.Size, // <<----------- might be incorrect?
    		From:      0,
    		Highlight: req.Highlight,
    		Fields:    req.Fields,
    		Facets:    req.Facets,
    		Explain:   req.Explain,
    	}
    	return &rv
    }

For reference, the issue that I see in my app is...

    https://github.com/couchbaselabs/intrapop/issues/16

**Comment by mschoch** [comment]
Ah, yes that does look like a bug.  The From 0 is required (because data for the Nth page could come from any of the previous pages when scattering the query.  But you're right, the size should then be Size + the original From.  I think this was working before, and I probably broke it when I rewrote this code to address the data race in #130.

I'll take a look...

**Comment by mschoch** [comment]
Leaving this open for now.  This commit fixes a problem, but perhaps not the problem.  I added a test case, but its more of a unit test to check expectations, not an integration test to verify behavior.

**Comment by mschoch** [comment]
Since @steveyen closed the related issue I'm assuming this works.
