### ISSUE TITLE
`TermFacets.Terms()` can now panic

### ISSUE THREAD

**Issue by bmhatfield** [blevesearch/bleve#1653]
Prior to this PR: https://github.com/blevesearch/bleve/pull/1404, a user interacting with `search.FacetResult` was safe to range over `Terms`, because Go will do the right thing when ranging over a nil slice. As of 1404, the interface changed to require a call into `.Terms()`, which does not have a nil guard. If `FacetResult.Terms` is nil, this will result in a panic. It's possible to guard this from calling code, but should not be necessary.

Note, also: 1404 was a backwards incompatible change which required code updates to address in calling code.

**Comment by abhinavdangeti** [comment]
@bmhatfield yes we understand it's a breaking change - reason why the last release was a major version change. I've advertised it here - https://github.com/blevesearch/bleve/releases/tag/v2.3.0

Placed a nil guard within the Terms() API with this - https://github.com/blevesearch/bleve/pull/1654
