### ISSUE TITLE
Please add a security policy

### ISSUE THREAD

**Issue by sirdarckcat** [blevesearch/bleve#1657]
Hi

Please define how to report vulnerabilities in this project.

**Comment by arraypad** [comment]
bump

**Comment by iredmail** [comment]
How about simply report here?

**Comment by sirdarckcat** [comment]
That's a decision for the project owners to make.

**Comment by iredmail** [comment]
If the info is not confidential, then this public issue tracker should be good enough, and a lot open source softwares hosted on GitHub do it this way.

**Comment by abhinavdangeti** [comment]
@sirdarckcat We'll add a security policy here soon. Stay tuned.

**Comment by sirdarckcat** [comment]
thanks
