### ISSUE TITLE
Perform includes like query

### ISSUE THREAD

**Issue by anshulrgoyal** [blevesearch/bleve#1658]
how can run an includes like query on a field like a search term "28 day" match "Recharge again in 28 days" and I don't want to match "my game is on third day"?

**Comment by abhinavdangeti** [comment]
@anshulrgoyal If you use the "standard" analyzer for the field while indexing the field .. these are the tokens generated for your text (after tokenizing on unicode, dropping english stop words and converting to lower case) ..

```
recharge
28
days
```

If you use a search query now like this ..
```
{"match": "28 day", "field": "content"}
```

.. it would apply the analyzers set for the field within the index over the search term which generates 2 tokens `["28", "day"]` and would look for the occurrence of either of those tokens from you indexed content which could end up matching a document that has `my game is on third day`.

This query can be altered to match all the tokens generated for the search term this way ..
```
{"match": "28 day", "field": "content", "operator":"and"}
```

This would obtain document hits where both the tokens `["28", "day"]` are available, however - in no particular order.

If the ordering of this text matters to you, you should include term vectors for the field while indexing (which would index the array positions of generated tokens), and you can use a match_phrase query ..
```
{"match_phrase": "28 day", "field": "content"}
```

**Comment by anshulrgoyal** [comment]
```go
matchQuery := bleve.NewMatchQuery(fmt.Sprintf("%s", search))
matchQuery.SetOperator(query.MatchQueryOperatorAnd)
```

where the search is `28 day` and content is `28 days` and I am not getting any results.

**Comment by abhinavdangeti** [comment]
Slight correction in my earlier comment.

The `standard` analyzer indexes "days" as "days", we want to bring it down to its root word for day/days to match the same token.

Using the `en` analyzer (instead of `standard`) to index the field should be the right move for you here. The query will remain the same.
