### ISSUE TITLE
Can I use bleve to search files for lines containing substrings.(I have a very large file 20gb and cant load it to mem)

### ISSUE THREAD

**Issue by HCBlackFox** [blevesearch/bleve#1670]

**Comment by abhinavdangeti** [comment]
Bleve's scorch search engine will only allow for searching over content that is created by it.

So you will need to find a way to insert the file contents into the index by defining rules for it (the index mapping) via supported APIs. The index will support a Search(..) API to allow for you to search the indexed content.

Here's the interface ..
https://github.com/blevesearch/bleve/blob/v2.3.2/index.go#L207...L251

**Comment by HCBlackFox** [comment]
> Bleve's scorch search engine will only allow for searching over content that is created by it.
> 
> So you will need to find a way to insert the file contents into the index by defining rules for it (the index mapping) via supported APIs. The index will support a Search(..) API to allow for you to search the indexed content.
> 
> Here's the interface .. https://github.com/blevesearch/bleve/blob/v2.3.2/index.go#L207...L251

Thank you, I tried to split my large file to smaller and index all files, but this is so slow, and after 2 hours It's starting to eat up all my RAM.

Here is my code, maybe something wrong?

` package main

     import (
	"bufio"
	"fmt"
	"github.com/blevesearch/bleve/v2"
	"os"
	"runtime"
 	"strconv"
 	"time"
     )

        func main() {
	mapping := bleve.NewIndexMapping()
	index, err := bleve.New("DBindex", mapping)
	if err != nil {
		fmt.Println(err)
		return
	}

	a := 1
	log, _ := os.Create("log.txt")

	for i := 1; i <= 809; i++ {
		y := 1
		DB, _ := os.Open(strconv.Itoa(a) + "/" + strconv.Itoa(i) + ".txt")
		//index some data
		scanner := bufio.NewScanner(DB)
		println(i)
		log.WriteString("File: " + strconv.Itoa(i) + "\n")
		for scanner.Scan() {
			Text := scanner.Text()
			println(y)
			go index.Index(strconv.Itoa(a)+":"+strconv.Itoa(i)+":"+strconv.Itoa(y), Text)
			y++
			if runtime.NumGoroutine() >= 10 {
				time.Sleep(100)
			}
		}
	}
	//search for some text

	query := bleve.NewMatchQuery("9228754042")
	search := bleve.NewSearchRequest(query)
	searchResults, err := index.Search(search)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(searchResults) }
`

**Comment by abhinavdangeti** [comment]
@HCBlackFox would you be willing to share a sample from your file (a line or a set of lines) so we get an idea on how your content looks, or simply if you could share what `Text` looks like here in this line ..
```
go index.Index(strconv.Itoa(a)+":"+strconv.Itoa(i)+":"+strconv.Itoa(y), Text)
```
Modeling your content better could be a key player here.

**Comment by HCBlackFox** [comment]
@abhinavdangeti 
Thanks for your time, I solved the problem by switching to Mysql database. I close the question.
