### ISSUE TITLE
IndexMapping.mapDocument() method should be public API?

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#168]
I have a case where I've a batch of documents, but some of those documents in the batch are (correctly) rejected by the IndexMapping.mapDocument() analysis.  (e.g., they might be non-JSON docs.)  So, the whole Index.Batch() invocation (correctly) fails.

In my app scenario, though, I just want to skip those un-mappable/un-analyzable documents and keep on truckin'.

So, I figured that I would graduate from using the easy-to-use "porcelain" API's and just use the lower-level IndexMapping and lower-level index.Batch interfaces directly, so that I would be able to have more granular error handling codepaths.

Along the way, I was blocked in "going lower level" where bleve.IndexMapping doesn't currently expose a public MapDocument() method.  (Instead, it has a non-public IndexMapping.mapDocument() method.)

For more details, the corresponding application level issue is....    https://github.com/couchbaselabs/cbft/issues/31

**Comment by mschoch** [comment]
Yeah I saw the other issue.  I'm not sure this is the correct fix.  In Elasticsearch the batch operation is not intended to offer any transactional semantics (at least not by default, there may be other options).  So, it is common for a batch operation to successfully index some documents, and fail on others.  The error is structured such that you can know which ones succeeded and which ones failed.

I think if proceed to remove the implicit "fsync/commit" behavior then, we too should end up behaving similarly.

Thoughts?

**Comment by steveyen** [comment]
That'll work too... moving away from "all or nothing" semantics or making it optional.

Probably involves an API change, though.  Or maybe tacking on yet another BatchAdvanced() / BatchEx() API someplace (but nice to be backwards compatible)?

Especially, if mapDocument() has some reasons to stay non-public (like, you were planning on rewriting/refactoring big parts of this sometime).

The lazy me just came up with the first proposal as "hey, just turn an m into an M and we're nearly done" :-)

**Comment by steveyen** [comment]
One more thing about this...

For my application use case, I'd guess that I'd want parsing/analysis errors to be "soft"... just keep on trucking through the batch.  (But, I'd need to know the exact documents that had problems (and their related errors).)

But, in contrast, I'd want storage errors (disk full, file corruption, etc) to be hard errors.

**Comment by mschoch** [comment]
The changes to the Batch API in https://github.com/blevesearch/bleve/commit/af356acff0929990ac56b9fef715445f2593ea7f
should address this issue.
