### ISSUE TITLE
CLI indexing is slow / is it using batch mode?

### ISSUE THREAD

**Issue by wkoszek** [blevesearch/bleve#1696]
I have JSON files with 7 keys, only 1 is INT, and 1 "Report" which holds text and is sometimes long - 1.6kB. I've run some experiments on v1 CLI until @abhinavdangeti made me realize v1 is very old. Anyway, the v1 data I obtained:

- 100k JSONs, 400MB of data, v1 Bleve, BoltDB store, 16mint to index, 2.9GB of output index, written to tmpfs was 103 JSONs/s indexing speed
- 8M JSONs, 32GB, v1 Bleve, LevelDB, written to NVMe disk, 60GB index, Was around 130 JSON/s, ~22hr to index

Now on v2 I'm seeing similar speed: 

```
$ bleve index scorch.idx.20220602 out.full | pv --line-mode --rate > /dev/null
[ 111 /s]
[ 105 /s]
```

Apparently it could be much faster if "batching" was used, but @abhinavdangeti stated `bleve index` in v2 isn't doing batch.  When I think about it, the CLI should be doing the fastest thing possible since it's always sort of a batch operation when you point the CLI to a directory to index.

**Comment by abhinavdangeti** [comment]
With scorch, I recommend indexing documents in batches. You will be able to use the bulk option to do this.

```
[14:43:31] AD: ~/Desktop $ bleve bulk --help
The bulk command will perform batch loading of documents in one or more newline delimited JSON files.

Usage:
  bleve bulk [index path] [data paths ...] [flags]

Flags:
  -b, --batch int   Batch size for loading. (default 1000)
  -h, --help        help for bulk
  -j, --json        Parse the contents as JSON. (default true)
```
