### ISSUE TITLE
Indexing 8M files results results in too many open files

### ISSUE THREAD

**Issue by wkoszek** [blevesearch/bleve#1697]
The v1 CLI worked fine for the indexing of 8M JSON files. However, upon upgrading to v2, after several hours of running, I got:

```
[ 111 /s]
[79.6 /s]
2022/06/03 21:54:44 open out.full/reports_594/report_2970715.json: too many open files
[73.2 /s]
```

I suspect there's something differnet in how `bleve index` command behaves in v2.

**Comment by abhinavdangeti** [comment]
You're hitting your file descriptor limit. So, you'll probably want to increase your ulimit setting.

With the CLI, if you use the `index` command, you will be introducing one file (segment) per document - this approach will introduce several files. Scorch comes with a default merge policy (compaction) - where smaller segments are merged into larger ones.

This is the default merge config ..
```
// DefaultMergePlanOptions suggests the default options.
var DefaultMergePlanOptions = MergePlanOptions{
	MaxSegmentsPerTier:   10,
	MaxSegmentSize:       5000000,
	TierGrowth:           10.0,
	SegmentsPerMergeTask: 10,
	FloorSegmentSize:     2000,
	ReclaimDeletesWeight: 2.0,
}
```

For your situation, you can look into making the merge policy more aggressive. But the **better thing to do** is to introduce documents in batches into your index. You can use the `bulk` command with the CLI for this.

```
[14:43:31] AD: ~/Desktop $ bleve bulk --help
The bulk command will perform batch loading of documents in one or more newline delimited JSON files.

Usage:
  bleve bulk [index path] [data paths ...] [flags]

Flags:
  -b, --batch int   Batch size for loading. (default 1000)
  -h, --help        help for bulk
  -j, --json        Parse the contents as JSON. (default true)
```
