### ISSUE TITLE
Can we specify different word separators during search and index creation?

### ISSUE THREAD

**Issue by json7** [blevesearch/bleve#1712]
thanks

**Comment by abhinavdangeti** [comment]
Here're a few steps:
* You can build a custom tokenizer using either an **exception** or a **regexp** to define rules on how to separate text.
* You'll then want to build a custom analyzer using this tokenizer and associate your field with this analyzer while indexing.
* While querying, if you use an analytic query like match or match_phrase and field scope the query - the analyzer you've defined for the field will automatically be applied to the search terms.

Here're all the tokenizers we support - https://github.com/blevesearch/bleve/tree/v2.3.3/analysis/tokenizer
Exception and Regexp are the only ones that are customizable.

There's several unit tests in https://github.com/blevesearch/bleve/blob/v2.3.3/index_test.go and https://github.com/blevesearch/bleve/blob/v2.3.3/search_test.go that could show you how.

Does this help?
