### ISSUE TITLE
How many terms in a Facet can Bleve "safely" handle?

### ISSUE THREAD

**Issue by jgschis** [blevesearch/bleve#1719]
Hi,

I am using Bleve (Couchbase FTS) to index about 20,000 to 30,000 documents (products) for ecommerce search and faceting.
There is a field in my documents called categories. This field is an array that contains all of the "categories" a product is in. At the moment, there are about 700 categories. An example document might look like: 

{
...
"categories ": ["Fashion", "Scarves"]
...
}

In my code, I ask Bleve to create a term facet on the _categories_ field. I then allocate each term returned by Bleve to a group (which I display on my website).  For example, the term "Scarves" would be allocated to the group "Fashion".
As there are currently 700 categories, I tell Bleve to return at most 700 terms in the facet.

So my question is,
Is there any danger in asking Bleve to return 700 terms in a facet? I have not noticed any issues. Also, what's the maximum number of terms in a facet that Bleve can handle?

I will also note that 99.99% of searches will probably only return at most 200 categories.

**Comment by abhinavdangeti** [comment]
There isn't a limit on the number of facets that can be handled.
You can do so by specifying the `size` in the `facets` attribute within the `SearchRequest`.
Needless to say, larger the number of categories reported by a query - more would be it's resource consumption.

**Comment by jgschis** [comment]
Thanks, do you know what number would be too high to be performant?

**Comment by abhinavdangeti** [comment]
@jgschis We've not tested an upper bound for facets size for me to share that number with you.

**Comment by jgschis** [comment]
OK, i will see how I go with my current design. I have other ideas on how to handle the categories if the facet size becomes an issue.

Thanks
