### ISSUE TITLE
Compilation failure on 2.3.3

### ISSUE THREAD

**Issue by agnivade** [blevesearch/bleve#1721]
Release 2.3.3 has a compilation failure which is fixed on master.

```
# github.com/blevesearch/bleve/v2/geo
../../go/pkg/mod/github.com/blevesearch/bleve/v2@v2.3.3/geo/geo_s2plugin_impl.go:392:39: cannot use radiusInMeter (variable of type float64) as type string in argument to geojson.NewGeoCircleShape
../../go/pkg/mod/github.com/blevesearch/bleve/v2@v2.3.3/geo/geo_s2plugin_impl.go:425:38: cannot use radius (variable of type float64) as type string in argument to geojson.NewGeoCircle
```

A new release needs to be cut.

**Comment by sreekanth-cb** [comment]
please refer - https://github.com/blevesearch/bleve/issues/1717

**Comment by agnivade** [comment]
https://github.com/blevesearch/bleve/issues/1717#issuecomment-1203826359 seems to be wrong. 2.3.3 does not work, that's why I created this. I think the issue should be open until a new release is cut.

**Comment by sreekanth-cb** [comment]
Just checked and it is working fine. The master is having this issue and not the latest release.
