### ISSUE TITLE
About 'indexAliasImpl' defined inside bleve/index_alias_impl.go

### ISSUE THREAD

**Issue by pprandive** [blevesearch/bleve#1723]
Hello,

There is a struct 'indexAliasImpl' defined inside subject mentioned file which has a local scope. Following is its definition:

type indexAliasImpl struct {
	name    string
	indexes []Index
	mutex   sync.RWMutex
	open    bool
}

Is there any specific reason behind making it locally scoped and not exporting it to outside? 
Checking it because, I needed to pass the alias object between multiple functions and since it is not exported, I couldn't define a function accepting this alias object as an argument.

Could you please let me know if there is a way to pass this index alias between function calls? That is, we create an index alias inside function foo() and it returns this object to it's caller which in turn calls another function bar() and sends this alias object as an argument.

Thanks and Regards,
Prafulla

**Comment by pprandive** [comment]
Is it that the bleve.Index should be used?

**Comment by abhinavdangeti** [comment]
Yes bleve.Index should be used.
