### ISSUE TITLE
Is there an API to repopulate the index after the document data has changed?

### ISSUE THREAD

**Issue by zhousy29** [blevesearch/bleve#1727]
Hi,  I went through the go API documentation and did not find handy APIs that could be used to repopulate the index after the document data has changed. right now, I delete the index directory and recreate the index DB.

What I'm expecting is if you could have something like  "index.clearAll()" or "index.empty()" .  
Or do you have better advice?

many thanks

**Comment by abhinavdangeti** [comment]
By repopulate - do you mean overwriting certain docs in your index with new content or simply purging current docs and adding newer docs (meaning current docs should not be searchable)?

If it's the latter - then what you're doing is the recommended approach.
If you're simply overwriting certain docs, you can do so on your current index. The existing docs will be marked as stale and replaced with newer content (the stale content is compacted out on a subsequent merge operation that puts together smaller segments into bigger segments).

**Comment by zhousy29** [comment]
thank you, abhinavdangeti.  Updating/Overwriting the current index is what I wanted.
I'll repeat doing this,  "index.Index(message.Id, message)", whenever the message content has changed.
I hope this is the right way to update certain docs.
