### ISSUE TITLE
Significant query throughput drop observed with v2.3.4

### ISSUE THREAD

**Issue by Thejas-bhat** [blevesearch/bleve#1731]
We introduced changes that intend to publish IO stats (read/write) for tracking system usage with [v2.3.4](https://github.com/blevesearch/bleve/releases/tag/v2.3.4).

- https://github.com/blevesearch/bleve/pull/1702
- https://github.com/blevesearch/bleve/pull/1710

For queries with high hit cardinality (order of 100K+ hits), we've observed a considerable query throughput drop in our in-house testing.

 ![image](https://user-images.githubusercontent.com/35959007/191663254-b3f96abd-bdff-4057-bf69-a7ff2906683d.png)

We are actively working on this issue to optimizing this stats calculation and perhaps even making this cost estimation on-demand to mitigate this regression.

The fix will be targeted for the v2.3.5 release.

**Comment by abhinavdangeti** [comment]
https://github.com/blevesearch/bleve/pull/1738
