### ISSUE TITLE
Please update cobra

### ISSUE THREAD

**Issue by MichaelMure** [blevesearch/bleve#1733]
The CLI tool in Bleve is using cobra-v0.0.5. This version, up to https://github.com/spf13/cobra/releases/tag/v1.4.0 is importing Viper, and with that comes a huge number of indirect dependencies: Etcd, systemd, protobuf, prometheus, websocket, GRPC ...

It'd be great for our collective sanity to avoid that.

**Comment by abhinavdangeti** [comment]
Targeting this for v2.3.5.
