### ISSUE TITLE
please support es query string，thanks

### ISSUE THREAD

**Issue by hktalent** [blevesearch/bleve#1737]
please support es query string，thanks
like：
/_search?q=domain: in "*gov.com*" and ip in *10.55.*

thanks

see:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html
<img width="802" alt="image" src="https://user-images.githubusercontent.com/18223385/194825734-f9c14b05-954b-44d9-b91d-ef2406eff80f.png">

**Comment by abhinavdangeti** [comment]
We do already support the query string syntax ..

```
{"query": "user.id:elkbee"}
```

You will be able to paginate results within bleve.SearchRequest.

Supporting a REST endpoint is something your application should handle. Is there something specific you're looking for?

**Comment by hktalent** [comment]
ok，thanks

**Comment by hktalent** [comment]
@abhinavdangeti 
In addition, I don't know if I have ever done a performance test for big data indexes, and I don't know how many T indexes the project program can support. I look forward to your reply.

**Comment by abhinavdangeti** [comment]
We don't have any hard limit on the number of indexes bleve/scorch can support. This would depend on the kind of hardware you bring to the table.

On Couchbase Search which extensively uses bleve/scorch - we've tested as many as 1000 indexes continuously receiving data in a distributed system. This number will vary based on the architecture/design of the application using the bleve/scorch indexes.
