### ISSUE TITLE
please support exclude html tags index，thanks

### ISSUE THREAD

**Issue by hktalent** [blevesearch/bleve#1742]
please support exclude html tags index，thanks

I need to store fragment html in my real application, but I want to index only the content outside the html tag, don't know how to achieve that

thanks

**Comment by PRO-BROS** [comment]
Thanks god I don't use these tags in my [site](https://prhocoding.com/)

**Comment by abhinavdangeti** [comment]
Using the html character filter (which internally uses a regexp-replace), bleve will NOT index any html tags - meaning html tags will **NOT** be searchable.

That said if you do "store" these fields' content to display field fragments while querying - the html tags will be retained there.

**Comment by hktalent** [comment]
ok, thanks
