### ISSUE TITLE
what happened? Dates are not properly filtered

### ISSUE THREAD

**Issue by hktalent** [blevesearch/bleve#1743]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/18223385/196627247-1f23ed6d-a4ed-4e87-9f21-73b174682346.png">

golang code
```
Date         *time.Time `json:"date"`
```

**Comment by abhinavdangeti** [comment]
A `query string` query like the one above in your example is internally translated into a boolean query - which has 3 components:

* A must clause - where all sub clauses MUST be satisfied - these are all clauses prefixed with a `+`
* A must_not clause - where all sub clauses MUST NOT be true - these are all clauses prefixed with a `-`
* A should clause - where all sub clauses CAN be true - these are those clauses that aren't prefixed with a `+` or `-`.

In your query string above, GHSL is the only search that is being enforced and the date is optional. If you'd like the date to NOT be optional, try ..
```
+date:>"2022-10-17" +GHSL
```

p.s. Make sure the date field is indexed as a datetime type.

**Comment by hktalent** [comment]
"p.s. Make sure the date field is indexed as a datetime type."
I know, thanks

**Comment by hktalent** [comment]
@abhinavdangeti Can dynamically change string date to date type date?
thanks
