### ISSUE TITLE
unrecognized import path "golang.org/x/text/unicode/norm"

### ISSUE THREAD

**Issue by cliguo** [blevesearch/bleve#175]
$ go get github.com/blevesearch/bleve
package github.com/blevesearch/bleve
        imports github.com/blevesearch/segment
        imports github.com/blevesearch/go-porterstemmer
        imports golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm"

**Comment by saljam** [comment]
What's in your $GOPATH/src/golang.org/x/text? Does `go get -u golang.org/x/text/unicode/norm` alone work?

**Comment by mschoch** [comment]
Closing this since we did not receive more information.  Please reopen if you'd like additional assistance on this @cliguo

**Comment by johnnynode** [comment]
It turned out:
```
me-Mac-pro:src gddev4$ go get -u golang.org/x/text/unicode/norm
# cd .; git clone https://go.googlesource.com/text /Users/../projects/go-projects/src/golang.org/x/text
Cloning into '/Users/../projects/go-projects/src/golang.org/x/text'...
fatal: unable to access 'https://go.googlesource.com/text/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/text/unicode/norm: exit status 128
```
