### ISSUE TITLE
Plural Stemmer for English

### ISSUE THREAD

**Issue by jgschis** [blevesearch/bleve#1750]
The snowball and porter stemmers are too aggressive for ecommerce. For example, the word dressing gets stemmed to dress. But dressing and dress are two different concepts and shouldn't be conflated. 

I think we need a stemmer that just reduces a plural to its singular form. The OpenSearch project recently added a stemmer that does this:
https://github.com/opensearch-project/OpenSearch/blob/main/modules/analysis-common/src/main/java/org/opensearch/analysis/common/EnglishPluralStemFilter.java

If no one else wants to do this, I will add this to Bleve...

**Comment by abhinavdangeti** [comment]
@jgschis Thanks for bringing this up.

We'd welcome a contribution from you. If not, we will look into this eventually.

**Comment by jgschis** [comment]
Yes I am doing it now...

**Comment by jgschis** [comment]
I have ported the code to go. This is the first time i have made a go program, so no sure if I've done this right

https://github.com/jgschis/pluralstem/blob/master/english/english.go

**Comment by jgschis** [comment]
HI,
I am now adding an "entry point" to the plural stemmer in Bleve. 

Should I

- Add my code to https://github.com/blevesearch/bleve/tree/master/analysis/token
- Add my code to https://github.com/blevesearch/bleve/tree/master/analysis/lang/en

**Comment by jgschis** [comment]
Feel free to add this to the bleve project 
https://github.com/jgschis/pluralstem

once done, i will make a pull request to add the entry point to this library to Bleve.

**Comment by jgschis** [comment]
Hi,

@abhinavdangeti 
What has to happen for my code to become part of bleve? I will do all the work, but could you please tell me what I have to do? I have already contributed to couchbase, so I know how to use gerrit.

**Comment by abhinavdangeti** [comment]
@jgschis Go ahead and raise a pull request adding your code to this project. 
There's instructions for it [here](https://github.com/blevesearch/bleve/blob/master/CONTRIBUTING.md).

**Comment by jgschis** [comment]
Hi,

I am not changing bleve yet. First I need to add my plural stemmer repository to   https://github.com/blevesearch. How do I do that? 

Once it's added, I will make a pull request to update bleve so that it calls the code in the pluralstem project.

**Comment by abhinavdangeti** [comment]
@jgschis I've ported your code in with this PR: https://github.com/blevesearch/bleve/pull/1808

**Comment by jgschis** [comment]
Thanks
