### ISSUE TITLE
How to count the same vocabulary common in several doc

### ISSUE THREAD

**Issue by hktalent** [blevesearch/bleve#1751]
Hello, I want to count some common keywords contained in 70%, or more than 60% of the articles, as Top hot words, I don’t know how to count and analyze, please help, thank you

@abhinavdangeti 
thanks

**Comment by hktalent** [comment]
In addition, some questions from the last consultation with you:
1. How to combine multiple indexes into one?
Of course their structures are different

2. There are a large number of numeric fields in the generated index and doc that have not been converted into int. I don’t know if there is a good way to adjust these old data in batches.

**Comment by abhinavdangeti** [comment]
I can't think of a straight forward approach to look into what the top hot words are at the moment. You could use the command line utility to look into the term dictionaries for each field - but like I said it isn't really the easiest way.

Pinging the team here for any other ideas (or perhaps something we could support in the future) .. @metonymic-smokey @Thejas-bhat @moshaad7.

> How to combine multiple indexes into one?
Of course their structures are different

A dynamic index definition will index all fields for you - automatically detecting text, numeric and boolean. You can explicitly index all the fields of your interest. In either situation - only documents which have non-null values for chosen fields will have their content indexed.

> There are a large number of numeric fields in the generated index and doc that have not been converted into int. I don’t know if there is a good way to adjust these old data in batches.

If the numbers are in text format in your JSON - you can simply index them as text, using the `keyword` analyzer (where the numbers are indexed as is). You can then run either match queries on them for point lookup. You can also run a term range query but you'd run into a situation where the numbers will be ordered lexicographically:
```
["1", "10", "2", "24", "3", ..]
```

So a term range over `+num:>="1" +num:<="10"` would only return `["1", "10"]`.

If you pad these numbers with sufficient number of `0`s before indexing them as a keyword, you will be able to adapt your query.
```
["00001", "00010", "00002", "00024", "00003", ..]
```
and then `+num:=>"00001" + num:<="000010"` will return `["00001", "00002", "00003", "00010"]`

**Comment by hktalent** [comment]
thank you very much

**Comment by hktalent** [comment]
Or it might be clearer if I put it this way
That is, I want to know which keywords appear most frequently in the index library, such as Top 1000
That is, the vocabulary of index decomposition

eg: 10 articles describe the vulnerabilities of weblogic
Then one of the frequently occurring words must have weblogic
Of course, I didn't know the term weblogic in advance.
It is hoped that there will be technical means to be able to count and analyze

**Comment by jgschis** [comment]
You could use facets?

Just do a search for all documents ,and create a facet on the keyword field. The fact result will then tell you the count of each keyword (or top 1000, whatever you want).

**Comment by hktalent** [comment]
thanks, i will try @jgschis
