### ISSUE TITLE
How to build indexes concurrently

### ISSUE THREAD

**Issue by hktalent** [blevesearch/bleve#1758]
How to build indexes concurrently
<img width="703" alt="image" src="https://user-images.githubusercontent.com/18223385/203296846-62c84aec-0e01-494a-bdd1-4196199b7210.png">
I checked the code above and found that a lock was added

When I actually use it, there are billions of data that need to be indexed

Multithreading is set, but it is still invalid. The speed of index building is very slow

Can you tell me the best practices?
@darren

**Comment by darren** [comment]
FWIW
1. have you used the batch api? 
https://github.com/blevesearch/bleve/blob/b954483a905ac8852cbba1076d90869e7678a0bc/index.go#L215-L216
2. try sharding your index

**Comment by hktalent** [comment]
@darren 
Can you tell me how to traverse the index efficiently?

I want to merge multiple indexes into one index

go blevExp.Copy2("cnnvd", "osint")
