### ISSUE TITLE
slow query

### ISSUE THREAD

**Issue by hktalent** [blevesearch/bleve#1768]
query slow,
If you use him as a search engine, there is still a lot of room for optimization
<img width="793" alt="image" src="https://user-images.githubusercontent.com/18223385/205882515-a1ca36f0-6ff2-442b-9fc5-efb84fb06209.png">

Suggest optimization

I don't know if there is a way to improve performance
Has nothing to do with the number of hits, or increase the cluster, distributed design

**Comment by hktalent** [comment]
Sorry, I want to optimize him:
1. The number of hit pagesize will be returned
2. Total count is no longer needed

Unfortunately I don't know how to do it, can you give me some examples?

**Comment by abhinavdangeti** [comment]
I'll need two pieces of information here ..

1. What is your index definition/mapping?
2. What does your UI translate that string (query) into?

**Comment by hktalent** [comment]
> I'll need two pieces of information here ..
> 
> 1. What is your index definition/mapping?
default from
https://github.com/blevesearch/bleve-explorer 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/18223385/206038242-c5786f64-f5db-4029-8c1d-f7bfbc866899.png">

> 2. What does your UI translate that string (query) into?
/indexes/osint/query?q=type:subdomain%20%2Bdomain:paypal.com&p=1

{"size":10,"from":0,"explain":true,"highlight":{},"query":{"boost":1,"query":"type:subdomain +domain:*paypal.com"},"fields":["*"]}
<img width="858" alt="image" src="https://user-images.githubusercontent.com/18223385/206039464-4a78518b-f401-4bc0-85c9-9a5debf2f14a.png">

**Comment by hktalent** [comment]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/18223385/206324611-5d652bdf-904b-4aa3-b067-8db81cdc87ef.png">
