### ISSUE TITLE
Writing many single records sequentially (no bulking)

### ISSUE THREAD

**Issue by imirzadeh** [blevesearch/bleve#1783]
Hi, 

I'm using Bleve (v.2.3.6) for my project and where the incoming documents come in streaming fashion. So I use the default/single document indexing rather than bulk/batch indexing.  In other words, I call this function many times:
```go
func IndexDocument(d SearchDocument) error {
	indexName := bleveIndexName(d.UserID)
	index, err := GetOrCreateIndex(indexName)
	defer index.Close()
	if err != nil {
		return err
	}
	// add to index
	err = index.Index(d.ID, d)
	if err != nil {
		return err
	}
	return nil
}
```

Under heavy load, I get many errors like the one below:
```
unable to load snapshot, failed to load segment: error opening bolt segment: open index/store/0000000000c0.zap: too many open files, continuing
```

Is there a way (e.g., some option/config for persisting/merging) that I can use to prevent this issue? 
Performance is not an issue for my use case. All I'm looking for is to similar to writing records to a DB one-by-one, I index my documents one-by-one. 

Unfortunately, I couldn't find any code/documentations on this issue.

**Comment by abhinavdangeti** [comment]
@imirzadeh this pattern would certainly introduce a lot more file segments into disk as opposed to batched writes. I would highly recommend batching your writes. For example, couchbase adds to bleve indexes batches of sizes varying anywhere between 1-200 documents.

This said if you simply cannot implement a batching mechanism, you could look into tightening the merger policy to merge files more aggressively. You'll want to either set `scorchMergePlanOptions` in your scorch options **or** more simply update `(index.scorch.mergeplan).DefaultMergePlanOptions`. You will also likely need to experiment a bit in trying to achieve a good spot for your use case.

You can start by overwriting the default settings to these -
```
DefaultMergePlanOptions = MergePlanOptions{
	MaxSegmentsPerTier:   5,
	MaxSegmentSize:       2000000,
	TierGrowth:           10.0,
	SegmentsPerMergeTask: 10,
	FloorSegmentSize:     2000,
	ReclaimDeletesWeight: 3.0,
}
```
Check out the commentary here to understand more about these options - https://github.com/blevesearch/bleve/blob/master/index/scorch/mergeplan/merge_plan.go#L68...L98

**Comment by imirzadeh** [comment]
@abhinavdangeti 

Thank you for the answer. The merge plan option seems promising!
How can I pass scorch options (including merge plan) in my code? The `Index.New()/NewUsing()` does not accept any related argument. 

Sorry that I'm not familiar enough with bleve. If you are aware of a code/lib sample that is using these options, please let me know so I can read it and figure it out.

**Comment by abhinavdangeti** [comment]
Yes, you'llneed to use `NewUsing(..)` and set these values into `kvConfig`.
If you're not setting anything else in it - here's how the call to `NewUsing(..)` could look ..

```
idx, err := bleve.NewUsing("<path>", "<index_mapping>", "scorch", "",
    map[string]interface{}{
        "scorchMergePlanOptions": {
             "maxSegmentsPerTier": 5,
             "maxSegmentSize": 2000000,
             "tierGrowth": 10.0,
             "segmentsPerMergeTask": 10,
             "floorSegmentSize": 2000,
             "reclaimDeletesWeight": 3.0,
        },
    })
```

**Comment by imirzadeh** [comment]
I tried very hard to make this work by using different configs/parameters for the merge plan. But I still run into issues. 

But thank you for your help anyway :)
