### ISSUE TITLE
SkipFreqNorm scoring issue

### ISSUE THREAD

**Issue by akirabbq** [blevesearch/bleve#1786]
Hi! If an index is created on disk by using batch.New(), and if any of the field mappings set SkipFreqNorm=true, all the result hits will return NaN scores if any SkipFreqNorm=true fields are involved in the query. 

If the same index is created using in-mem only, the score will have normal values. Any idea? Thank you.

**Comment by abhinavdangeti** [comment]
Hi @akirabbq, this optimization of skipping indexing the frequency and norm values has been put in place only for the `scorch` indexType - which is our default format for bleve indexes. It is not applicable to `upside_down` (which is our older, deprecated index format). 

Currently, the in-memory only index uses the `upside_down` index format - reason why you don't see the optimization you call out.
