### ISSUE TITLE
the scorch memory usage is too large and the final program is blocked

### ISSUE THREAD

**Issue by bufsnake** [blevesearch/bleve#1787]
Insert 6 million pieces of data, the memory usage is normal when inserting for the first time, when inserting the same 6 million pieces of data again, the memory usage exceeds 10G, and finally the program blocks.

![image](https://user-images.githubusercontent.com/46959268/218289982-ff158fe7-7dcf-4a9e-bc2f-e8549bc812c2.png)

**Comment by iredmail** [comment]
Excuse me, what does "inserting the same ... data again" mean?
If you can offer a minimal working code sample, it will be easier for developers to reproduce the issue and eventually fix it.

**Comment by bufsnake** [comment]
After the first full insertion is complete, it is inserted again.

**Comment by bufsnake** [comment]
The insertion code is as follows.

```go
func (b *BleveSearch) CreateData(name string, data []Data) error {
	if _, ok := b.indexes[name]; !ok {
		return fmt.Errorf("%s index not exist", name)
	}
	batchAdd := b.indexes[name].NewBatch()
	for i := 0; i < len(data); i++ {
		if err := batchAdd.Index(data[i].GetId(), data[i]); err != nil {
			return err
		}
	}
	return b.indexes[name].Batch(batchAdd)
}
```

**Comment by abhinavdangeti** [comment]
@bufsnake what's your typical batch size?

While the recommendation is to not insert 1 document per batch or simply index 1 document at a time, I'd also recommend to cap the number of documents going into each batch before indexing it. If it helps any, Couchbase (which extensively uses scorch for it's search application) caps maximum batch size to about 200.

**Comment by bufsnake** [comment]
> @bufsnake what's your typical batch size?
> 
> While the recommendation is to not insert 1 document per batch or simply index 1 document at a time, I'd also recommend to cap the number of documents going into each batch before indexing it. If it helps any, Couchbase (which extensively uses scorch for it's search application) caps maximum batch size to about 200.

Currently inserting 300 documents each time.

**Comment by bufsnake** [comment]
@abhinavdangeti

Currently inserting 300 documents each time.

**Comment by bufsnake** [comment]
After the index exceeds 500G, it will become blocked and need to be stored in separate nodes.
