### ISSUE TITLE
Possible unbounded memory consumption crash when "*" is used in QueryStringQuery

### ISSUE THREAD

**Issue by rasteric** [blevesearch/bleve#1796]
I have about 300,000 documents indexed and my application works fine for all normal queries. The index is using scorch with boltdb. Memory consumption is low, 200-300 MB. Whenever I enter `*` or query strings with a wildcard at the start such as `*.mp3,` where the latter ought to match a relatively small number of document names only, Bleve memory consumption jumps through the roof: 4 GB, 4.5 GB, 5 GB, and so on, until the whole system memory of 32GB is reached and the system starts to swap. This seems to happen after the search has finished and is independent of the number of hits reported. It's as if there is some kind of loop in a goroutine with a memory leak triggered by the wildcard in the query. 

I know the memory leak is not in the rest of my application since it already uses an sql search with LIKE statements and these do not create any problems if the same number or more hits are returned.

Here is the search code I use:

	query := bleve.NewQueryStringQuery(term)
	search := bleve.NewSearchRequest(query)
	searchResult, err := prj.index.Search(search)
	if err != nil {
		return nil, err
	}
	results := make(map[Project][]Asset)
	for _, val := range searchResult.Hits {
          // doing something with the results
       }

Indexing uses the default analyzer and structs:

	// example of indexing, first map from struct, then index struct (control.index) is a bleve indexer
      	id := a.CombinedID(control, p)
	idx.Name = a.Name(control, p)
	idx.Sort = a.Sort(control, p)
	idx.XID = a.xidString(control, p)
	idx.Path = a.Path(control, p)
	idx.Mime = a.MIME(control, p)
	idx.Info = a.Info(control, p)
	idx.Tags = a.Tags(control, p)
	idx.Version = a.Version(control, p)
	idx.Plan = a.Plan(control, p)
	idx.Created = a.CreatedAt(control, p)
	idx.Updated = a.UpdatedAt(control, p)
	idx.Modified = a.FileModificationDate(control, p)
	a.setLastIndexed(control, p, time.Now())
	return control.index.Index(id, idx)

        // example of the struct used:
        type AssetIndex struct {
	    Name     string    `json:"name"`
	    Project  string    `json:"project"`
	    Sort     int       `json:"sort"`
	    XID      string    `json:"xid"`
	    Path     string    `json:"path"`
	    Mime     string    `json:"mimetype"`
	    Info     string    `json:"info"`
	    Tags     string    `json:"tags"`
	    Version  string    `json:"version"`
	    Plan     string    `json:"plan"`
	    Created  time.Time `json:"created"`
	    Updated  time.Time `json:"updated"`
	    Modified time.Time `json:"modified"`
	   Content  string    `json:"content"`
	   Meta     string    `json:"meta"`
        }

**Comment by Thejas-bhat** [comment]
Hi @rasteric, is it possible to get a memory profile (using pprof) on this issue?

https://pkg.go.dev/runtime/pprof#hdr-Profiling_a_Go_program

**Comment by rasteric** [comment]
My apologies, I was under time pressure and have switched to FTS5 already. I suggest you close the issue if you cannot repeat it in your setup/examples.

**Comment by kichik** [comment]
I am also seeing very similar results when searching for `*`. I have attached memory and CPU profile dump from this simple test:

```
package main

import (
	"github.com/blevesearch/bleve/v2"
	"log"
	"testing"
)

func TestHighRamUsage(t *testing.T) {
	index, err := bleve.Open("index.bleve")
	if err != nil {
		log.Fatal(err)
	}

	request := bleve.NewSearchRequest(bleve.NewWildcardQuery("*"))
	request.Size = 100
	request.Fields = []string{"*"}
	results, err := index.Search(request)
}
```

The index on disk is less than 1GB and uses zap v15 (all defaults, bleve 2.4.0, go 1.22).

For me this happens during the search and not after. Once the search is done, I can see system allocated memory going down very slowly as the GC does its job.

[pprof.tar.gz](https://github.com/blevesearch/bleve/files/15017140/pprof.tar.gz)

**Comment by kichik** [comment]
@Thejas-bhat are there any other details I could add that would help track this down?
