### ISSUE TITLE
bleve.Batch.String() API for debuggability?

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#180]
I had an app that gets an error executing a Batch (apparently due to some underlying KVStore issue), so was I looking for a way to dump out all the docs in the batch (perhaps app can log them or display in UI) and narrow down the problematic doc.

So, perhaps an additional Batch.String() method would be helpful for diagnosability, but allow for information hiding (no need to allow access to internals of Batch implementation).

**Comment by mschoch** [comment]
I've put together a version which will print ops and keys.  Including the fields values will make the output extremely verbose.  Here is a sample of what it looks like now:

```
Batch (2 ops, 2 internal ops)
	INDEX - 'a'
	DELETE - 'b'
	INDEX INTERNAL - 'c'
	DELETE INTERNAL - 'd'
```

Please reopen if you really need the field values as well.
