### ISSUE TITLE
question: How to reduce the memory used?

### ISSUE THREAD

**Issue by springrain** [blevesearch/bleve#1809]
I want to reduce memory and io usage, is it okay if I set it this way? What should be done?

```go
bleve.Config.DefaultMemKVStore = scorch.Name
bleve.Config.DefaultKVStore = scorch.Name
```

Because bleve can only have one write handle, I opened it and did not close it, sharing use, resulting in high memory and io , how should I solve it?

**Comment by abhinavdangeti** [comment]
There's no setting the KV store with bleve's scorch engine. Bbolt is automatically used for metadata storage.

You can set memory limit in your application that uses bleve to limit memory consumption this way - https://pkg.go.dev/runtime/debug#SetMemoryLimit
