### ISSUE TITLE
Divided by zero error was never fixed or has come back

### ISSUE THREAD

**Issue by camsn0w** [blevesearch/bleve#1811]
I noticed that my program was crashing with a fatal divide by zero error and I happened to come across: https://github.com/blevesearch/bleve/issues/1606 I saw it was marked as solved however the stacktrace was identical and the stated fix of setting "SearchRequest.Score = "none" SearchRequest.Highlight = nil" worked to fix the issue

**Comment by jgschis** [comment]
So is there a fix for this, as I am noticing this as well in Couchbase 7.1.3?
