### ISSUE TITLE
How to retrieve documents with ID

### ISSUE THREAD

**Issue by the42** [blevesearch/bleve#1821]
In a former version of bleve there used to be

d, err := bleve.Document(id)

but this doesn't expose any means to retrieve the fields. So instead I do

	qry := bleve.NewTermQuery(id)
	qry.SetField("_id")
	req := bleve.NewSearchRequest(qry)

	req.Fields = []string{"*"}
	result, err := index.Search(req)

However this doesn't return any search results. How can I perform a search with the document id?

**Comment by abhinavdangeti** [comment]
Would `NewDocIDQuery` not work for you?

https://github.com/blevesearch/bleve/blob/ec1a82f09b429573363375e0be68f8a923ba716b/query.go#L73-L78

**Comment by the42** [comment]
Yes, I tried

	qry1 :=bleve.NewDocIDQuery([]string {id})
	req1 := bleve.NewSearchRequest(qry1)
	res1, err := index.Search(req1)

but res1.Hits has always been zero. Btw. I am inserting records like

	batch.Index(id, wortlaut)


As this all didn't work out I defined a custom id field on my data to index with keywordmapping

	keywordmapping := bleve.NewKeywordFieldMapping()
	wortlautdocumentmapping.AddFieldMappingsAt("id", keywordmapping)

and now I am searching like

	qry := bleve.NewQueryStringQuery(fmt.Sprintf("id:%s", id))
	req := bleve.NewSearchRequest(qry)
	result, err := model.thindex.Search(req)

which works. An ugly and probably not so performant hack, but that works.

**Comment by abhinavdangeti** [comment]
I'm surprised the DocIDQuery doesn't work for you. Would you be willing to share an entire sample program that reproduces the situation?

You mention that after indexing the field separately as `id` and tried -
```
qry :=bleve.NewTermQuery(id)
req := bleve.NewSearchRequest(qry)
result, err := index.Search(req)
```

.. didn't work. I believe you missed this step ..
```
qry.SetField("id")
```

.. which is what the query-string query example you shared above does.

**Comment by the42** [comment]
I updated from bleve 2.3.7. to bleve 2.3.8 and now everything works.

For the record, these three queries now all return the same result:

		docqry := bleve.NewDocIDQuery([]string{docid})
		docreq := bleve.NewSearchRequest(docqry)
		docreq.Fields = []string{"*"}
		result, err = index.Search(docreq)
		if err != nil {
			panic(err)
		}
		fmt.Println("DocIDQuery Results: ", docres.Total)

		termqry := bleve.NewTermQuery(docid)
		termqry.SetField("id")
		termreq := bleve.NewSearchRequest(termqry)
		termreq.Fields = []string{"*"}
		result, err = index.Search(termreq)
		if err != nil {
			panic(err)
		}
		fmt.Println("TermQuery Results: ", termres.Status.Total)

		qry := bleve.NewQueryStringQuery(fmt.Sprintf("id:%s", docid))
		req := bleve.NewSearchRequest(qry)

		req.Fields = []string{"*"}
		result, err = index.Search(req)
		if err != nil {
			log.ErrorCtx(ctx, err.Error())
			return nil, err
		}
