### ISSUE TITLE
Field Analyzer Not Getting Used

### ISSUE THREAD

**Issue by hacdias** [blevesearch/bleve#1835]
Hey, I am _really_ trying to use Bleve, but I'm struggling to find documentation about this. I want to index documents with two fields: "title" and "content". For "title", I want to use a custom analyzer that includes stop words for better matches. However, it doesn't seem to work:

```golang
mapping := bleve.NewIndexMapping()
err := mapping.AddCustomAnalyzer("en-with-stop-words", map[string]interface{}{
	"type":      custom.Name,
	"tokenizer": unicode.Name,
	"token_filters": []string{
		en.PossessiveName,
		lowercase.Name,
		porter.Name,
	},
})
if err != nil {
	return err
}

titleField := bleve.NewTextFieldMapping()
titleField.Analyzer = "en-with-stop-words"

contentField := bleve.NewTextFieldMapping()
contentField.Analyzer = "en"

page := bleve.NewDocumentStaticMapping()
page.AddFieldMappingsAt("title", titleField)
page.AddFieldMappingsAt("content", contentField)

mapping.DefaultMapping = page

index, err := bleve.NewMemOnly(mapping)
if err != nil {
	return fmt.Errorf("could not create index: %w", err)
}

err = index.Index("test", map[string]interface{}{
	"title":   "About",
	"content": "Lorem ipsum sin dolor amet and some stop words too like about",
})
if err != nil {
	return fmt.Errorf("could not add to index: %w", err)
}

res, err := index.Search(bleve.NewSearchRequest(bleve.NewQueryStringQuery("about")))
if err != nil {
	return fmt.Errorf("could not search in index: %w", err)
}

fmt.Println(res.Hits.Len())
```

Oddly enough, if I add `page.DefaultMapping = "en-with-stop-words"` it starts working. If I add `page.DefaultMapping = "en"`, it doesn't. But this doesn't seem to make sense. It should use the `Analyzer` of each field, no?

Maybe it's a bug, or I'm doing something completely wrong. Can anyone give some direction on this? Thanks 😄

**Comment by Thejas-bhat** [comment]
it's mostly due to the fact that by default the query hits a "_all" field whose default analyzer is standard (i think). if you want to redirect the query to the title field you could use `NewQueryStringQuery("title:about")`

**Comment by hacdias** [comment]
@Thejas-bhat thanks. That seems to work. Thanks. Is there a way that I can search in both fields at once, ignoring the stop words for one and not for the other?

**Comment by Thejas-bhat** [comment]
the thing is that every searchable field is assigned a single analyzer (and two different searchable field could have same analyzer). so, i don't think its possible to achieve it using a single field. what can be done is to have a disjunction query where one sub-query queries upon the title field and the other sub-query on the content field. the final result set is union of the two sub-queries' result sets.

**Comment by Thejas-bhat** [comment]
within a single QueryString query you could use this format "title:termA title:termB". otherwise, you can also use a match query which accepts the field value as an argument. something like this:

```
mQ := NewMatchQuery("term1 term2 term3")
mQ.SetField("title")
```
that way all the entire match query will be directed to the title field.

PhraseQuery is a bit different in the sense that you get documents having the text "term1 term2 term3" in that exact order, but in the above match query it's more like a disjunction query, any document having atleast one of those three terms and in any order.

**Comment by hacdias** [comment]
@Thejas-bhat thanks for all the help 😄 It works well like that!
