### ISSUE TITLE
What did I do wrong with the GeoShape index

### ISSUE THREAD

**Issue by fakegis** [blevesearch/bleve#1839]
the code is as follows（bleve version:2.3.8）:
```
        fm := mapping.NewGeoShapeFieldMapping()
	dmap := mapping.NewDocumentMapping()
	dmap.AddFieldMappingsAt("GeoShape", fm)

	idxMapping := bleve.NewIndexMapping()
	idxMapping.DefaultMapping = dmap

	index, _ := bleve.NewMemOnly(idxMapping)
	defer index.Close()

	type GeoShape struct {
		Type        string      `json:"type"`
		Coordinates [][]float64 `json:"coordinates"`
	}
	doc := struct {
		Info     string   `json:"info"`
		GeoShape GeoShape `json:"GeoShape"`
	}{
		Info: "bleve test",
		GeoShape: GeoShape{
			Type:        "linestring",
			Coordinates: [][]float64{{0, 0}, {0.000001, 0}},
		},
	}

	index.Index("doc1", doc)
	rdoc, err := index.Document("doc1")
	if err != nil {
		t.Fatal(err)
	}

	fmt.Println(rdoc.(*document.Document).GoString())

	geoQuery := query.NewGeoDistanceQuery(0, 0, "10km")
	geoQuery.SetField("GeoShape")
	req := bleve.NewSearchRequest(geoQuery)
	res, err := index.Search(req)
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println(res)
       //Print: No matches
```

It seems that the `geoshape` index was not built correctly. I have tried many methods, using geojson point，unable to obtain correct results too .
`GeoShape{
Type: "point",
Coordinates: []float64 [0,0],
}`

What should I do? This is important to me. Thanks

**Comment by fakegis** [comment]
> 您只能在一个字段上运行。此外，如果您认为该字段未按预期编制索引，则可以使用格式设置。试试这个地理形状查询，它执行与地理距离查询相同的操作 -`GeoShapeQuery``geoshape`
> 
> ```
> 	fm := mapping.NewGeoShapeFieldMapping()
> 	dmap := NewDocumentMapping()
> 	dmap.AddFieldMappingsAt("GeoShape", fm)
> 
> 	idxMapping := NewIndexMapping()
> 	idxMapping.DefaultMapping = dmap
> 
> 	index, _ := NewMemOnly(idxMapping)
> 	defer index.Close()
> 
> 	docBytes := []byte(`
> 		{"info":"bleve test","GeoShape":{"type":"linestring","coordinates":[[0,0],[0.000001,0]]}}
> 	`)
> 	var docMap map[string]interface{}
> 	if err := json.Unmarshal(docBytes, &docMap); err != nil {
> 		fmt.Println(err)
> 		return
> 	}
> 
> 	index.Index("doc1", docMap)
> 
> 	geoQuery, err := query.NewGeoShapeCircleQuery([]float64{0, 0}, "10km", "within")
> 	if err != nil {
> 		fmt.Println(err)
> 		return
> 	}
> 	geoQuery.SetField("GeoShape")
> 	req := NewSearchRequest(geoQuery)
> 	res, err := index.Search(req)
> 	if err != nil {
> 		fmt.Println(err)
> 		return
> 	}
> 	fmt.Println(res)
> ```

Thank you, these have solved my problem.

**Comment by fakegis** [comment]
After testing, using `query. NewGeoShapeCircleQuery ([] float64 {0, 0}, "10km", "within") `can obtain correct results, but using `query. NewGeoDistanceQuery (0, 0, "10km") `cannot obtain results. What is the difference between these two functions, depending on the indexing method (Google s2/geohash) or geo type (point/linestring)?

**Comment by metonymic-smokey** [comment]
@fakegis Geoshape query uses spherical geodesics, unlike the Geodistance query. 
According to [this blog](https://www.couchbase.com/blog/advanced-geospatial-support-added-to-search-service/), it has the following implication - 
"The Search service uses geodesics or spherical geometry to support the advanced spatial features. That means the curvature of earth’s surface is taken into account while performing spatial filters. "

**Comment by fakegis** [comment]
> @fakegis Geoshape query uses spherical geodesics, unlike the Geodistance query. According to [this blog](https://www.couchbase.com/blog/advanced-geospatial-support-added-to-search-service/), it has the following implication - "The Search service uses geodesics or spherical geometry to support the advanced spatial features. That means the curvature of earth’s surface is taken into account while performing spatial filters. "

Thank you, I think my problem has been resolved.
