### ISSUE TITLE
website https://www.blevesearch.com is messy due to invalid(?) ssl cert

### ISSUE THREAD

**Issue by iredmail** [blevesearch/bleve#1846]
Just visit https://www.blevesearch.com and you should understand what i mean. :)
Is ssl cert for www.blevesearch.com (NOT "blevesearch.com") invalid now?

**Comment by mousedownmike** [comment]
I can confirm that I'm seeing similar issue as @iredmail, I've actually been seeing it for a few weeks and keep forgetting to open an issue.  

Steps to reproduce:

OS: Ubuntu 22:04
Browser: Firefox 115

1. Enter **www.blevesearch.com** in browser bar and hit enter.
2. **Observe** 
  *  301 redirect to blevesearch.com
  * Unformatted HTML Presented
  * Asset requests blocked with `SSL_ERROR_BAD_CERT_DOMAIN`

![www redirect](https://github.com/blevesearch/bleve/assets/47116171/8f16f857-9b3a-4575-9b95-944c7a1dec7c)


1. Enter **https://www.blevesearch.com** in browser and hit enter. 
2. **Observe**
  * Browser security warning
  * Certificate supplied appears to be for a github.com domain.

![https](https://github.com/blevesearch/bleve/assets/47116171/3223d5de-75dd-4830-a5a9-667b608ed137)

**Comment by mousedownmike** [comment]
I get something similar in Safari on iOS:
![image](https://github.com/blevesearch/bleve/assets/47116171/06398ca3-567e-4aab-b824-02394c057726)

**Comment by abhinavdangeti** [comment]
Believe we've addressed it now.
https://blevesearch.com should work now and https://www.blevesearch.com should redirect to https://blevesearch.com.

**Comment by mousedownmike** [comment]
:heavy_check_mark: https://blevesearch.com works.

:heavy_check_mark: http://blevesearch.com  works (shows 'connection is not secure' in toolbar)

:heavy_check_mark: http://www.blevesearch.com works, redirects to http://blevesearch.com (see above)

:x: https://www.blevesearch.com **does not** work, it presents the security risk warnings notable:

> The certificate is only valid for the following names: *.github.io, github.io, *.github.com, github.com, www.github.com, *.githubusercontent.com, githubusercontent.com
