### ISSUE TITLE
Japanese analyzer slow to open

### ISSUE THREAD

**Issue by chowey** [blevesearch/bleve#187]
I have a body of translated Japanese text. I used the `analysis/language/ja` analyzer for this index. I am not too concerned about the indexing time. However, once I have indexed it, my machine takes a really long time to re-open the index for use.

For clarity, I am timing the following command:

```
index, err = bleve.Open(name)
```

Here are some figures:

* (using "ja" analyzer) 28.4s to open
* (using "cjk" analyzer) 116.7ms to open
* (on the original english text, using "en" analyzer) 168.2ms to open

Is that expected behavior?

**Comment by mschoch** [comment]
I think there are 2 potential issues:

1.  Opening the index is usually a function of how many rows are in the underlying kv store.
2.  I belive the kagome package used by the "ja" analyzer also loads some static dictionaries into memory.

I would expect the time from 2 above to be in an init() method though and not in Open() so double check where the time is being spent.  If you confirm its definitely coming from Open() then we should compare how many rows are in the KV stores when using the various analyzers.

**Comment by chowey** [comment]
You are correct that the kagome package loads some static dictionaries, and that is what takes so long. The line is [here](https://github.com/ikawaha/kagome/blob/master/dic.go#L55) (the `initSysDic.Do`):

```
// NewSysDic returns the kagome system dictionary.
func NewSysDic() (dic *Dic) {
	initSysDic.Do(func() { sysDic = loadSysDic() })
	return sysDic
}
```

I timed that exact line. It is definitely what causes the long load time. Obviously it only runs once the first time it is used. But it is not done in an init() func, which is why it appears to take so long on Open().

This is not an issue with bleve itself but with kagome, so I'm closing this issue.

**Comment by mschoch** [comment]
Thanks, I'm going to re-open the issue temporarily.  It's still odd to me that it happens during Open().  I'd like to better understand that before closing it out.

**Comment by chowey** [comment]
For what its worth, kagome takes only 2.5s to load on a linux box, compared to the 25s it takes on my Mac box.

**Comment by chowey** [comment]
Figured it out - someone had added `-race` to the run script, to test for race conditions. This had a severe performance impact on kagome.

So:
* it was about 25s to run `bleve.Open()` on a Japanese index using kagome with `-race` enabled
* it was about 2.5s to run `bleve.Open()` on a Japanese index using kagome without `-race` enabled
* it was about 150ms to run `bleve.Open()` on a similarly-sized English index with `-race` enabled
* it was about 35ms to run `bleve.Open()` on a similarly-sized English index without `-race` enabled

The difference between 2.5s (kagome) and 35ms (en) is still substantial, but I can live with that.

**Comment by mschoch** [comment]
Thanks for tracking all this down.  I now see why the time ends up being spent as a part of Open().  I can see a way that we could allow the application to load the dictionary earlier, and then we could use that instead of creating a new one inside of Open().  For most applications this probably doesn't change much as you probably open the index near the beginning anyway.  But in some really advanced cases I could see a benefit.  I'm going to leave it the way it is for now unless you think it would help a lot.
