### ISSUE TITLE
github.com/blevesearch/bleve/v2/http/search.go bug?

### ISSUE THREAD

**Issue by hktalent** [blevesearch/bleve#1873]
github.com/blevesearch/bleve/v2/http/search.go bug?
No ctx is passed in, when the network times out, or the client cancels the request, the query is not terminated gracefully
https://github.com/blevesearch/bleve/blob/6c3999222a52e2281f01fb64181096efc2ef1a98/http/search.go#L84

change to :
```
	// execute the query
	searchResponse, err := index.SearchInContext(req.Context(),&searchRequest)
```

**Comment by Likith101** [comment]
Added the option of giving the timeout as part of the request which will then be passed on to the search function. The case of client cancelling a request does not make much sense in a http handler function and so hasn't been added.
