### ISSUE TITLE
Current `bleve` release broken by more recent change?

### ISSUE THREAD

**Issue by bmhatfield** [blevesearch/bleve#1879]
```
go/pkg/mod/github.com/blevesearch/bleve/v2@v2.3.9/search/searcher/search_geoshape.go:107:32: not enough arguments in call to geojson.FilterGeoShapesOnRelation
	have (index.GeoJSON, []byte, string, **bytes.Reader)
	want (index.GeoJSON, []byte, string, **bytes.Reader, *s2.GeoBufferPool)
```

Seems to have been changed in https://github.com/blevesearch/bleve/pull/1864 but `go get -u github.com/blevesearch/bleve/v2` brings it in, it seems?

**Comment by bmhatfield** [comment]
Forcibly rolling that back in `go.mod` results in more breaking changes:

```
go/pkg/mod/github.com/blevesearch/bleve/v2@v2.3.9/index_impl.go:651:26: assignment mismatch: 2 variables but docF.DateTime returns 3 values
```

which appears to be the result of an update to github.com/blevesearch/bleve_index_api v1.0.6

**Comment by bmhatfield** [comment]
Jason in the Gophers Slack helped point me in the right direction; `-u` caused a dependency update overfetch.

<img width="302" alt="Screenshot 2023-09-06 at 9 50 49 PM" src="https://github.com/blevesearch/bleve/assets/1119967/812fb415-304e-4e26-91cb-24e9ed8d0cb9">

That said, it's probably worth cutting a Bleve release given the breaking changes in supporting libraries.

**Comment by bmhatfield** [comment]
Going to leave open as a request to cut a new release; feel free to close as desired.

**Comment by abhinavdangeti** [comment]
@bmhatfield we'll be making a release later in this month.
