### ISSUE TITLE
can not search bool fields

### ISSUE THREAD

**Issue by hktalent** [blevesearch/bleve#1889]
can not search bool fields?

```
github.com/blevesearch/bleve/v2 v2.3.10
github.com/blevesearch/bleve_index_api v1.0.6
```

<img width="443" alt="image" src="https://github.com/blevesearch/bleve/assets/18223385/db832f66-ad71-4ff6-806f-7e446390e899">

<img width="377" alt="image" src="https://github.com/blevesearch/bleve/assets/18223385/dd809126-5d4c-4cdc-bcdd-91eac8b499d5">

<img width="343" alt="image" src="https://github.com/blevesearch/bleve/assets/18223385/c9388492-d17a-4f6e-bc98-1d29f14b5ece">
<img width="299" alt="image" src="https://github.com/blevesearch/bleve/assets/18223385/1d4d619d-6085-4295-9c35-8f3f63dc6e88">
<img width="291" alt="image" src="https://github.com/blevesearch/bleve/assets/18223385/d79cabea-332f-4ed2-9a62-e159f2e5aff7">

I refer to
http://blevesearch.com/docs/Query-String-Query/
No answer found

**Comment by Likith101** [comment]
Searching boolean fields is not supported using Query String queries.
