### ISSUE TITLE
Possible memory leak in index/store/forestdb/iterator.go

### ISSUE THREAD

**Issue by tleyden** [blevesearch/bleve#194]
I've recently discovered that if a doc returned from calling iterator.Get() is not explicitly closed, it can result in memory leak -- see [google groups thread](https://groups.google.com/d/msg/forestdb/k8jcxvH5mOM/N_ORp2AsFrQJ)

Reading over the code in index/store/forestdb/iterator.go, it's not obvious to me that this resource leak is avoided, since there is never an explicit call to doc.Close().  From my observations, even if the reference to the Go wrapper doc is GC'd, the underlying cgo memory won't be released.

I haven't observed any bugs while using bleve, this was just from reading index/store/forestdb/iterator.go, so there's a good chance it's not really a bug.

**Comment by mschoch** [comment]
Yes this looks like a bug.

**Comment by tleyden** [comment]
Related (closed) issue for secondary indexing: https://issues.couchbase.com/browse/MB-14701
