### ISSUE TITLE
Configuration for only in-memory storage

### ISSUE THREAD

**Issue by said1296** [blevesearch/bleve#1947]
Hi! Is there a way to configure bleve to keep all documents in-memory so that querying is as fast as possible? I won't be storing more than 500 documents at a time.

I guess I have to set bleve.Config.DefaultKVStore to some value.

Thanks for the help.

**Comment by Thejas-bhat** [comment]
You can use NewUsing() API https://github.com/blevesearch/bleve/blob/c8e3daf115aee56897e841aee9ddc9dfa78ba5d6/index.go#L280 with DefaultKVStore and pass a map with the key value pair of "unsafe_batch": true in it.

**Comment by abhinavdangeti** [comment]
@said1296 Perhaps you should look into - NewMemOnly(..) ..

https://github.com/blevesearch/bleve/blob/v2.3.10/index.go#L261...L268
