### ISSUE TITLE
How can I use the Vector Search feature?

### ISSUE THREAD

**Issue by luigibarbato** [blevesearch/bleve#1963]
Hi guys! first of all, thank you for your effort for this awesome project. I noticed that with the latest pull requests you have introduced vector search, a feature that I can't seem to use. Is it not ready yet? If yes, how can I use it? 
 
 Thanks :)

**Comment by abhinavdangeti** [comment]
https://github.com/blevesearch/bleve/releases/tag/v2.4.0
