### ISSUE TITLE
Handling a field whose value may be a different language?

### ISSUE THREAD

**Issue by Nickersoft** [blevesearch/bleve#1969]
Hey folks,

I've been struggling to navigate the documentation and was wondering if anyone could shed light onto whether the following is possible / what approach I could take:

I currently have a table with a column whose values contain a variety of languages. The language of this field is stored in a separate field, so I know what the language is. Is it feasible to have the field's analyzer be different depending on the language, or do I establish a schema once that gets used for all of my documents? I have a basic search set up using the examples, but haven't been able to find any good resources on the analyzer usage.

**Comment by metonymic-smokey** [comment]
@Nickersoft thanks for reaching out.

Applying an analyser for a column cannot be done based on another column's value since we analyse and index both fields side by side.
