### ISSUE TITLE
Race between Batch() and DocCount()

### ISSUE THREAD

**Issue by otoolep** [blevesearch/bleve#198]
As of https://github.com/blevesearch/bleve/commit/57358088ec31fb651348a9497d7d7f2db1eef173. The Go race detector is complaining of the following.

WARNING: DATA RACE
Write by goroutine 22:
  github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Batch()
      /home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:616 +0xfa0
  github.com/blevesearch/bleve.(*indexImpl).Batch()
      /home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index_impl.go:304 +0x160

Previous read by goroutine 10:
  github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).DocCount()
      /home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:145 +0x4d
  github.com/blevesearch/bleve.(*indexImpl).DocCount()
      /home/ubuntu/.go_workspace/src/github.com/blevesearch/bleve/index_impl.go:345 +0x151

Do you believe this is something I should be fixing in my code? By RLocking the index before calling count? If so, there is nothing in the docs about this.

**Comment by mschoch** [comment]
No, you should not have to fix this in your code.  The index impl should protect itself, this is a bug.

**Comment by otoolep** [comment]
OK, thanks @mschoch -- that's what I thought, but I wanted to be sure.

**Comment by otoolep** [comment]
By the way, this test was run with the latest bleve code. I just referenced the latest commit on master.
