### ISSUE TITLE
Vector example returns empty result list

### ISSUE THREAD

**Issue by natb1** [blevesearch/bleve#2028]
I am very excited to see vector support. Thank you.

When I run the verbatim [example from the docs](https://github.com/blevesearch/bleve/blob/master/docs/vectors.md) I get an empty result set. The example prints "[]". This main func is just the indexing and searching example concatenated
```
func main() {
	doc := struct {
		Id   string
		Text string
		Vec  []float32
	}{
		Id:   "example",
		Text: "hello from united states",
		Vec:  []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
	}

	textFieldMapping := mapping.NewTextFieldMapping()
	vectorFieldMapping := mapping.NewVectorFieldMapping()
	vectorFieldMapping.Dims = 10
	vectorFieldMapping.Similarity = "l2_norm" // euclidean distance

	bleveMapping := bleve.NewIndexMapping()
	bleveMapping.DefaultMapping.Dynamic = false
	bleveMapping.DefaultMapping.AddFieldMappingsAt("text", textFieldMapping)
	bleveMapping.DefaultMapping.AddFieldMappingsAt("vec", vectorFieldMapping)

	index, err := bleve.New("example.bleve", bleveMapping)
	if err != nil {
		panic(err)
	}
	index.Index(doc.Id, doc)

	searchRequest := bleve.NewSearchRequest(query.NewMatchNoneQuery())
	searchRequest.AddKNN(
		"vec",                                   // vector field name
		[]float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}, // query vector (same dims)
		5,                                       // k
		0,                                       // boost
	)
	searchResult, err := index.Search(searchRequest)
	if err != nil {
		panic(err)
	}
	fmt.Println(searchResult.Hits)
}
```

If I run the bleve unit tests with --tags=vectors within the same environment (nix, macOS, ARM) they all pass.
[testout.txt](https://github.com/blevesearch/bleve/files/15203480/testout.txt)

- I am running all go commands with --tags=vectors
- I have compiled and installed FAISS from the bleve branch of the bleve fork commit 38f6b60c3658d82421a4627464855391444687e5
- I compiled with -DFAISS_ENABLE_C_API=ON (and may have sorted through some other linking issues)
- github.com/blevesearch/bleve/v2 v2.4.0

Any idea why this would return an empty result? Or, guidance on how to get more debugging information?

Thanks again.

**Comment by abhinavdangeti** [comment]
Update your code to this -

```
doc := struct {
		Id   string         `json:"id"`
		Text string       `json:"text"`
		Vec  []float32 `json:"vec"`
	}{
		Id:   "example",
		Text: "hello from united states",
		Vec:  []float32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
	}
```

I'll fix the readme with https://github.com/blevesearch/bleve/pull/2029

**Comment by natb1** [comment]
ah doy, thank you.
