### ISSUE TITLE
Keyword search on fields that start with a number do not match

### ISSUE THREAD

**Issue by osiloke** [blevesearch/bleve#207]
A search for a555c3bb06f7a127cda000005 will be matched but 555c3bb06f7a127cda000005 will not be matched.

**Comment by osiloke** [comment]
I dropped a line in the matchQuery Searcher method to print "Hello" whenever it is called and it seems to be called twice when searching fields that contain text like "555c3bb06f7a127cda000005".
I'm still digging through the bleve source code to see why but this is very strange.

**Comment by mschoch** [comment]
I've added a unit test which attempts to recreate the problem you're observing.  This seems to work when I do a term search directly.  Based on your earlier code samples I believe you're using a query string query.  So its possible the bug is in the parsing of the query string, or in the connection between the two query types.

**Comment by mschoch** [comment]
Link to unit test: https://github.com/blevesearch/bleve/blob/5b8c9f2d73336d9ff8da2af46b23d51911913d85/index_test.go#L868-L939

**Comment by mschoch** [comment]
OK, I've confirmed this has to do with the Query String parsing.  If you put the term starting with a number in quotes, it works as expected.

So a query string like:

Body:"555c3bb06f7a127cda000005"

will work, while

Body:555c3bb06f7a127cda000005

will not.

I'm pretty sure this has to do with how our parser recognizes numbers vs strings, but I have to review that code to see what (if anything) we can do about it.

**Comment by osiloke** [comment]
Well, at least for now the following is a better workaround for now
```
post:\"555c7f156f7a12d766000015\"
```
 i had already created a custom analyzer and tokenizer that ads a character in front of my fields that way i could do this
```
post:indexed555c7f156f7a12d766000015
```
Thanks for your help

**Comment by mschoch** [comment]
You should now be able to search as you originally expected.  I updated the test case I referenced earlier to include a query string term search with leading number.  See: https://github.com/blevesearch/bleve/blob/2af47cea7595510a99a97e86a96308ae67f4755c/index_test.go#L948

**Comment by osiloke** [comment]
Nicely done, thanks.
