### ISSUE TITLE
indexing in batches, doc count shows N, search matching everything returns < N

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#211]
1.  Index documents in batches, for total of N documents
2.  DocCount() returns N
3.  Run search which should match everything.

For some % of runs, this fails, and search returns < N results.

**Comment by mschoch** [comment]
I was provided a provide gist to reproduce this issue.  Only observed on linux box, not mac.

**Comment by mschoch** [comment]
It looks like the issue is that at the end of the batch, 2 things need to happen:

1.  commit the tx
2.  update the doc counts

Logically, we want these to occur in the order above.  However, we use deferred execution for 1 but not 2.  This means we're actually updating the doc count before we've committed the tx.

**Comment by otoolep** [comment]
Thanks @mschoch
