### ISSUE TITLE
bleve configuration overhaul

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#221]
The following is a proposal.  We would like your feedback.

### The Problem

Bleve has lots of optional components.  Many of these are analysis components specific to a particular language.  Often including these optional components introduce additional dependencies on 3rd party libraries or C libraries.  We wanted Bleve to include as much functionality as possible, while also remaining pure-Go so that the library was "go-gettable".

### Original Solution

We have a file "config.go" which includes components using the "import for side-effects" approach.  So for example it contains the import:

```
_ "github.com/blevesearch/bleve/analysis/language/en"
```

The side-effect of this is to include all the code specific to analyzing English text.  The config.go file is large, as it includes support for just about everything that is pure Go.

Further, we had additional config_\<feature\>.go files which were protected with build tags.  This meant you could add support for additional features by building with a build tag.  So you could do:

```
go build -tags 'leveldb'
```

By using this build tag, the config_leveldb.go file would be included, which would then link in all the additional code for using LevelDB.

### Why?

Why did we do this?  The idea was that we wanted a large amount of functionality available with minimal configuration. (think Elasticsearch)

### Problems with this Approach

1.  Builds are slower than necessary.  The compiler has to look into packages your program doesn't even use or care about.
2.  Binaries are larger than necessary.  Even if your code doesn't ever work with language X, we've included code to handle it.
3.  Build tags often add to the confusion.  People build/run/install code a variety of different ways, and build tags don't always seem to behave the same way everywhere everytime.

### Proposed Solution

1.  config.go will either go away completely, or be much smaller.
2.  All the config_\<feature\>.go files guarded by build tags will go away.
3.  Applications will be encouraged to include packages that add functionality that they need.

So, for example, if your application indexes English text, you would import:

```
import("github.com/blevesearch/bleve/analysis/lang/en")
```

In most cases, you won't need to use the blank identifier (_) trick either, because when you configure your mapping, you make use of the imported package with a line like:

```
englishTextFieldMapping := bleve.NewTextFieldMapping()
englishTextFieldMapping.Analyzer = en.AnalyzerName
```

I feel that by doing this, Bleve behaves more like you expect a Go library to behave.  It only includes what is necessary.  And it is up to your application to express its need for additional functionality.

### FAQ

1.  What if I'm building a general-purpose indexing application, like Elasticsearch?

    In this case, your application would end up having a file very much like the config.go file in Bleve.  It is more appropriate that this be in your application and not the library.

2.  Aren't some of the packages names I need to import now long and/or ugly?

    Yes, I think they are, but I think we could improve this too.  For example, I'd be open to renaming: `github.com/blevesearch/analysis/lang/en` to `github.com/blevesearch/bleve/lang/en`  Its a minor improvement, but can make a big difference in overall usability of the library.

### Summary

Overall, I feel that by making this change Bleve becomes more consistent with the approaches used by other Go libraries.

**Comment by steveyen** [comment]
Feels like a good thing to me, and might allow more Go community to more easily leverage "common Go" level of experience (no build tags) as they get more into Bleve.

Probably should come with an appropriate version bump?

Also assuming this won't have any persistent file-format changes, so my old index files should be reusable even though the API might have changed?

**Comment by mschoch** [comment]
Thanks @steveyen 

Currently we have no version numbers.  This is a separate problem, and my current thinking is that we would address that problem in the coming months.  In my opinion it would be beneficial to solve this configuration issue before we declare 1.0.

We do have version numbers for the indexing encoding format.  As this change won't affect the encoding scheme, it need not be bumped here.  Programs will continue to be able to read indexes created prior to this change.  However, they may need to include additional imports to ensure all the necessary components are built.

**Comment by bcampbell** [comment]
Yep, I think this sounds like a positive step.
I think I understand how the build tags work, but I never find them as intuitive as I'd like, and it always feels a little clunky.

I guess the standard `database/sql` package is one example of a similar model here, although it sounds like you want bleve to be more explicit, rather than using the anonymous underscore imports that sql drivers tend to endorse.

**Comment by mschoch** [comment]
Thanks for the `database/sql` pointer, I hadn't looked at that.

Regarding the underscore imports, they can still be used, as the importing of the package will still have the side-effect of registering the component in the bleve registry.  But, I think if we design it so that the code in the imported package is actually used, it helps the readability of the code.

I think if we move forward with this, we can update some of the example apps.  Then, with real examples to look at its easier to decide what the recommended way is.

**Comment by mschoch** [comment]
So, amidst other things I've also been starting to walk forward on this.  One slightly unexpected thing has come up.

Taking the cld2 analyzer as a fairly typical case.  In the top-level bleve we currently a file: config_cld2.go which, if the tag is present, will include the cld2 token filter and related analyzer.

To me this is clearly something that should be removed.  Someone interested in using those packages should import the corresponding packages in their app (either by direct use, or by underscore imports, guarded by build tags or not, all of this is an app concern)

But, where it is less clear is inside the: `analysis/token_filters/cld2 package`.  Right now that is also guarded by the same build tag.  I was initially thinking we would also remove that.

But, that has the unfortunate side-effect that the command

    go test -v ./...

when run from the top-level bleve package will fail if you don't have cld2 installed.  Not only does it fail, it stops without having tested everything else after that.

I feel like that is a pretty common go convention that we'd be giving up.  So, to me that leaves 2 options:

1.  Keep the build tags on the inner packages.  This seems like it might be even more confusing, as your app would have to import the package AND define the appropriate build tag.
2.  Move all the things that might require external dependencies outside of the core bleve repo.

I'm tending to lean towards 2, with the criteria for exclusion right now being a C library dependency.  Though I could see a case made for some 3rd party Go deps falling into this category too, though that seems like lower priority for now.

I welcome other input on this.

**Comment by mschoch** [comment]
Resuming this thread, as while I'm working on the performance improvements, it would help to also thin-out/rearrange the deps.

My latest thinking is this:

Any package that requires a C dependency will be moved out of the blevesearch/bleve hierarchy.

Inside of blevesearch/bleve, things like `go test -v ./...` will work.

One new git repo, blevesearch/blevex

Add-ons/Plugins to bleve which have a C dependency would be at the top-level of blevex (not replicating the organizational hierarchy of bleve)

There would be NO expectation that `go test -v ./...` works at the top-level of blevex, only that individual packages can be tested when their dependencies are satisfied.

So, we would see something like:

blevex/cld2
blevex/cznic (even though cznic doesn't have C dep, it cannot fully satisfy interface contract)
blevex/forestdb
blevex/icu
blevex/leveldb
blevex/rocksdb

There would be no build tags required to use these, apps would simply import the packages if they want them.

I chose "blevex" because its short, but and also connotes extensions to the main bleve, but I could be convinced something else instead.

**Comment by steveyen** [comment]
+1 on the blevex proposal, and really liking that go test -v ./... should just work for bleve.

It also seems like if I was a pure-go bleve user already, then I suspect (but no proof) that my app should still work even after blevex shows up.
