### ISSUE TITLE
There is no way to convert a search result data into a JSON/struct

### ISSUE THREAD

**Issue by dorsha** [blevesearch/bleve#252]
I think this feature can be really useful (similar to how elastic works).

For example, in elastic this can be done to convert result into struct easily:

```
someStruct = &someStruct{}
err = json.Unmarshal(*searchResult.Source, someStruct)
```

**Comment by albertog** [comment]
+1

**Comment by mschoch** [comment]
I believe this is a duplicate of https://github.com/blevesearch/bleve/issues/174
