### ISSUE TITLE
Expose row fields to enable client debugging/tooling

### ISSUE THREAD

**Issue by pmezard** [blevesearch/bleve#268]
Hello,

I have written a simple command computing the term histogram of an index. It is a simple loop on Index.DumpAll, type switching on error and TermFrequencyRow. Unfortunately I had to expose the tfr.term and tfr.freq with accessors to be able to use the rows.

Is there any reason to hide this information? I understand that accessing rows is not a basic usage of bleve API, but it makes writing debugging tools unnecessarily harder.

FWIW, this histogram tools already made obvious I have sanitizing issues with terms, though I do not know where the error comes from in the analysis chain yet.

**Comment by mschoch** [comment]
I guess it depends what you're trying to accomplish.  If you're just trying to debug, it might make more sense to just set the Stringer interface set up to spit out the info we want.

If we go down the path of type assertions to the specific Row implementations then (which I think we already do) we're going to create more work for ourselves when new index implementations come along (and one is already in progress)

**Comment by pmezard** [comment]
I am not sure why you expect extra work. I imagine 3 cases:
1- Debugging. No problem, you can just hack bleve source code and revert later
2- Exploring low level data stored in the index. Obviously depends on the index structure, so no big deal if such tools break when the index changes. These tools are useful to understand how the index works, how it interacts with the backend and "feel" the dataset size. They also lead to [3].
3- Explore high level properties of the index. The term histogram may belongs to this category, it helps tuning the analysis process and gives domain specific information about the dataset. And that regardless of the index structure. It might be worth adding and supporting dedicated APIs to expose such features.

My small frustration with [2] is I see no good reason to hide the internal index structure, provided it is advertized as completely unstable. But hiding it hampers exploration which might lead to [3].

For now I have reverted my local changes and partially reimplemented the key/value decoding logic, so I have a workaround.

**Comment by mschoch** [comment]
I'm not saying we have to hide it.  I'm saying that if the bleve_dump does a type assertion to (*upside_down.TermFrequencyRow), then theres just more work to be done down the road.  If there was some other interface, or for lots of cases just using Stringer, then we don't have to update bleve_dump everytime we make changes.

**Comment by pmezard** [comment]
OK. I was not suggesting to touch at bleve_dump, and if I ever find this histogram tool absolutely awesome and necessary I would make a dedicated pull-request and argue maintenance costs are worth it.

Here I am just talking about making the row fields public. It may be with accessors, or by exporting them, as you prefer.

**Comment by mschoch** [comment]
I would vote for accessor methods.
