### ISSUE TITLE
Add new tokenizer that handles web data well 

### ISSUE THREAD

**Issue by WillGardella** [blevesearch/bleve#269]
Add a new 'web' tokenizer that preserves structured information like:
- URLs / URIs (e.g. http://www.example.com or https://www.example.com/abc?foo=bar&oops=true)
- email addresses (e.g. email@example.com)
- Twitter handles and hashtags (@twitter #mollusks)

Without the new tokenizer, the special characters are often ignored or cause the tokenizer to break what should be a single token in the index into two or more separate tokens.

**Comment by meirwah** [comment]
Is there any work in progress to solve this?

**Comment by mschoch** [comment]
The simplest solution is to configure an "exception" tokenizer which has regular expressions defined for the above.  So, with the appropriate regular expression magic, it should take someone about 15 minutes.
