### ISSUE TITLE
remove bleve/http/mapping?

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#289]
Hey @steveyen now that we have a separate project for [bleve-mapping-ui](https://github.com/blevesearch/bleve-mapping-ui) can we remove this package?

**Comment by steveyen** [comment]
Yep, I think it's deletable from blevesearch/bleve now.

**Comment by steveyen** [comment]
commit ab3188becb62204d66d4e56b4480d7868641eb37
