### ISSUE TITLE
Issue when searching '@' term 

### ISSUE THREAD

**Issue by meirwah** [blevesearch/bleve#290]
Hi,
I have some data stored in Bleve, where one of the fields contains a text of "@meir",
when I try to search for "meir" I get results, but when I try to search "@" i get no results at all,
and if I search "@meir" only the part is highlighted ...  

See below:
![image](https://cloud.githubusercontent.com/assets/6059211/11475444/24605ada-9786-11e5-854b-a2af723d67e2.png)

![image](https://cloud.githubusercontent.com/assets/6059211/11475461/3528c438-9786-11e5-94cb-1f583040125d.png)

![image](https://cloud.githubusercontent.com/assets/6059211/11475470/427bf132-9786-11e5-87fb-92f386bd2974.png)

any idea what can be the issue?
It does not seem that '@' is a special char from docs...

**Comment by mschoch** [comment]
The problem is that the Unicode standard tokenizer considers the @ to be punctuation and it is removed during the tokenization process.  We have an issue open to build a tokenizer which treats things like twitter handles as exceptions that should be kept intact: see #269

**Comment by mschoch** [comment]
I have pushed some code for #269 if you want to give it a try and let us know that would be great.

**Comment by meirwah** [comment]
Hi @mschoch , 
Thanks for the quick response on this!!
It seems that our internal mapping was wrong, so we actually needed to use keyword analyzer in the end..
sorry for the confusion... 
Hopefully we will use the new analyzer in the future..
