### ISSUE TITLE
pprof of rocksdb-firestorm can lock

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#308]
I've been playing around with the new firestorm engine w.r.t. performance, and I was able to occasionally (not all the time) have bleve-blast lockup while using rocksdb-firestorm configuration, where eventually, bleve-blast stops making progress.

To reproduce, in the bleve-bench/cmd/bleve-blast directory...

$ CGO_CFLAGS="-I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy" go build -tags "prod rocksdb" && rm -rf bench.bleve/ && ./bleve-blast -source=../../tmp/enwiki.txt -count=1000000 -numAnalyzers=8 -numIndexers=8 -config=../../configs/rocksdb-firestorm.json -batch=100 -bindHttp=127.0.0.1:5555

More info is here at this gist, including goroutine dump, versions, etc: https://gist.github.com/steveyen/cb1333c517285d43edb7

**Comment by steveyen** [comment]
More info...

Looks like it runs fine, but locks once you try to get profiling data via REST/HTTP.

For example, after I have bleve-blast running (per above reproduction instructions), it runs fine.  But, then I try to get profiling info, via...

  go tool pprof http://127.0.0.1:5555/debug/pprof/profile

And, then, indexing progress soon locks right after, with MB/sec dropping to 0.  The goroutine that emits progress lines to stdout, however, keeps on going.

**Comment by mschoch** [comment]
Ah interesting, I think I have seen this before.  Its some weird problem that seems to be related to Go, cgo, and the profiler, not all getting along together.

I think I ended up abandoning one line of profiling for this very reason.

**Comment by steveyen** [comment]
More info: this was on OSX 10.11.1, with go1.5.2 darwin/amd64

**Comment by mschoch** [comment]
It would be possible to have an option for our RocksDB KV adapter to do manual merge instead of built-in merge.  This would help confirm that it is C calling back into Go that is the source of the problem.

**Comment by mschoch** [comment]
Migrated this issue to blevex: https://github.com/blevesearch/blevex/issues/26
