### ISSUE TITLE
firestorm newFirestormReader() snapshotting operations reversed

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#312]
Some notes from discussion with @mschoch...

firestorm's newFirestormReader() (in reader.go) should reverse the order of operations in...

- A) grabbing a store.Reader()
- B) snapshotting the compensator  

So, it should be B and then A.

Related, the firestorm garbage collector should not delete rows needed by a reader, in-between steps B+A and possibly even after steps B+A, as long as the reader is open.  This later issue needs more thought.

**Comment by mschoch** [comment]
Firestorm has been retired.
