### ISSUE TITLE
panic with rocksdb backend

### ISSUE THREAD

**Issue by donhcd** [blevesearch/bleve#332]
I can't really tell if this is a bleve or blevex/rocksdb or a pure rocksdb issue or a combination of those, but I'm getting a `panic`/segfault when I `Close` an index which was just created using `bleve.New`, using master of both bleve and blevex:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x41 pc=0x41]

runtime stack:
runtime.throw(0xb12580, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90 fp=0x7fb1907fabc8 sp=0x7fb1907fabb0
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x7fb1907fac18 sp=0x7fb1907fabc8

goroutine 10 [syscall, locked to thread]:
runtime.cgocall(0x40d468, 0xc8200368b8, 0xc800000000)
        /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820036888 sp=0xc820036858
github.com/tecbot/gorocksdb._Cfunc_rocksdb_mergeoperator_destroy(0x2cbfe20)
        github.com/tecbot/gorocksdb/_obj/_cgo_gotypes.go:1292 +0x31 fp=0xc8200368b8 sp=0xc820036888
github.com/tecbot/gorocksdb.(*Options).Destroy(0xc82012e060)
        /go/src/github.com/tecbot/gorocksdb/options.go:902 +0x62 fp=0xc8200368c8 sp=0xc8200368b8
github.com/blevesearch/blevex/rocksdb.(*Store).Close(0xc8200fb500, 0x0, 0x0)
        /go/src/github.com/blevesearch/blevex/rocksdb/store.go:99 +0x49 fp=0xc8200368d8 sp=0xc8200368c8
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Close(0xc820110400, 0x0, 0x0)
        /go/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:412 +0x46 fp=0xc820036908 sp=0xc8200368d8
github.com/blevesearch/bleve.(*indexImpl).Close(0xc820110380, 0x0, 0x0)
        /go/src/github.com/blevesearch/bleve/index_impl.go:684 +0xa4 fp=0xc820036948 sp=0xc820036908

```

**Comment by mschoch** [comment]
Can you also let us know what version of rocksdb?  We're doing a lot of testing with this right now and haven't run into this ourselves.

**Comment by donhcd** [comment]
The command I'm running to install it is essentially

```git clone https://github.com/facebook/rocksdb ~/rocksdb && cd ~/rocksdb && git checkout tags/v4.1 && make shared_lib```

so the version of rocksdb should be [4.1](https://github.com/facebook/rocksdb/releases/tag/v4.1)

**Comment by mschoch** [comment]
Thanks, I've mostly been testing with 3.13.1.  But I also just heard from a co-worker that he was able to reproduce.

**Comment by steveyen** [comment]
Hi, I'm also using rocksdb 4.1; and techbot/gorocksdb commit 762103f8ef378.

And, after putting an index.Close() call into my code (which I didn't have before), I also get the panic (see below).

Unfortunately, after staring at this, deploying lots of printf's, I don't know why this is happening either.

Using go1.5.2, darwin/amd64.

One suspicion is GC might be involved, perhaps similar to this reported issue with gorocksdb comparator callbacks: https://groups.google.com/forum/#!topic/golang-nuts/24BCnAWcqrw

bleve-blast(31568,0x700000728000) malloc: *** error for object 0x6a00ee0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff968ab0ae m=7
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x479a920, 0xc820115cf8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820115cc8 sp=0xc820115c98
github.com/tecbot/gorocksdb._Cfunc_rocksdb_mergeoperator_destroy(0x6a00ee0)
	github.com/tecbot/gorocksdb/_obj/_cgo_gotypes.go:1299 +0x31 fp=0xc820115cf8 sp=0xc820115cc8
github.com/tecbot/gorocksdb.(*Options).Destroy(0xc820076a80)
	/Users/steveyen/go/src/github.com/tecbot/gorocksdb/options.go:902 +0x62 fp=0xc820115d08 sp=0xc820115cf8
github.com/blevesearch/blevex/rocksdb.(*Store).Close(0xc820075840, 0x0, 0x0)
	/Users/steveyen/go/src/github.com/blevesearch/blevex/rocksdb/store.go:99 +0x49 fp=0xc820115d18 sp=0xc820115d08
github.com/blevesearch/bleve/index/store/metrics.(*Store).Close(0xc8200b77c0, 0x0, 0x0)
	/Users/steveyen/go/src/github.com/blevesearch/bleve/index/store/metrics/store.go:92 +0x45 fp=0xc820115d48 sp=0xc820115d18
github.com/blevesearch/bleve/index/upside_down.(*UpsideDownCouch).Close(0xc82009ce00, 0x0, 0x0)
	/Users/steveyen/go/src/github.com/blevesearch/bleve/index/upside_down/upside_down.go:412 +0x46 fp=0xc820115d78 sp=0xc820115d48
github.com/blevesearch/bleve.(*indexImpl).Close(0xc82009cd00, 0x0, 0x0)
	/Users/steveyen/go/src/github.com/blevesearch/bleve/index_impl.go:684 +0xa4 fp=0xc820115db8 sp=0xc820115d78
main.main()
	/Users/steveyen/go/src/github.com/blevesearch/bleve-bench/cmd/bleve-blast/main.go:122 +0x9ac fp=0xc820115f40 sp=0xc820115db8
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820115f90 sp=0xc820115f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820115f98 sp=0xc820115f90

**Comment by steveyen** [comment]
Another diagnosis observation...

When I add explicit options.Destroy() invocations to the tecbot/gorocksdb merge operator tests, here...

https://github.com/tecbot/gorocksdb/blob/master/merge_operator_test.go

...the tests still run fine and do not crash/panic.

So there's something about the blevesearch/blevex rocksdb adaptor or perhaps bleve's upside_down merge operators that somehow are different, but I don't see it yet.

**Comment by mschoch** [comment]
OK, I read up a little more about this.

`rocksdb_mergeoperator_destroy` is called by Options.Destroy()

we call that in Store.Close()

I searched on google for `rocksdb_mergeoperator_destroy` and found this:

https://github.com/facebook/rocksdb/issues/343

A Facebook developer commented that this method should NOT be called on merger operators that were subsequently passed to a `rocksdb_options_set_merge_operator()` call.  So it would seem like this is an issue in the tecbot wrapper.

If you all agree with this understanding, we can file an issue upstream.

**Comment by steveyen** [comment]
I see this issue #332 got auto-linked to rocksdb issue #343 by github.

But, I see that proposed PR didn't get linked here, so... https://github.com/blevesearch/blevex/pull/14 didn't get linked here, so

**Comment by tmm1** [comment]
I believe this issue can be closed?

**Comment by mschoch** [comment]
I still haven't filed issue upstream, currently we just have a workaround which never frees a larger data structure to avoid the wrapper library from incorrectly freeing something it no longer owns.

**Comment by mschoch** [comment]
I have filed upstream issue: https://github.com/tecbot/gorocksdb/issues/51

**Comment by mschoch** [comment]
I've migrated this issue to blevex: blevesearch/blevex#25
