### ISSUE TITLE
Boost values are not used for anything outside term queries

### ISSUE THREAD

**Issue by slavikm** [blevesearch/bleve#333]
For example, NewRegexpSearcher just uses 1.0 instead of the boost parameter it receives.

**Comment by mschoch** [comment]
Can you provide an example query and results with scoring?

Somewhat confusingly boost only ever has effect if there are multiple clauses in a query (it then adjusts the relevant weights between those clauses)

**Comment by slavikm** [comment]
Of course, I understand that :-)
But look at the code, it just ignores the boost value and passes 1.0 as constant.

Anyway, I have my own string query parser that translates terms with * in them to wildcard queries. I'm trying to query:
xxx yy*^100

Without changing the code, it gives me the xxx results first. After changing NewRegexpSearcher to pass in the boost parameter, it gives me yy* first.
