### ISSUE TITLE
Sort facet terms

### ISSUE THREAD

**Issue by bep** [blevesearch/bleve#335]
This is easy to do client side, but some sort of sensible sorting should be out-of-the-box (name, # matches?).

As it is now, the client get jitterish when doing facet refinements.

**Comment by mschoch** [comment]
Can you be more specific about the result you're seeing.  On the server we already have them in order by count descending, since thats how we decide which to return.  And in my tests that is the same order they come through on the client.

**Comment by bep** [comment]
Yes, they are consistent by count,   but in my case I have some categories.

So, given term and # maches:

``
A  (2)
B  (2)
C  (1)
``

The count will always be ordered, but the names seems random, so I see:

``
B  (2)
A  (2)
C  (1)
``

**Comment by mschoch** [comment]
OK, so would a secondary sort by term for facet results that have the same number of results improve things for now?

**Comment by bep** [comment]
Yes, that would do the trick for me.

**Comment by gedw99** [comment]
Any chance this could be fixed ? Its a show stopper for me using this on a project at the moment. 
I just tried it this morning, and its still there in the GUI for Fosdem-search

**Comment by gedw99** [comment]
Any idea if this is likely to be fixed in the next week ? Sorry to ask, but i am using this functionality for a real project...

**Comment by gedw99** [comment]
thanks Marty, i will test it now.
