### ISSUE TITLE
Analyzer for German ?

### ISSUE THREAD

**Issue by gedw99** [blevesearch/bleve#356]
I am indexing German text. They have some funny characters, so i guess i should be using the correct Analysis language ?

When i look here there are a few, but cant work out if German (DE) is there ?
https://github.com/blevesearch/bleve/tree/master/analysis/language

at the moment i use EN, and it still managed to find the German word "für" correctly in the UI.
So maybe its fine ?
````

enFieldMapping := bleve.NewTextFieldMapping()
enFieldMapping.Analyzer = en.AnalyzerName

```

**Comment by Shugyousha** [comment]
Hi Ged

On Mon, Mar 14, 2016 at 11:59:35AM -0700, Ged wrote:
> I am indexing German text. They have some funny characters, so i guess
> i should be using the correct Analysis language ?
> 
> When i look here there are a few, but cant work out if German (DE) is there ?
> https://github.com/blevesearch/bleve/tree/master/analysis/language
> 
> at the moment i use EN, and it still managed to find the German word
> "für" correctly in the UI.  So maybe its fine ?

The Analyzer for German is in the blevex repo here.

https://github.com/blevesearch/blevex/tree/master/lang/de

You will find a filter for German stop words and a stemmer as well. I
have used them for a bit but can't tell you if it fits your needs.

I am sure that feedback will be appreciated!

**Comment by joeblew99** [comment]
Thanks . yes I will be happy to give feedback tomorrow once ikick the tires.

**Comment by gedw99** [comment]
Ok i managed to start using that now.
Will let you know for sure... Thanks again..

**Comment by Shugyousha** [comment]
I think I have seen that you have gotten the answer on the mailing list already but just for visibility I will mention it here as well.

It seems like the default analyzer configured with `de.AnalyzerName` will use the token filter referred to by`de.NormalizeName`. That token filter seems to replace `ß` with `ss` and umlauts with their tremata-less forms.

To avoid this from happening, you can use a custom analyzer (with `AddCustomAnalyzer`). As long as you don't add the default tokenizer of the `de` package, these replacements will not happen.

I hope that helps!
