### ISSUE TITLE
how to do multi index search

### ISSUE THREAD

**Issue by thomasmodeneis** [blevesearch/bleve#362]
Hi,

I'm using Bleve for couple projects I'm developing and I'm also having big time to figure out a way to perform a full index search, by that I mean searching on a set of pre-defined indexes and concat the results before returning it back to the client.

What I want is something similar to elasticsearch when you ommit the index it does a full search on all available indexes witch is pretty handy.

I could not find anything on the docs that could potentially give me a direction so I had to open this ticket here, sorry about that.

Does anyone may have a idea how can I manage to work around this ?

Thanks

**Comment by mschoch** [comment]
I just answered a very similar question on the google group: https://groups.google.com/d/msg/bleve/-RoyHFfUPLI/Ai69yI2jCQAJ

Does that help?

**Comment by thomasmodeneis** [comment]
Hi @mschoch 
Thanks for your tips, I will work on this during the weekend and get you posted here if I find any other complications, cheers.

For the record, the tip was:
```
The feature you want to use is called IndexAlias.
You would first open the physical indexes:
schools, err := bleve.Open(...)
...
teachers, er := bleve.Open(...)
...
etc

Then would create one using 

everything := NewIndexAlias(schools, teachers, ...)

Now you use "everything" just like the other indexes (from an API perspective an IndexAlias is an Index)
```

**Comment by shirmanov** [comment]
Hi @mschoch
is there any particular order in which indexes are used when added to an index alias?
