### ISSUE TITLE
Storage backend specific Operations like Compaction

### ISSUE THREAD

**Issue by lambdaupb** [blevesearch/bleve#363]
I'm currently using the leveldb backend storage and it performs quite nicely;
But I produce a write-once/read-many index and would like to do a compaction phase before deploying a new index.

LevelDB and RocksDB both have some support for forcing a compaction.
`db->CompactRange(NULL, NULL);` in leveldb or `DB::CompactFiles()` for rocksdb

Maybe bleve could support this sort of action through an API.

**Comment by mschoch** [comment]
The problem we have is the various backends we support all have different and useful APIs.  If we were to support all of them directly in Bleve it would end up being a mess.

Our current thinking is that we'll only put things into the Bleve API when there is some clear common behavior across *most* of the implementations.  An example that does not exist yet, but could in the future, would be a mechanism to perform a live backup.

To your specific case, for now the work around we recommend is to use the Advanced() method on the index.

index, err := bleve.Open(...)

_, kvstore, err := bleve.Advanced()
if err != nil {
  // handle error
}

// type assert to the expected implementation
if kvstore, ok := kvstore.(*leveldb.Store) {
  kvstore.Compact(...)
}

Now, this still requires you to add the Compact() method to the LevelDB KVStore implementation, but it frees us from having to but no-op implementations into all the kvstores.

**Comment by mschoch** [comment]
We have added Compact() for now, but will review the need for additional storage specific operations on a case by case basis.
