### ISSUE TITLE
Global Search Using Bleve

### ISSUE THREAD

**Issue by DNadar** [blevesearch/bleve#364]
Hi,

I am using Bleve for my application and i am impressed with the way it works.
Currently i am able to retrieve the Search result from the Index Folder created using Bleve.Open as mentioned in the Documentation.

Currently, for eg: i am creating indexes depending upon the Entity.
Let say i have Entity called School, Teachers, Students and i have defined separate indexes for the Entity.

after creating indexes using bleve, here is the folder structure 
index/School/{index file generated by Bleve}
index/Teacher/{index file generated by Bleve}
index/Student/{index file generated by Bleve}

I am able to retrive the data for school by opening index file 'index/School' (similarly for Teacher and student)

How to do a global Search irrespective of the entities. Meaning i want to do a search across School, Teacher and Student when i am not aware of which entity to search for.

Thank you,
DNadar.

**Comment by mschoch** [comment]
Your question posted to the google group has been answered: https://groups.google.com/d/msg/bleve/-RoyHFfUPLI/Ai69yI2jCQAJ
