### ISSUE TITLE
How search by prefix of field?

### ISSUE THREAD

**Issue by gebv** [blevesearch/bleve#366]
```
    conjuncts := make([]bleve.Query, 2)
    conjuncts[0] = bleve.NewPrefixQuery("Title:title")
    conjuncts[1] = bleve.NewQueryStringQuery("Options.Tags:tag1")
    
    query := bleve.NewConjunctionQuery(conjuncts)
```

**Comment by mschoch** [comment]
I do not understand what you're asking.  The prefix query will match terms that contain the supplied prefix.

Your use of fieldname:term inside a prefix query is incorrect.  Only QueryStringQuery supports that syntax.  All the other queries are only for programatic use.

```
prefixQuery := bleve.NewPrefixQuery("title").SetField("Title")
```

**Comment by gebv** [comment]
Oh, i realized my mistake
`bleve.NewPrefixQuery("Title:title")` corresponds to the `bleve.NewPrefixQuery("title").SetField("Title")`
thx @mschoch
