### ISSUE TITLE
Any version?

### ISSUE THREAD

**Issue by yanyiwu** [blevesearch/bleve#367]
Please do some versioning for this project.
It has 900 commits already.

And versioning helps me to develop some custom analyzer of bleve. 

Plus: if it had more details about AddCustomAnalyser api in documents, it would be better than now.

**Comment by mschoch** [comment]
Sorry for the delay.  A lot of users want different things under the simple headline "version numbers".  We've been trying to find a way to solve all of them and not been successful.

I will post a proposal to the google group today, and after giving people time to share feedback we will move forward.  I will post a link to the google group message here once it is posted.

Can you elaborate on these points?

1.  How will versioning help you develop a custom analyzer?
2.  Have you seen this example of AddCustomAnalyzer? https://github.com/blevesearch/beer-search/blob/master/mapping_example1.go#L76-L99  Would a page explaining this exmample in more detail be helpful?  Or are you trying to do something more advanced than this?

**Comment by mschoch** [comment]
I've posted a version number proposal here: https://groups.google.com/d/msg/bleve/pBVVnEfqB7M/EERaT5ToBwAJ

If possible share you comments on the google-group, if thats not possible you an share them here.

**Comment by yanyiwu** [comment]
Thanks very much.

1. Good proposal , and it let me know you already knew how to do version things of this project,
just do it, it is much better than now(no any tags).

2. I already finished custom analyzer for Chinese development (https://github.com/yanyiwu/gojieba) , with  the help of google. When I issue this, I just want some documents about the custom analyzer in http://www.blevesearch.com , even though just a few links in there, better than nothing.
