### ISSUE TITLE
Regression after updating bleve 

### ISSUE THREAD

**Issue by Spivaka** [blevesearch/bleve#368]
@mschoch 
This commit https://github.com/blevesearch/bleve/commit/0b171c85da0922a0baf5fd559ec8515dd35cadb8 changed the search of simple fields to letter from unicode. This means that searching for a term that includes numbers such as "LALALA83" will return 0 answers although the field searched has this value.

We are using this simple search all across our product - this change break it (beside the fact that searching numbers is a part of searching values...)

**Comment by mschoch** [comment]
Sorry about that, we were not expecting very many people to be using the simple analyzer.

Previously our simple analyzer had the wrong definition, and was not simple enough.  This change makes the simple analyzer work closer to the one with the same name offered by Elasticseach and Lucene.

Is it possible for your application to use a custom analyzer with this definition?

```
	err = indexMapping.AddCustomAnalyzer("simpleClassic",
		map[string]interface{}{
			"type": `custom`,
			"tokenizer": `unicode`,
			"token_filters": []interface{}{
				`to_lower`,
			},
		})
	if err != nil {
		return nil, err
	}
```

**Comment by Spivaka** [comment]
Did is exactly what we did as a work around, implemented our own analyzer with unicode. 
I'm not sure I am following - Lucene and Elasticseach don't support searching for numbers?

**Comment by mschoch** [comment]
Sure, of course they do, but not if you index text using the simple analyzer.

Here is the output from Elasticsearch using a query to test the behavior of their "simple" analyzer:

```
$ curl -XGET 'localhost:9900/_analyze?analyzer=simple' -d 'LALALA83' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    90  100     8  10531    936 --:--:-- --:--:-- --:--:-- 11250
{
  "tokens": [
    {
      "token": "lalala",
      "start_offset": 0,
      "end_offset": 6,
      "type": "word",
      "position": 1
    }
  ]
}
```

You see that it too drooped '83' portion of the term.

Here is the same term passed to Elasticsearch's standard analyzer:

```
$ curl -XGET 'localhost:9900/_analyze?analyzer=standard' -d 'LALALA83' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   106  100    98  100     8   6786    553 --:--:-- --:--:-- --:--:--  7000
{
  "tokens": [
    {
      "token": "lalala83",
      "start_offset": 0,
      "end_offset": 8,
      "type": "<ALPHANUM>",
      "position": 1
    }
  ]
}
```

The change we made last week brings our behavior more in line with their behavior.

In general we're trying to avoid problems like this.  This is something that would have benefitted from the version number proposal recently discussed, as users would have at least had some advanced warning of the change.  Then once we reach a 1.x version, we would not even allow such a change.

**Comment by Spivaka** [comment]
Than in which analyzer we should use for searching text, including numbers, other than simple?

**Comment by mschoch** [comment]
The default analyzer is "standard" and is the one we recommend most users start with unless it doesn't work for their use case.

There is nothing wrong with using the custom analyzer above.  The only difference between it and the standard analyzer is that the standard analyzer also removes English stop words.

**Comment by Spivaka** [comment]
Ok, as we do allow stop words in our texts we will use our custom analyzer. 
Thanks for your help!
