### ISSUE TITLE
PROPOSAL: remove byte_array_converters

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#392]
The bleve index mapping allows you to configure something called a "byte_array_converter".  The original idea was to let you pass in a slice of bytes to the top-level Index() method and have bleve make sense of the data.

The default "byte_array_converter" attempts to parse the bytes as JSON, and then index the resulting data structure.  This was intended as a convenience for people building applications that worked with JSON.

### PROBLEM

If the bytes fail to parse as JSON, all bleve methods return an error.  This poses 2 real problems for applications:

1.  Batch operations end up getting aborted because of 1 bad document
2.  Applications may want to catch this error and handle it themselves (possibly indexing stub document instead)

The good news is that applications can already do this themselves.  They simply parse the JSON themselves first, detect/handle errors, and then pass the resulting structures on to Bleve.

Our observation has been that real applications are better served doing this themselves.

### PROPOSAL

Rather than try to fix the problems, we propose to remove byte_array_converters completely.

1.  Initially we envisioned that there would be several more implementations.  In practice this didn't actually materialize.
2.  By making this change we can remove code from the analyzer sub-package and in one small way simplify the mapping.  Although its a small simplification, the mapping is the most complex part of bleve, so it is a welcome change.

### UPDATING YOUR APP

If your application fed raw JSON bytes into bleve as:

```
    err := bleve.Index(id, jsonbytes)
```

You would now need to write:

```
    var jsondoc interface{}
    err := json.Unmarshal(jsonbytes, &jsondoc)
    if err != nil {
        err = bleve.Index(id, jsondoc)
    }
```

**Comment by steveyen** [comment]
No objections from me.

But, full disclosure, I've been working on an application which already uses the application-driven approach/proposal that Marty describes.  In case it might be useful to others, link to "in the wild" code here - https://github.com/couchbase/cbft/blob/master/pindex_bleve.go#L999

**Comment by mmindenhall** [comment]
It would be nice to have the commit message say something like:  "POSSIBLE BREAKING CHANGE (see #392)".  It would have saved some time figuring out why tests were failing all over the place.  Thanks!
