### ISSUE TITLE
Get all the documents in an Index

### ISSUE THREAD

**Issue by DNadar** [blevesearch/bleve#395]
Is there any Rest API to load all the Documents Present in the Index file.

Currently, i am indexing the Document (in all 25 document) and on search i am able to get the Corresponding Documents in the Search text input.

How to load the entire Document (all 25 document) irrespective of any text search.

**Comment by mschoch** [comment]
See https://github.com/blevesearch/bleve/blob/master/query_match_all.go#L24-L26

**Comment by DNadar** [comment]
Thanks for the reply :)
