### ISSUE TITLE
Panic if using goleveldb while indexing and searching

### ISSUE THREAD

**Issue by nekrondev** [blevesearch/bleve#403]
I modified beer-search example to use goleveldb:
```
import (
_ "github.com/blevesearch/bleve/index/store/goleveldb"
...
)
...
beerIndex, err := bleve.NewUsing(*indexPath, indexMapping, bleve.Config.DefaultIndexType, "goleveldb", nil)
...
```
Now indexing of beer works fine, but if I try to search for items bleve will panic with the following error:

```
2016/08/01 10:45:17 http: panic serving [::1]:51743: runtime error: invalid memory address or nil pointer dereference
goroutine 34 [running]:
net/http.(*conn).serve.func1(0x1cf1fc80)
        C:/Go/src/net/http/server.go:1389 +0xa2
panic(0x8622c0, 0x1123c030)
        C:/Go/src/runtime/panic.go:443 +0x3fd
github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0x0, 0x323c1d58, 0x112a17f0, 0x1cee2000, 0x0, 0x0, 0x0)
        c:/src/go/src/github.com/blevesearch/bleve/index_impl.go:374 +0x2ccf
github.com/blevesearch/bleve.(*indexImpl).Search(0x0, 0x1cee2000, 0x0, 0x0, 0x0)

        c:/src/go/src/github.com/blevesearch/bleve/index_impl.go:368 +0x6d
github.com/blevesearch/bleve/http.(*SearchHandler).ServeHTTP(0x117048d0, 0x32435030, 0x14b62000, 0x1ce5a000)
        c:/src/go/src/github.com/blevesearch/bleve/http/search.go:76 +0x78f
github.com/gorilla/mux.(*Router).ServeHTTP(0x11706330, 0x32435030, 0x14b62000, 0x1ce5a000)
        c:/src/go/src/github.com/gorilla/mux/mux.go:103 +0x20a
net/http.(*ServeMux).ServeHTTP(0x11227fa0, 0x32435030, 0x14b62000, 0x1ce5a000)
        C:/Go/src/net/http/server.go:1910 +0x133
net/http.serverHandler.ServeHTTP(0x11710820, 0x32435030, 0x14b62000, 0x1ce5a000)

        C:/Go/src/net/http/server.go:2081 +0x156
net/http.(*conn).serve(0x1cf1fc80)
        C:/Go/src/net/http/server.go:1472 +0xed8
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2137 +0x394
```
Searching for items will only work if I stop the indexing process and start beer-search with an already build index.

I was POCing bleve for a large-scale logfile search application using goleveldb, because of its default compression needed for millions of loglines. However indexing and searching must be possible in parallel or else I am not able to keep an up-to-date search index.

**Comment by mschoch** [comment]
So, indexing and searching at the same time is quite heavily tested, but not with the goleveldb adapter.  So I would strongly suspect a bug in either our wrapper around goleveldb or goleveldb itself.  I'll try to reproduce the problem later today.

Can you let me know the git SHA of your `github.com/syndtr/goleveldb` repo?

**Comment by mschoch** [comment]
Actually, also the SHA for bleve, as the line numbers seem to point to blank lines in master.

**Comment by nekrondev** [comment]
For bleve: 9089de251f3d8ab973d30158325650f1dd520efb
For goleveldb: ab8b5dcf1042e818ab68e770d465112a899b668e

Many Thanks for your hard work, bleve search is very appreciated here as a go FTS engine.

Cheers,
Nek

**Comment by mschoch** [comment]
Thanks,

So, the line number at the top of the stack, pinned to the version of bleve you're using is this:

https://github.com/blevesearch/bleve/blob/9089de251f3d8ab973d30158325650f1dd520efb/index_impl.go#L374

That's an odd place for a nil pointer, and suggests that the indexImpl pointer method receiver is nil.  Most of the time that happens when users don't check the value of err when opening an index, but you indicated this happens with beer-search, so that suggests something else is happening.

I'm still digging into this, just dropping some notes here.

**Comment by mschoch** [comment]
Hmmn, so I went back to the same version of bleve, and went forward one commit to have the same version of goleveldb, but so far I'm unable to reproduce the problem.

The only change to beer-search that I made is this:

```
diff --git a/main.go b/main.go
index 97f4420..cb4e3e8 100644
--- a/main.go
+++ b/main.go
@@ -23,6 +23,7 @@ import (
 
        "github.com/blevesearch/bleve"
        bleveHttp "github.com/blevesearch/bleve/http"
+       "github.com/blevesearch/bleve/index/store/goleveldb"
 )
 
 var batchSize = flag.Int("batchSize", 100, "batch size for indexing")
@@ -57,7 +58,7 @@ func main() {
                if err != nil {
                        log.Fatal(err)
                }
-               beerIndex, err = bleve.New(*indexPath, indexMapping)
+               beerIndex, err = bleve.NewUsing(*indexPath, indexMapping, bleve.Config.DefaultIndexType, goleveldb.Name, nil)
                if err != nil {
                        log.Fatal(err)
                }
```

What I'm trying is:

1.  `$ rm -rf beer-search.bleve/`
2.  `$ ./beer-search`

Then while it's building the index I'm just pressing "search" over and over again in the UI to run a match search.  I'm not seeing any errors return in the browser console, or in the terminal.

Are there any other changes in your code, or details about what you're doing to that might help me reproduce this?

**Comment by nekrondev** [comment]
Marty, thanks for your pointer (uninitialized var was the solution). Ashes on my own, I somehow modified beer-search to use beerIndex, err := instead of beerIndex, err =  ... in the if err == bleve.ErrorIndexPathDoesNotExist part using a nil var for the main search thread while indexing goroutine used a local beerIndex instance.

Anyway, thanks for your investigation and help, I am very sorry to occupied your time with this!

Cheers,
Nek.

**Comment by mschoch** [comment]
Hey no problem, glad we got it figured out.
