### ISSUE TITLE
readonly option doesn't work

### ISSUE THREAD

**Issue by testhmaa** [blevesearch/bleve#405]
i was testing your  https://github.com/blevesearch/bleve-hosted

since the index is just being served read-only, 2 or more apps can share the index 
However, if i start 2 instances from the same directory, giving different port number, only 1 succeeds and other  instance hangs till the first one dies.
After basic digging, found that the lock is somewhere in the core application/library

actually behavior should be 2 or more instances should be able to serve same index ( of course for load-sharing or whatever).

Please tell me if my testing is wrong or something else that can be used to share same index between 2 or more instances in read-only mode

**Comment by mschoch** [comment]
I think not all the KV stores support the "read_only" option right now.  At the time bleve-hosted was built, I was only testing it with the goleveldb adapter.

Can you confirm which KV store you're using?

**Comment by testhmaa** [comment]
I am testing the default goleveldb, no tuning

**Comment by testhmaa** [comment]
Boltdb has this feature. documentation from https://github.com/boltdb/bolt    says

> Sometimes it is useful to create a shared, read-only Bolt database. To this, set the Options.ReadOnly flag when opening your database. Read-only mode uses a shared lock to allow multiple processes to read from the database but it will block any processes from opening the database in read-write mode.

**Comment by mschoch** [comment]
The default is boltdb, not goleveldb.  And yes I understand that bolt also supports this feature.  It is the bleve wrapper code, which does not enable it.  It is probably 5 line fix, plus a test.

**Comment by Losses** [comment]
@mschoch The same bug is still there, using default Boltdb, open the first instance with readonly mode, the second instance with `"read_only": false`, the program hangs while the second db running...

**Comment by mschoch** [comment]
The read-only capability of Bleve, when using the upsidedown index type (default) is provided by the underlying K/V store.  This support sometimes has limitations.  In the case of BoltDB, the documentation is clear:

https://github.com/etcd-io/bbolt#read-only-mode

When opening BoltDB in read-only mode, a shared-lock is acquired.  This means you could have many instances open the index in read-only mode at the same time, but NO process will be able to open it in read-write mode until all the read-only instances have exited.

The situation isn't yet any better with the scorch index-type, but there is hope to fix it one day (still uses BoltDB internally for managing some metadata).  Essentially, Bleve was not designed to support multiple processes working with the index data.  It's something we can eventually fix, but it requires many other things be cleaned up first.

**Comment by Losses** [comment]
Hmmm, I'll try another db type, thanks for your reply!

**Comment by Losses** [comment]
@mschoch Sorry but another question, could this be solved by changing to another existed K/V storage solution?

**Comment by mschoch** [comment]
While I think it might be possible for an alternate K/V store to support what you want, I don't know of any that actually do.

As I said earlier, Bleve was designed with the assumption that only a single process could directly access the index.  It's fair to criticize that assumption, but it doesn't change the reality at the moment.  The alternatives I'm aware of are to use inter-process-communication to access the index from other processes, or to only open the indexes for writing briefly, then close and copy them for the other processes to query.

Longer-term this can be fixed in bleve/scorch.  I have an experimental new library that does locking at the individual file level, allowing multiple read processes at the same time as a single writer process, but this code won't be release for several more months.

**Comment by Losses** [comment]
> While I think it might be possible for an alternate K/V store to support what you want, I don't know of any that actually do.
> 
> As I said earlier, Bleve was designed with the assumption that only a single process could directly access the index. It's fair to criticize that assumption, but it doesn't change the reality at the moment. The alternatives I'm aware of are to use inter-process-communication to access the index from other processes, or to only open the indexes for writing briefly, then close and copy them for the other processes to query.
> 
> Longer-term this can be fixed in bleve/scorch. I have an experimental new library that does locking at the individual file level, allowing multiple read processes at the same time as a single writer process, but this code won't be release for several more months.

Yeah, thanks for you precious insight, there're a lot of trade off while designing a program so there's nothing should be criticized, I'll try to find a way to achieve what we need, try my best.
