### ISSUE TITLE
TopNCollector unsuitable for retrieving all hits

### ISSUE THREAD

**Issue by mmindenhall** [blevesearch/bleve#408]
Sorry I can't dig in and provide more info right now, but commit 24a2b57 introduced a bug that causes the Search function to hang and never return (it works with previous commit).  I'm using an in-memory index (gtreap), and am doing the following:

1.  Creating the in-memory index with an index mapping that includes a DateTimeMapping field.
1.  Batch index some documents using the mapping.
1.  Create a search request with `bleve.NewDateRangeInclusiveQuery`.
1.  Execute the search -- it hangs until the test times out.

If I can, I'll try to write a test later tonight to reproduce the problem.

**Comment by mschoch** [comment]
Yeah, if you can provide a test that would be great.

As I indicated in this message (https://groups.google.com/d/msg/bleve/GxGBZ0FM6pM/hJpv7fgdAQAJ) bleve master is going to be a bit unstable for a while, and you should most likely switch to a more stable release.

**Comment by mschoch** [comment]
I've been trying to reproduce this bug, but so far have been unsuccessful.  Here is my test case, it indexes 10000 docs with a date which some some random offset from the current time.  Then we create 10 query workers, and feed them 10000 queries, which search from random endpoints offset from the current time.  It takes over 3 minutes on my machine, but does not hang.

```
func TestBug408(t *testing.T) {

	m := NewIndexMapping()
	m.DefaultMapping = NewDocumentStaticMapping()
	m.DefaultMapping.AddFieldMappingsAt("created", NewDateTimeFieldMapping())

	index, err := New("", m)
	if err != nil {
		t.Fatal(err)
	}

	sdate := time.Now()
	// index docs with dates some random offset from now
	for i := 0; i < 10000; i++ {
		doc := map[string]interface{}{}
		offset := rand.Int63()
		created := sdate.Add(time.Duration(offset))
		doc["created"] = created
		err := index.Index(fmt.Sprintf("%d", i), doc)
		if err != nil {
			log.Fatal(err)
		}
	}

	requests := make(chan *SearchRequest, 10000)

	// create 10 query workers
	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func() {
		OUTER:
			for {
				select {
				case r, ok := <-requests:
					if !ok {
						// close channel becomes nil channel
						requests = nil
					}
					_, err = index.Search(r)
					if err != nil {
						log.Fatal(err)
					}
				default:
					break OUTER
				}
			}
			wg.Done()
		}()
	}

	// build requests and put on buffered channel
	for i := 0; i < 10000; i++ {
		startOffset := -rand.Int63()
		endOffset := rand.Int63()
		start := sdate.Add(time.Duration(startOffset))
		end := sdate.Add(time.Duration(endOffset))
		startString := start.Format("2006-01-02")
		endString := end.Format("2006-01-02")
		include := true
		q := NewDateRangeInclusiveQuery(&startString, &endString, &include, &include)
		req := NewSearchRequest(q)
		requests <- req
	}

	wg.Wait()
}
```

**Comment by mschoch** [comment]
Hey @mmindenhall, I was thinking about this some more.  Do you know if it was possible that the query than hangs was (or included) a conjunction query?

**Comment by mmindenhall** [comment]
Hi @mschoch, the initial bug was reported against a single DateRangeQuery, but the failure is happening also with a TermQuery.  I probably could have written a test for this from scratch faster, but I took our data type and document mapping, then started paring it down to the simplest possible variant that still fails.

I've distilled this down into a pretty simple test that hangs with commit 24a2b57, but succeeds with the previous commit.

```go
package main

import (
	"math"
	"strconv"
	"testing"

	"github.com/blevesearch/bleve"
)

func TestBug408(t *testing.T) {
	type TestStruct struct {
		Id     string  `json:"id"`
		UserId *string `json:"user_id"`
	}

	docMapping := bleve.NewDocumentMapping()
	docMapping.AddFieldMappingsAt("id", bleve.NewTextFieldMapping())
	docMapping.AddFieldMappingsAt("user_id", bleve.NewTextFieldMapping())

	indexMapping := bleve.NewIndexMapping()
	indexMapping.DefaultMapping = docMapping

	index, err := bleve.New("", indexMapping)
	if err != nil {
		t.Fatal(err)
	}

	numToTest := 10
	matchUserId := "match"
	noMatchUserId := "no_match"
	matchingDocIds := make(map[string]struct{})

	for i := 0; i < numToTest; i++ {
		ds := &TestStruct{"id_" + strconv.Itoa(i), nil}
		if i%2 == 0 {
			ds.UserId = &noMatchUserId
		} else {
			ds.UserId = &matchUserId
			matchingDocIds[ds.Id] = struct{}{}
		}
		err = index.Index(ds.Id, ds)
		if err != nil {
			t.Fatal(err)
		}
	}

	cnt, err := index.DocCount()
	if err != nil {
		t.Fatal(err)
	}
	if int(cnt) != numToTest {
		t.Fatalf("expected %d documents in index, got %d", numToTest, cnt)
	}

	q := bleve.NewTermQuery(matchUserId).SetField("user_id")
	searchReq := bleve.NewSearchRequestOptions(q, math.MaxInt32, 0, false)
	t.Log("===== Before executing index.Search")
	results, err := index.Search(searchReq)
	if err != nil {
		t.Fatal(err)
	}
	t.Log("===== After executing index.Search")
	if int(results.Total) != numToTest/2 {
		t.Fatalf("expected %d search hits, got %d", numToTest/2, results.Total)
	}

	for _, result := range results.Hits {
		if _, found := matchingDocIds[result.ID]; !found {
			t.Fatalf("document with ID %s not in results as expected", result.ID)
		}
	}
}
```

**Comment by mschoch** [comment]
Excellent, I can reproduce this locally now.  Thanks!

**Comment by mschoch** [comment]
Oh, I see the problem.  It's not hung, it's allocating RAM.  We now pre-allocate all the ram we need at one time for the search.  You pass math.MaxInt32 because you want all the results, but this allocates way more RAM than is actually required....

**Comment by mschoch** [comment]
I think what we may have to do is introduce something like an AllHitsCollector which is designed to better support that case.

**Comment by mschoch** [comment]
The TopNCollector introduced by commit 24a2b57 avoids doing any RAM allocation during a search by pre-allocating enough DocumentMatch structs to accommodate the results.  Unfortunately, users that pass very large values for the Size of the SearchRequest (like math.MaxInt32) will attempt to allocate unnecessarily large blocks of RAM.  This may even appear to hang the process as the runtime attempts to satisfy the request.

**Comment by mschoch** [comment]
Actually, I think we can tune the logic slightly to handle both cases.  There are 2 data structures internally that right now we size based on the following:

```
size+skip+(amount needed for search execution)
```

These are the slice backing the result set, and DocumentMatchPool.  In both cases, we could cap the "size" at some other constant, lets say 1000.  That way, actual searches for top hits have 0 allocations, and don't need to grow the backing slice.  But, users that request *all* hits have to pay for allocations and reslicing (as necessary to accommodate the actual result set size).  They were already paying that price before, so it shouldn't be significant change.
