### ISSUE TITLE
bo.ReadOnly undefined when "go getting"

### ISSUE THREAD

**Issue by fetmar** [blevesearch/bleve#413]
```shell
$ go get github.com/blevesearch/bleve
# github.com/blevesearch/bleve/index/store/boltdb
../../github.com/blevesearch/bleve/index/store/boltdb/store.go:65: bo.ReadOnly undefined (type *bolt.Options has no field or method ReadOnly)
../../github.com/blevesearch/bleve/index/store/boltdb/store.go:74: bo.ReadOnly undefined (type *bolt.Options has no field or method ReadOnly)
```
PS - Hi, Marty.

**Comment by mschoch** [comment]
Hi Josh,

I just tried checking out bleve in a clean GOPATH and it seemed to work OK.  Based on the message, my guess is that your version of boltdb is older, and predates the ReadOnly option.

Can you try the adding the `-u` flag?

**Comment by fetmar** [comment]
You're right. I didn't realize I had an older version of BoltDB kicking around. Rookie mistake. Thanks. Hope you're well!
