### ISSUE TITLE
panic during search

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#419]
User upgraded to take advantage of new sorting capability, did call SortBy on the request, and on some of their indexes encountered this panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x44ec67d]

goroutine 56 [running]:
panic(0x47b8260, 0xc82000a0b0)
        /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/blevesearch/bleve/index/upside_down.(*IndexReader).DocumentFieldTerms(0xc820be4120, 0xc820b296b0, 0xf, 0x10, 0xc820b29730, 0x1, 0x1, 0x0, 0x0, 0x0)
        src/github.com/blevesearch/bleve/index/upside_down/index_reader.go:112 +0x61d
github.com/blevesearch/bleve/search/collectors.(*TopNCollector).collectSingle(0xc820da2000, 0xc820eb42d0, 0x6415a20, 0xc820be4120, 0xc820cb2b70, 0x0, 0x0)
        src/github.com/blevesearch/bleve/search/collectors/topn.go:165 +0x21f
github.com/blevesearch/bleve/search/collectors.(*TopNCollector).Collect(0xc820da2000, 0x64045d0, 0xc82000aeb8, 0x65b3a40, 0xc820f3a000, 0x6415a20, 0xc820be412
0, 0x0, 0x0)
        src/github.com/blevesearch/bleve/search/collectors/topn.go:119 +0x3f2
github.com/blevesearch/bleve.(*indexImpl).SearchInContext(0xc820159030, 0x64045d0, 0xc82000aeb8, 0xc820d9c000, 0x0, 0x0, 0x0)
        src/github.com/blevesearch/bleve/index_impl.go:438 +0xab6
github.com/blevesearch/bleve.(*indexAliasImpl).SearchInContext(0xc820d9a000, 0x64045d0, 0xc82000aeb8, 0xc820d9c000, 0x0, 0x0, 0x0)
        src/github.com/blevesearch/bleve/index_alias_impl.go:154 +0x226
github.com/blevesearch/bleve.(*indexAliasImpl).Search(0xc820d9a000, 0xc820d9c000, 0x4896790, 0x0, 0x0)
        src/github.com/blevesearch/bleve/index_alias_impl.go:137 +0x7d
```

**Comment by tmm1** [comment]
The diff was 5f1454106d185...b961d742c1d0331a

**Comment by mschoch** [comment]
I tried reproducing this with a normal code path like:

```
func TestBug419(t *testing.T) {
	index, err := New("", NewIndexMapping())
	if err != nil {
		t.Fatal(err)
	}

	// index a document that has no index or stored fields
	err = index.Index("a", make(map[string]interface{}))
	if err != nil {
		t.Fatal(err)
	}

	// query that matches document a
	q := NewMatchAllQuery()
	req := NewSearchRequest(q)
	// sort by a field not in the document
	req.SortBy([]string{"name"})

	_, err = index.Search(req)
	if err != nil {
		t.Fatal(err)
	}
}
```

But, that was unsuccessful.  It seems that the call to backIndexRowForDoc() returns a nil back index row.  That should only happen if the document doesn't exist... But, the stack trace shows that we found a document match with this doc id, so not finding the back index row would then indicate some sort of transaction isolation issue.

@tmm1 can you report back which KV store you're using?

**Comment by tmm1** [comment]
using the levigo backend

**Comment by mschoch** [comment]
So, there are 2 things:

1) bleve shouldn't panic in this case, but it will need to return an index consistency error
2) we still don't know what causes this...

A few more questions about how you delete?

Do you delete single documents using Delete()? or through a Batch?
Do you check the error value returned by these methods?
Does your application operate in an environment where crashes are likely?

We delete all rows for a document in a single leveldb batch.  The documentation suggests this is atomic (all rows will be deleted, or none).  But these observations suggest this isn't the case.  We have a term row referencing the doc, but no corresponding back index row.

Alternative possibilities are:
- backindex row was never written correctly (also written in what should be atomic batch)
- some other operation damages the index (altering backindex row so that miss a term row to cleanup during delete)

At the moment, we have no leads on the second half of this.  I will submit some changes to address the first half of this.

**Comment by tmm1** [comment]
> Do you delete single documents using Delete()? or through a Batch?

Through a batch, as shown in https://gist.github.com/tmm1/ab6b863fe08e41d280c595e0e8102e73

> Do you check the error value returned by these methods?

No. I can add some error checking on our side.

> Does your application operate in an environment where crashes are likely?

Looks like on the first instance (the one which I provided a copy of the data for), the NOFILE limit was hit repeatedly during deletes and indexing in the days prior to the panic, which is probably what left the index in an inconsistent state.

On a second instance which hit this panic, there was a powerloss event. AFAICT there were no writes being performed for several hours before the power loss, but the panic occurred soon after power was restored so it was probably related.

**Comment by mschoch** [comment]
Moving this from 1.0 to 1.x since we made a change to avoid the panic.

**Comment by steveyen** [comment]
thanks @tmm1 (from 2016) -- with the commit from @mschoch (from 2017) -- and, gonna mark this closed (from 2018)

(would be interesting if the next reopen of this turns up in 2019?  :-) )
