### ISSUE TITLE
Would you please elaborate on why the C/C++ dependencies?

### ISSUE THREAD

**Issue by hgfischer** [blevesearch/bleve#422]
I would like to help on the removal of those C/C++ dependencies and for that, knowing why they are needed instead of Go alternatives, would help. Thanks!

**Comment by mschoch** [comment]
Bleve no longer has any required C/C++ dependencies.  All of the optional C/C++ functionality has been moved to the blevex package.

**Comment by mschoch** [comment]
This has been idle for a week now, so I'm going to close it.  There are some optional modules in blevex that require C/C++.  If you would like specific information about any of them, reopen with more information.
