### ISSUE TITLE
conjunction searcher can call kvstore Iterator.Seek() with a non-forwards key

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#441]
While attempting some performance optimizations around ConjunctionSearcher, I noticed that kvstore Iterator.Seek()'s can be invoked with a seek-to-key that's 'backwards' or less-than the current key.

**Comment by steveyen** [comment]
Hmmm, I think I had bodged up this issue's title and description.  Fixed it to be more clear.

(Previously, I had written that TermFieldReader.Advance() was invoked with a backwards key -- that may not be the case.  Instead, it was more that kvstore Iterator.Seek() was invoked with a backwards key.)

**Comment by mschoch** [comment]
After reviewing closer with @steveyen we agree that the Iterator.Seek() call does allow for going backwards.  However, in this case, its cause was unnecessary, and the change in #442 should prevent iterators from going backwards unnecessarily.  This probably has a minor, but positive impact on all kv stores query performance.
