### ISSUE TITLE
Panic if slice or array includes nil

### ISSUE THREAD

**Issue by slavikm** [blevesearch/bleve#500]
I believe that this line - https://github.com/blevesearch/bleve/blob/master/mapping/document.go#L374 should also check that `!val.Index(i).IsNil()` - otherwise we get a panic in https://github.com/blevesearch/bleve/blob/master/mapping/document.go#L409

**Comment by mschoch** [comment]
Yeah, at first glance it looks like you're right.  I'd like to create a unit test to create the problem before we add a fix though.  I'll try to get to this today.

**Comment by mschoch** [comment]
So, I'm currently unable to reproduce this.  Here is what I've tried:

```
func TestSliceContainingNilBug500(t *testing.T) {
	type Thing struct {
		Name string
	}
	var x *Thing
	tests := []struct {
		Contents []*Thing
		Unknowns []interface{}
	}{
		{
			Contents: []*Thing{
				x,
				nil,
			},
			Unknowns: []interface{}{
				x,
				nil,
			},
		},
	}

	m := NewIndexMapping()
	for _, test := range tests {
		doc := document.NewDocument("x")
		err := m.MapDocument(doc, test)
		if err != nil {
			t.Fatal(err)
		}
	}
}
```

Do you have an actual case that panics?

**Comment by slavikm** [comment]
@mschoch I checked again and it looks like the problem was on our end - memory changed while indexing...
