### ISSUE TITLE
Examples for sorting time.Time fields?

### ISSUE THREAD

**Issue by leeola** [blevesearch/bleve#509]
It seems sorting other fields is a somewhat new feature, and the documentation may be a bit lacking for sorting non-string field types. With that said my current attempts thus far of indexing a time.Time and sorting it have proven unsuccessful.

Would it be possible to provide an example of how one might index, and then query with a sort on this time.Time field?

For reference, my document mapping is non-existent *(which may be the cause)*, and i tried explicitly setting the default mapping to include my datetime field. I've also tried sorting my search by specifying both the `searchReq.SortBy([]string{"datetimeField"})`, as well as by defining a custom SortField to specify the time, eg:

```
searchReq.SortByCustom(search.SortOrder{
  &search.SearchField{
    Field: "datetimeField",
    Type: search.SortFieldAsDate,
})
```

Any examples of what i'm likely doing wrong would be greatly appreciated!

**Comment by leeola** [comment]
Oh and because the problem likely is due to my mapping, here is the simple mapping i'm working with:

```
		docMap := bleve.NewDocumentMapping()
		uploadedAtMapping := bleve.NewDateTimeFieldMapping()
		docMap.AddFieldMapping("uploadedAt", uploadedAtMapping)

		mapping := bleve.NewIndexMapping()
		mapping.DefaultMapping = docMap
```

**Comment by mschoch** [comment]
Hello,

Sorry you're having problems.  I put together this example real quick.
It's not the best code, but uses your mapping, indexes 3 docs with
different dates, and shows a MatchAll query returning the docs in ascending
and descending date order.

https://gist.github.com/mschoch/19767c439466bcbeb138008f6c3ac0b3

If you have more questions about this let me know.

marty

**Comment by leeola** [comment]
Thanks, really appreciate it! I didn't suspect it was the fault of Bleve, but not being sure on my implementation, i was having difficulty confirming.

Your example works for me, and is oddly enough the same *(that i can tell)* as mine. So i'll continue to investigate. Really appreciate the example!

**Comment by leeola** [comment]
For future Googlers, my issue was as follows:

The timestamp being indexed was being converted to a string before being indexed. This resulted in the mapping to not index it correctly *(or so it seems)*. After correctly writing the time.Time object, Bleve works as intended.

Thanks again! Bleve has been very enjoyable 👍
