### ISSUE TITLE
Switching from Elasticsearch to Bleve

### ISSUE THREAD

**Issue by barthr** [blevesearch/bleve#519]
I'm currently researching how bleve can replace our current setup at work. We have all of our services written in Go, but for one service we use elasticsearch to do the searching. 

But elasticsearch is very heavy in running, all of our services are really low in resource usage but the database hits some serious peaks when querying. I was wondering how it would be to run this with bleve. I made some example projects with bleve, and I liked the way how it works. 

Everyday we receive around 500k records in the database, those get cleaned after 1 - 2 days. Is it possible to do this with bleve + boltdb (or rocksdb). We use range query's to keep the amount of data retrieved with each query low.

Any thoughts? 

Also I would love to contribute, drop me a line on where help is needed.

**Comment by mschoch** [comment]
So, this comes up from time to time.  The first thing is that Bleve is just a library whereas Elasticsearch is an application.  

Do you want to build a general-purpose search application like Elasticsearch?  Probably not, that would be a huge project.  At my employer we've undertaken the effort of building a distributed search service on top of Bleve, and it's a lot of work.  See https://github.com/couchbase/cbft

But, if you just want to build a special-purpose service to suit your needs, it might be possible.

1) There is nothing too problematic with 500k records, our nightly tests build indexes on a dataset of 200k records.
2) Cleaning up a rolling set of data (like purge after 1-2 days) is best accomplished by creating separate index shards for some granularity (say every 6 hours).  Then you can use MultiSearch/IndexAlias to search across them easily, but close/delete them when no longer needed.

The real challenge is the distributed nature of elasticsearch.  It allows you to scale your load across multiple nodes, and also improve reliability by have replica copies of the index.  If a single node can handle your load, you might be able to simplify things by just running multiple instances to get reliability without any complex distributed system logic.  But you'll have to do some experiments to know (and you also run the risk of out-growing that in the future).

**Comment by barthr** [comment]
Thanks for your comment. I'm aware of the fact that bleve isn't a full solution compared to elasticsearch. Currently we aren't using the power of what elasticsearch can give us and we don't actually need it. I'm going to rewrite the querying part to bleve + rocksdb and see how it will perform on our test environment. All the query types are almost the same so that should be no problem, i'm really curious to try this in production.

I will run some tests and let you know! 

Besides that keep up the good work. I really like this project, and looking forward to contribute!

**Comment by mschoch** [comment]
So, my one piece of caution is that due to the architecture of Bleve, none of the C based KV stores will perform well for searching.  We focused for a long time on indexing performance, and didn't realize this limitation until very late.

The reason for the problem is that our search behavior requires invoking a KV store iterator `Next()` method repeatedly.  When using a C based KV store, this is paying the cgo performance penalty.  There is no straightforward way to avoid this without completely rearchitecting the way the index is laid out.

So, for people concerned with both indexing and search performance, I now only recommend you consider pure Go KV stores (moss-store is currently the fastest)

**Comment by barthr** [comment]
I think I will stick with bolt for now to see how it will work out. Thanks for your feedback
