### ISSUE TITLE
search against multiple fields

### ISSUE THREAD

**Issue by porjo** [blevesearch/bleve#540]
It seems I can either search against all fields or one specific field. I'd like to specify several fields to search against. For example, I do this currently:
```go
q := query.NewMatchQuery("foobar")
q.SetField("bbb")
```
It would make sense to have a `SetFields` method and use it like this: 
```go
q.SetFields([]string{"bbb", "ccc"})
```
A workaround is to search on all fields then filter the results by matched location.

**Comment by bobinette** [comment]
Hello,

I think you can play with conjunctions and disjunctions query. For example if you want the documents that match `foobar` on fields `bbb` **and** `ccc` you could write:
```go
bbb := query.NewMatchQuery("foobar")
bbb.SetField("bbb")

ccc := query.NewMatchQuery("foobar")
ccc.SetField("ccc")

q := query.NewConjunctionQuery(bbb, ccc)
```

**Comment by porjo** [comment]
Thankyou, that solves my problem. In my case I needed to use `NewDisjunctionQuery` to match any of the supplied fields, rather than all.
