### ISSUE TITLE
Lost stemmer_xx no token filter registered (was working..)

### ISSUE THREAD

**Issue by lundin** [blevesearch/bleve#542]
Hi!

I have an existing index build upon very old blevesearch repo (2015) in an application which now fails to start, either creating a new index or query the existing one.

It started to fail after updating to GO 1.7 and go get a blevesearch (however i have now switched back to the old branch of bleve (i just renamed the old version before go get) and GO 1.3) however the app now fails to start.

For example when trying to build an index it fails:

```
error building analyzer: no token filter with name or type 'stemmer_sv' registered
error building analyzer: no token filter with name or type 'stemmer_sv' registerederror building analyzer: no token filter with name or type 'stemmer_fr' registerederror building analyzer: no token filter with name or type 'stemmer_en' registerederror building analyzer: no token filter with name or type 'stemmer_de' registerederror building analyzer: no token filter with name or type 'stemmer_it' registerederror building analyzer: no token filter with name or type 'stemmer_es' registeredpanic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x465afd]
```

And when i try to do a simple MatchAll query
```
error building analyzer: no token filter with name or type 'stemmer_sv' registeredpanic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x44801d]
```

In my centos 7 i have
libstemmer-0-2.585svn.el7.x86_64

Is there any way to "rebuild" it or do you have any tip on what might have happend here ?

Many thanks for any insight!

**Comment by mschoch** [comment]
Normally when you get the message of the form:

```
no token filter with name or type 'XXXX'
```

It means that you're referring to `XXXX` as a string in your source, and that is no longer recommended, as it can lead to the problems observed here.  Instead, you should import the package containing that definition, and refer to exported string (usually exported in the variable `Name`)

In the case of 'stemmer_sv', it it would now be done by importing:

github.com/blevesearch/blevex/lang/sv

And then referring to `sv.StemmerName` in your code.  The benefit of this approach is that it ensures you import the package containing the code (which registers itself via an init method).

The `sv` package may have also moved once or twice, so you'll have to pick a version of bleve, and find it either in bleve or blevex.

There may then be other problems, but I would first start with this and see where it gets you.

**Comment by lundin** [comment]
Hi Marty!

Thanks for your comments, i agree, however this bleve version is really old, even before the belevx package was created and even versioning. So in language folder there is this stemmer_sv.go which register itself on init.

So with this package i created the index with string names "stemmer_sv" etc. 
So it have worked since then.

Yesterday i installed Go 1.7 and go get a new blevesearch package. However i renamed the old blevesearch before and kept in in my GOPATH. I then revered back to 1.3 and the put back the old blevesearch but somehow i am now unable to run the same app with the index. It fails to reckon the stemmer. Isnt that strange ? I rebuild the application with Go 1.7 and the new bleve so somehow it seems that it "destroyed" the index or something in that line.

**Comment by mschoch** [comment]
Do you know the bleve SHA of the version that once worked?  Maybe if I look back at that I'll have more ideas.

**Comment by lundin** [comment]
Marty,
Pretty sure this is the one if it helps:
https://github.com/blevesearch/bleve/tree/0771f813ce27f58e001d9ea0ceba1e4afc180146

And it keep saying
error building analyzer: no token filter with name or type 'stemmer_sv' registered

Seems weired that that init function does not register them, has been working until i mixed up either bleve packages or Golnag version and build with flag -a. Did i changed the index somehow if i rebuild my app..which only has queries not creating the index.

Thanks for all the help, much appreciated!

**Comment by mschoch** [comment]
Hmmn, I don't have anything concrete to recommend.  But a couple of things come to mind.

1) your mention of `-a` does remind me that in earlier days, occasionally the .a files under `$GOPATH/pkg` would become stale and not rebuild properly.  In particular it would happen when I would toggle between build flags.  It was as if using different build flags didn't cause Go to realize it couldn't reuse an existing .a file.  So, you might try nuking any .a file under `$GOPATH/pkg/github.com/blevesearch/...`

2) The files in the `sv` package are guarded with the build tags:

`+build libstemmer full`

So, be sure to use either on of these during the build of your program.  Leaving them off would explain why the init functions aren't registering the functionality.

**NOTE:** to anyone else reading this thread, these recommendations are only for this older version of bleve and are not applicable to the current codebase.

**Comment by lundin** [comment]
Marty you are a genius and a lifesaver!! The build tags!

Now i will upgrade the app so all breaking changes that has been made will work with new bleve version.

Many many thanks and keep the FTS development in CB up as well..awesome work =)

Closing this issue.
