### ISSUE TITLE
'ansi' highlighter not registered

### ISSUE THREAD

**Issue by DrakeW** [blevesearch/bleve#554]
The indexing and search part of bleve worked perfectly for me, but when I added highlighter to my search request the error message showed `no highlighter with name or type 'ansi' registered`. 

I tried to set up a few break points on the package and it turned out that the `init()` function in blevesearch/bleve/search/highlight/highlighter/ansi/ansi.go is never called. 
However, the the two `init()` in `html.go` and `highlighter_simple.go` were called normally. And weirdly once I replaced the content of `html.go` with that of `ansi.go`, the ansi highlighter was registered. So that proved the code in `ansi.go` works.

And I checked blevesearch/bleve/config/config.go and it seemed all three highlighters were imported...

Please let me know if you need further information :)

**Comment by DrakeW** [comment]
adding this line to my own file fixed the problem though
```
import (
  _ "github.com/blevesearch/bleve/config"
)
```
which makes me wonder if this is what I'm supposed to import..?

**Comment by mschoch** [comment]
Sorry for the delay in responding.  A while back we decided to make importing "github.com/blevesearch/bleve" only import the minimal set of functionality to operate.  In a lot of ways this makes sense as, it lets users operate in a lean environment when necessary, and it lets power users import additional functionality as needed.

As a part of this change, the default config only includes the HTML hightlighter.  To get the "ansi" highlighter you must import a specific package.

You can either import this directly, if you know this is all your application needs.  Or you can import "github.com/blevesearch/config" which automatically imports many packages, and adds support for importing optional packages through a common set of build tags.

I hope this explanation helps, if you have more questions let me know.
