### ISSUE TITLE
Please Annotate Release Tags

### ISSUE THREAD

**Issue by MTecknology** [blevesearch/bleve#559]
This package is used heavily by Gitea which means I have an interest in getting Bleve included in Debian. While working through this package, I saw that tags are used to mark releases, but they are not being annotated.

This causes some headaches for packaging systems that monitor upstream activity (for new releases) because the information is missing from 'git describe'. To annotate a tag, it just needs the -a flag passed. (git tag -a).

It's possible to update the current 0.5.0 tag, if you're willing, but more importantly, could you please include the annotation for future releases?

Couple resources if you're willing to update the previous tag(s):
http://stackoverflow.com/questions/5002555/can-a-lightweight-tag-be-converted-to-an-annotated-tag
http://sartak.org/2011/01/replace-a-lightweight-git-tag-with-an-annotated-tag.html

**Comment by mschoch** [comment]
Yes we'll try to do this going forward.

**Comment by MTecknology** [comment]
Excellent, thanks!

**Comment by mschoch** [comment]
Version v0.6.0 has just been released and I used an annotated tag this time.  Let me know there are still problems with the way I'm doing it.

**Comment by MTecknology** [comment]
It looks great. Thanks again for the extra work!
