### ISSUE TITLE
Email text field and NewTermQuery

### ISSUE THREAD

**Issue by sAbakumoff** [blevesearch/bleve#568]
I am planning to use Bleve to index the data in my app and since there are different types of data, I think that Documents Mapping would satisfy the requirements I have in mind. One of the tasks I will need to be able to perform is finding a user my email. Since I need the exact match, I thought that Term query should be used because according to documentation

> It performs an exact match in the index for the provided term.

  Here is the sample of code:

```golang
func buildMapping() mapping.IndexMapping {

	textFieldMapping := bleve.NewTextFieldMapping()
	textFieldMapping.Analyzer = en.AnalyzerName

	userMapping := bleve.NewDocumentMapping()
	userMapping.AddFieldMappingsAt("Email", textFieldMapping)

	indexMapping := bleve.NewIndexMapping()
	indexMapping.TypeField = "Type"
	indexMapping.DefaultAnalyzer = "en"
	indexMapping.AddDocumentMapping("user", userMapping)

	return indexMapping
}

var indexPath = flag.String("index", "index.bleeve", "index path")

func main() {
	flag.Parse()
	defer os.RemoveAll(*indexPath)
	bleveIndex, err := bleve.Open(*indexPath)

	if err == bleve.ErrorIndexPathDoesNotExist {
		bleveIndex, err = bleve.New(*indexPath, buildMapping())
		if err != nil {
			log.Fatal(err)
		}
	}

	err = bleveIndex.Index(uuid.New().String(), struct {
		Email string
		Type  string
	}{Email: "u1@code.com", Type: "user"})
	if err != nil {
		panic(err)
	}

	query := bleve.NewTermQuery("u1@code.com")
	query.SetField("Email")
	searchRequest := bleve.NewSearchRequest(query)
	searchRequest.Highlight = bleve.NewHighlight()
	searchResults, err := bleveIndex.Search(searchRequest)
	if err != nil {
		panic(err)
	}

	fmt.Println(searchResults)
}
```

This program prints "No matches", but if the I modify it so that query initialized like ```query := bleve.NewMatchQuery("u1@code.com")``` then the match is found and printed:
![image](https://cloud.githubusercontent.com/assets/769109/24603191/040d833a-188a-11e7-9df0-bfdb14897bb8.png)
But the "match" query is not suitable because it also finds any email with "code.com" domain. I thought that @ could be special symbol that should be escaped, but it's not mentioned in the documentation. So, what I am missing?

**Comment by bobinette** [comment]
Hello,

I think you should specify the `keyword` [analyzer](https://github.com/blevesearch/bleve/blob/master/analysis/analyzer/keyword/keyword.go) for the `email` field, to prevent it form being analyzed when indexing, like
```go
emailFieldMapping := bleve.NewTextFieldMapping()
emailFieldMapping.Analyzer = keyword.Name

userMapping := bleve.NewDocumentMapping()
userMapping.AddFieldMappingsAt("Email", emailFieldMapping)
```

You can head [here](http://www.blevesearch.com/docs/Analyzers/) for a bit more information

**Comment by sAbakumoff** [comment]
Thanks for sending the prompt response! I tried that, but now the program fails with the following message

> 2017/04/03 16:48:10 no analyzer with name or type 'keyword_marker' registered
