### ISSUE TITLE
Interesting behavior of "match" query

### ISSUE THREAD

**Issue by sAbakumoff** [blevesearch/bleve#574]
Hi,
I observe the behavior that can be reproduced by using the following code

```golang
func buildMapping() mapping.IndexMapping {

	keywordMapping := bleve.NewTextFieldMapping()
	keywordMapping.Analyzer = keyword.Name

	enTextMapping := bleve.NewTextFieldMapping()
	enTextMapping.Analyzer = "en"

	orgMapping := bleve.NewDocumentMapping()
	dataMapping := bleve.NewDocumentMapping()
	orgMapping.AddSubDocumentMapping("Data", dataMapping)
	dataMapping.AddFieldMappingsAt("Name", enTextMapping)
	orgMapping.AddFieldMappingsAt("Type", keywordMapping)

	indexMapping := bleve.NewIndexMapping()
	indexMapping.TypeField = "Type"
	indexMapping.AddDocumentMapping("org", orgMapping)
	return indexMapping
}

var indexPath = flag.String("index", "index.bleeve", "index path")

func main() {
	flag.Parse()
	defer os.RemoveAll(*indexPath)
	bleveIndex, err := bleve.Open(*indexPath)

	if err == bleve.ErrorIndexPathDoesNotExist {
		bleveIndex, err = bleve.New(*indexPath, buildMapping())
		if err != nil {
			log.Fatal(err)
		}
	}
	rawJson := json.RawMessage(`{"Name":"Apple Inc"}`)
	var data interface{}
	if err = json.Unmarshal(rawJson, &data); err != nil {
		panic(err)
	}

	bleveIndex.Index("orgId", struct {
		Type string
		Data interface{}
	}{Type: "org", Data: &data})

	for _, queryStr := range []string{`{"match" : "Apple"}`, `{"match" : "Inc"}`} {
		q1, err := query.ParseQuery([]byte(queryStr))
		if err != nil {
			panic(err)
		}
		q2 := bleve.NewTermQuery("org")
		q2.SetField("Type")
		query := bleve.NewConjunctionQuery(q1, q2)
		searchRequest := bleve.NewSearchRequest(query)
		searchRequest.Highlight = bleve.NewHighlight()
		searchResults, err := bleveIndex.Search(searchRequest)
		if err != nil {
			panic(err)
		}
		fmt.Println(searchResults)

	}
}
```
the output is:
![image](https://cloud.githubusercontent.com/assets/769109/24704355/7c70a322-1a31-11e7-935a-32c3ff902c30.png)

So, {"match":"Apple"} query doesn't find anything, but {"match" : "Inc"} does find  the "Apple Inc" string which had been indexed..
I am not sure why it happens, could anyone explain it please?

**Comment by mschoch** [comment]
So, the mapping is indexing things pretty as you expected.  The tokens in the index for the Data.Name field are:

appl
inc

However, when you run the query, the query doesn't restrict itself to a field, so the search is taking place on the _all field.  And although you specified the analyzer to use for particular fields, you didn't changed the default analyzer, so the query is using the "standard" analyzer.  But, this analyzer produces the tokens: apple, inc.

So, that is why the search for "Inc" matches, but "Apple" does not.

The simplest way to fix it your case is to add the line:

    indexMapping.DefaultAnalyzer = "en"

This sets the default analyzer to match how you've indexed the other fields, which then lets searches on the "_all" field work correctly.

**Comment by mschoch** [comment]
Also, I wanted to mention that they way I debugged this was to use the bleve dump command.

1. comment out code which deletes the index
2. run the command
    bleve dump ./index.bleeve 
3. look at the tokens listed  (seeing appl let me realized the data was getting indexed correctly and that the problem was on the search side)

**Comment by sAbakumoff** [comment]
Thank a ton! I really appreciate the instant replies I have been receiving for all my noob  questions.
