### ISSUE TITLE
Processor intensive batch indexing

### ISSUE THREAD

**Issue by japettyjohn** [blevesearch/bleve#577]
I've got a few thousands HTML web pages I'm scraping and indexing which I think should be pretty quick and not too intensive.

What I'm seeing is in batches of 100, between 0.5 and 1 MB of content, I'm seeing it fluctuate between 1 second and 30 seconds to index. Getting up full CPU utilization on 8 cores.

I've seen this with CentOS6 and macOS, go 1.6, 1.7 and 1.8.

While I am doing 15 languages, I'm seeing this from English to Swedish and Japanese to Spanish.

Analyzers in play are the Simple and Keyword analyzer and language loaded are EN and CJK.

KVStore is boltdb. Same thing is happening across a single solid state as is happening on raided HDD.

Not sure where else to look for tuning issues.

**Comment by mschoch** [comment]
On most systems the disk gets saturated long before the CPU gets to 100% so your observations are a bit surprising.

That being said, BoltDB ultimately isn't going to give you the indexing performance you want.

**Comment by mschoch** [comment]
I'd recommend giving the moss storage engine a shot, but its not very well documented at the moment.

**Comment by mschoch** [comment]
Another suggestion is to simplify what you're trying to do at first.  You mention 15 languages, several different analyzers, and 0.5-1MB of content (not clear if this is per-batch or per-document).

If you can share a small example of code, bleve mapping and source documents that reproduce the problem, that is the fastest way to get support.

**Comment by japettyjohn** [comment]
Thanks a lot for the suggestion. I've started testing moss, but in doing so I found the issue sourced from the pages themselves. Some bad regexp go inserted onto every page and it was burning the CPU.
