### ISSUE TITLE
about grouping

### ISSUE THREAD

**Issue by hengwei-ly** [blevesearch/bleve#582]
Can bleve group by specified query  ?

**Comment by mschoch** [comment]
Can you give more details about what you're trying to do, or perhaps give an example?

**Comment by hengwei-ly** [comment]
Very glad to receive your reply . 
Now I have thousands of datas and I want to group them in three(or more) time periods,Here's my code:

        query := bleve.NewMatchAllQuery()
	searchRequest := bleve.NewSearchRequest(query)

	start, _ := time.Parse("2006-01-02 15:04:05", "2017-04-20 7:05:00")
	end1, _ := time.Parse("2006-01-02 15:04:05", "2017-04-20 7:10:00")
	end2, _ := time.Parse("2006-01-02 15:04:05", "2017-04-20 7:15:00")
	end3, _ := time.Parse("2006-01-02 15:04:05", "2017-04-20 7:20:00")

	facet1 := bleve.NewFacetRequest("reception", 1)
	facet1.AddDateTimeRange("date1", start, end1)
	searchRequest.AddFacet("dateRange1", facet1)

	facet2 := bleve.NewFacetRequest("reception", 1)
	facet2.AddDateTimeRange("date2", start, end2)
	searchRequest.AddFacet("dateRange2", facet2)

	facet3 := bleve.NewFacetRequest("reception", 1)
	facet3.AddDateTimeRange("date3", start, end3)
	searchRequest.AddFacet("dateRange3", facet3)

	searchRequest.Size = 10000
	searchResults, err := index.Search(searchRequest)
	//fmt.Println(searchResults.Facets["dateRange"])
	for k, v := range searchResults.Facets {
		fmt.Println(k, ":",v.Total)
	}
So,is there some simple and effective ways?

**Comment by mschoch** [comment]
OK, so the code you have is close.  I think what you want is to have a single facet request for the field, and then have 3 date ranges defined for that.  So the updated code would look more like:

```
query := bleve.NewMatchAllQuery()
searchRequest := bleve.NewSearchRequest(query)

start, _ := time.Parse("2006-01-02 15:04:05", "2017-04-20 7:05:00")
end1, _ := time.Parse("2006-01-02 15:04:05", "2017-04-20 7:10:00")
end2, _ := time.Parse("2006-01-02 15:04:05", "2017-04-20 7:15:00")
end3, _ := time.Parse("2006-01-02 15:04:05", "2017-04-20 7:20:00")

facet := bleve.NewFacetRequest("reception", 1)
facet.AddDateTimeRange("date1", start, end1)
facet.AddDateTimeRange("date2", start, end2)
facet.AddDateTimeRange("date3", start, end3)
searchRequest.AddFacet("dateRange", facet)

searchRequest.Size = 10000
searchResults, err := index.Search(searchRequest)
//fmt.Println(searchResults.Facets["dateRange"])
for k, v := range searchResults.Facets {
	fmt.Println(k, ":",v.Total)
}
```

The idea is that you have a single field "reception" with date values.  And you have created 3 date ranges that you care about (date1, date2, and date3).  The facet request will count up how many documents have reception dates that fall into each range.

If this still doesn't produce the results you want, can you create a small self-contained example that indexes a few documents like the ones you use, and we can try to work on getting that example to work.

**Comment by hengwei-ly** [comment]
Thank you very much for your explanation. I want to record every 5 minutes within 12 hours, so there will be 720 groups This is another bit of memory loss. but I can not find a good way. Now I can finish it. Thanks again.

**Comment by hengwei-ly** [comment]
I tried your way, but I couldn't get the right result.
I want to record number every 5 minutes within 12 hours, so I will get 720 groups.I tried :
query := bleve.NewMatchAllQuery()
	searchRequest := bleve.NewSearchRequest(query)
	endtime := time.Unix(time.Now().Unix()+60*60*8, time.Now().Unix()+60*60*8*1000)

	for i := 1; i <= 15; i++ {                                        // there will be 720 groups.
		extime1 := endtime.Unix() - 60*int64(i)*10
		extime2 := endtime.Unix() - 60*int64(i-1)*10
		start := time.Unix(extime1, extime1*1000)
		end := time.Unix(extime2, extime2*1000)
		facet := bleve.NewFacetRequest("reception", 1)  // dispute code
		facet.AddDateTimeRange("date", start, end)
		searchRequest.AddFacet("dateRange"+strconv.Itoa(i), facet)
	}
It is feasible.
I tried another way：
		facet := bleve.NewFacetRequest("reception", 1)  // dispute code
        for i := 1; i <= 15; i++ {                                        // there will be 720 groups.
		extime1 := endtime.Unix() - 60*int64(i)*10
		extime2 := endtime.Unix() - 60*int64(i-1)*10
		start := time.Unix(extime1, extime1*1000)
		end := time.Unix(extime2, extime2*1000)
		facet.AddDateTimeRange("date", start, end)
		searchRequest.AddFacet("dateRange"+strconv.Itoa(i), facet)
	}
All facets will show the same result ("0") if I do.
I've got what I want in fact, but I want to test if there's a simpler way to do it.
