### ISSUE TITLE
Match entire field value?

### ISSUE THREAD

**Issue by leeola** [blevesearch/bleve#588]
Is it possible for Bleve to match the entire value? Eg, with the following:

```
[
  {
    "field": "foo bar baz",
  },
  {
    "field": "bar",
  }
]
```

I'd like a query to match the object with `bar` but not `foo bar baz`.

**Comment by mschoch** [comment]
Matching things at query time is entirely dependent on how you analyzed the during indexing.

Exact matching can be done, but only if the entire string was indexed as a single token at indexing time.  But, doing that means you can't match "foo".  Sometimes this means you need to index the same source field multiple ways (with 2 different field names).

Alternatively, you could try to match it as a phrase "foo bar baz", that might work in some cases, but is not the same as an exact match.

**Comment by leeola** [comment]
Ah, unfortunate, i'm dealing with a dynamic/schema-less dataset. Appreciate the input, thank you.
