### ISSUE TITLE
Geo JSON support

### ISSUE THREAD

**Issue by tonyalaribe** [blevesearch/bleve#599]
Can bleve be used to make queries on documents based on gps coordinates? For example, in my system, i need to query for businesses that meet a search query, while also sorting based on proximity to a given gps cordinate (The indexed documents, include geojson encoded gps coordinates).

**Comment by mschoch** [comment]
Yes, it's a relatively new feature so there isn't much documentation yet.  The best I can you point you to is some of our integration tests.

You can see documents containing geo points here:

https://github.com/blevesearch/bleve/tree/master/test/tests/geo/data

A mapping with an entry for the `geo` field as type `geopoint` here:

https://github.com/blevesearch/bleve/blob/master/test/tests/geo/mapping.json#L26

And some searches and results here:

https://github.com/blevesearch/bleve/blob/master/test/tests/geo/searches.json

There 2 types of queries supported: bounding box and point distance

And you can optionally sort results based on distance form a point as well.

Let me know if you have more questions.

**Comment by tonyalaribe** [comment]
Thanks @mschoch. I think this fits my use case. I'm let you know if I find any issues.

**Comment by hubyhuby** [comment]
dear @tonyalaribe ,
Did you managed to make the geo search work  on the JSON data provided my Marty ?
If so could you communicate a basic snippet ?
Thanks for your help
