### ISSUE TITLE
Simple REST API

### ISSUE THREAD

**Issue by OmgImAlexis** [blevesearch/bleve#601]
I'd be nice to have a simple REST API for adding documents and searching which would allow other languages to use this similarly to Elastic Search.

**Comment by mschoch** [comment]
Bleve does come with a REST API, see the "http" sub-package for the handlers.

However, in the next major version (bleve 2.x) we'll most likely be removing these as we want to focus on being a library, and let the application layer handle this.

**Comment by steveyen** [comment]
Hi -- with @mschoch's last comment / answer on this, gonna mark this closed.  -- cheers, steve
