### ISSUE TITLE
Does QueryStringQuery supports fuzziness?

### ISSUE THREAD

**Issue by xomaczar** [blevesearch/bleve#606]
Trying to use QueryStringQuery to match partial terms. Trying to lower fuzziness option

**Comment by mschoch** [comment]
Yes it does.  The syntax is term~N, where N is the edit distance.  Going higher than 2 will probably lead to poor performance.

Let's leave this issue open to fix the documentation, which is out of date.  This page needs to be updated.

http://www.blevesearch.com/docs/Query-String-Query/

**Comment by xomaczar** [comment]
Nice thanks. I need fuzziness >= 3 to find "desired" results. Does QueryStringQuery supports regex - term*

**Comment by mschoch** [comment]
Yes, if the text starts and ends with `/` it is interpreted as a regular expression.  You can see some examples in the unit tests:

https://github.com/blevesearch/bleve/blob/master/search/query/query_string_parser_test.go#L624-L647

**Comment by ionrock** [comment]
@mschoch I submit that PR to the docs and I'm happy to iterate on it to make sure it conveys the right meaning. I'd like to point folks there directly over time when working with our app using bleve to save some doc cycles. Let me know what needs to happen to get those docs updated!
