### ISSUE TITLE
how to search by document type

### ISSUE THREAD

**Issue by zannet** [blevesearch/bleve#609]
i have three document types in one index:

> indexMapping := bleve.NewIndexMapping()
> 
> // note mapping
> note := bleve.NewDocumentMapping()
> // message mapping
> message := bleve.NewDocumentMapping()
> // user mapping
> user := bleve.NewDocumentMapping()
> 
> indexMapping.AddDocumentMapping("note", note)
> indexMapping.AddDocumentMapping("message", message)
> indexMapping.AddDocumentMapping("user", user)

how can i search by document type, something like this:

> req := bleve.NewSearchRequest(bleve.NewQueryStringQuery(strings.ToLower(q)))
> **req.Doctype = "note"** // only search note document type
> res, err := index.Search(req)

**Comment by mschoch** [comment]
The type as determined by the index mapping is not indexed, and therefore you cannot search by it.

The workaround if you need to search it is to ensure you have a field containing the type.

**Comment by zannet** [comment]
@mschoch thank, i'll give it a try
