### ISSUE TITLE
open index takes much time using mossStore 

### ISSUE THREAD

**Issue by Darren** [blevesearch/bleve#617]
we lately updated mossStore to master and found that open index took minutes long,
Each time the index is being opened, another data-*.moss file is created for writing, then
the old one is deleted, with index data file size  grows up to 100G, this take too much time.

Disable compaction is not viable, because it will slow down query.

As a workaround, I have to change default CompactionLevelMaxSegments to 2.

moss/store_api.go:
```go
var DefaultStoreOptions = StoreOptions{
	CompactionPercentage:       100.0,
	CompactionLevelMaxSegments: 2,
	CompactionLevelMultiplier:  1024 * 1024 * 1024,
	CompactionBufferPages:      512,
}
```

How can specify these options while opening the index?

**Comment by mschoch** [comment]
ping @steveyen

**Comment by steveyen** [comment]
Hi Dareen -- typing in the reply in untested fashion, but you'll have to initialize with bleve's NewUsing() API, which let's you pass in a kvconfig.  And, the kvconfig should roughly look like (in pseudo-JSON)...

    kvConfig = {
        "path": "/path/to/your/storage/directory",
        "mossLowerLevelStoreName": "mossStore",
        "mossStoreOptions": {
        	CompactionPercentage:       100.0,
        	CompactionLevelMaxSegments: 2,
        	CompactionLevelMultiplier:  1024 * 1024 * 1024,
        	CompactionBufferPages:      512,
        }
    }

Again, I didn't actually test this, so pls lemme know if that doesn't fly.

cheers,
steve
