### ISSUE TITLE
Use old index data with new version of Bleve

### ISSUE THREAD

**Issue by maiorrulz** [blevesearch/bleve#618]
I updated the Bleve version, and encountered with versioning problem. While opening my old index, I'm getting an error `incompatible version, 7 is supported`. 
After revert I found in `upsidediwn.go`  file that I was using version 5. 
Is there way to use updated Bleve with old index data?

**Comment by meirwah** [comment]
@mschoch is there an upgrade path?

**Comment by mschoch** [comment]
Generally no.  The plan has always been that once we reach 1.0, we would freeze the index format, or if changes are necessary to fix bugs, support reading older versions i the 1.x line.

Unfortunately, we still haven't managed to ship 1.0.

So for now, the only solution is to use an older version of bleve that can read that format, or reindex your data with a newer version of bleve.
