### ISSUE TITLE
should Czech language use cs or cz

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#62]
I've been trying to stick to ISO 639 language codes, which according to wikipedia is "cs".  See http://en.wikipedia.org/wiki/Czech_language

However, my source for this stop word list was a "cz" folder in lucene.  See https://github.com/apache/lucene-solr/blob/trunk/lucene/analysis/common/src/resources/org/apache/lucene/analysis/cz/stopwords.txt

This was actually why i hesitated initially on "czech" when I ported all the other language lists.  Eventually I just wanted to get the list ported and argue about the correct code later.  So here we are.

**Comment by mauron85** [comment]
Once czechoslovakia was splitted into Slovakia and Czech Republic. Both country change tlds to .sk and .cz, but for some unclear reason Czech kept the cs (czechoslovakian) code for the language. So country tld is cz but locale is cs.
