### ISSUE TITLE
Facet terms return their analyzed variants

### ISSUE THREAD

**Issue by rikvdh** [blevesearch/bleve#639]
I have the use-case where I want to use the slug or ID of a document as facet. But the returned name is the name as it is passed through the selected analyzer for an index making it unusable to translate back to human-readable forms.

For example, I use the nl.AnalyzerMapping for analyzing my documents, but I have brands of products which I want to use as a facet. Having `foobare` becomes `foobar` and `foos` becomes `foo`.

For my use-case I don't want Bleve to manipulate my facets, I understand the part where you want to make sure that `bar` and `bars` are categorised as a single `bar`, but some names can be for example human names or brand names which must be left intact.

**Comment by mschoch** [comment]
In bleve, the way to have it leave a fields value alone is to use the 'keyword' analyzer on that field.  This will make no changes to the value, and index it exactly.

As you point out, that is good idea for fields you wish to create  a facet on.

If you want to search on a field AND create a facet on it, that is supported as well.  Simply index the source field twice.  For the first one use the analyzer you want for better searching, and for the second one, use 'keyword' and name the field something different, like 'category.facet'.
