### ISSUE TITLE
Question on memory use

### ISSUE THREAD

**Issue by gaillard** [blevesearch/bleve#658]
When using a kv store like bolt, is there anything in the pkg that uses memory in a way that is not controllable, such as memory use being driven by the dataset?

**Comment by mschoch** [comment]
BoltDM use mmap, so depending on which memory stats you look at, the process may appear to use large amounts of memory.  But this memory is managed by the OS and not the application.

Not specific to BoltDB, but a general limitation of the bleve package is that the entire result set of a search must fit into RAM.  In the future we may introduce options to stream results (only useful in cases where you don't need sorting).  Also, complex searches may require a large number of simultaneous iterators into the key/value store.  These each have some cost and it can add up.

**Comment by mschoch** [comment]
Please reopen if your question hasn't been answered.

**Comment by gaillard** [comment]
Just a quick follow up to confirm, the limitation is related to the result set and not effected by the size/from in the searchrequest?

**Comment by mschoch** [comment]
We have to keep size+from matches in memory while determining the final result set, which has size (size).  This tends to matter when users want "all" results and set size to some really large value like 10,000,000.
