### ISSUE TITLE
New release needed, go dep tool failing for 0.5.0.

### ISSUE THREAD

**Issue by dudeskeeroo** [blevesearch/bleve#706]
The blevex project removed blevex/cellar but the latest bleve release (v0.5.0) still has a reference to it.

This means tools like dep will try to incorporate v0.5.0 and subsequently blevex/cellar, which fails because it no longer exists.

bleve Head no longer references Cellar.

For anyone else trying to work around this, you can go get the latest bleve in to your GOPATH and run `dep init -gopath` to make dep use the latest version from your gopath. Not ideal, but it'll get you by.

Cheers!

**Comment by mschoch** [comment]
Version v.0.6.0 hast just been released.
