### ISSUE TITLE
Query values in map

### ISSUE THREAD

**Issue by nd2s** [blevesearch/bleve#712]
I have following data types:

```
type Entry struct {
    Name string
    Subs []*SubEntry
}

type SubEntry struct {
    Val  float64
    Vals map[int]float64
}
```

In the document mappings `Dynamic` is set to `false` and the only (`TextField`) mapping is on `Entry.Name`.

I can restrict search results by using a `NumericRangeQuery` on `Subs.Val`, but I don't know how to select specific map entries. I tried using the key in the field name like `Subs.Vals.3` but this doesn't seem to work.

Is this possible?

**Comment by mschoch** [comment]
Based on your description, the mapping you're configuring is not being used (a common problem in bleve).  If dynamic is false, and you only configure Entry.Name, it should not be possible to do any searches on Subs.  This suggests that your mapping is not configured correctly and the default mapping is still being used.

I don't know what you mean by "select specific map entries".  In Bleve documents are indexed as a whole.

**Comment by nd2s** [comment]
Hmm, makes sense. I'll investigate the mapping problem.

"select specific map entries":
I am indexing documents with sub documents. Users are supposed to get a tuple `<document_id, subdocument_id>` as a result.

Each sub document also has properties (`Val` and `Vals` in my example). Users are supposed to be able to constrain the search results using these property values. Currently I am doing that with `bleve.NewConjunctionQuery(userTextQuery, NumRangeQuery("Subs.Val", userMin, userMax))` for the `Val` property value.

But I now need to handle further constraints on `Subs.Vals` for specific property ids (the map keys). If user wants to only see results of (sub)documents where attribute 5 is in range [0, 10] I need a way to add this numeric range to the map "field.

**Comment by mschoch** [comment]
If you need sub-documents to come back as a part of search results, then you have to index the sub-documents separately.  Otherwise, you will only ever get documents back as a whole.
