### ISSUE TITLE
Proposal: token filter for removing duplicate terms

### ISSUE THREAD

**Issue by ethantkoenig** [blevesearch/bleve#737]
There are situations where it is useful to only store the first occurence/token of each term in a document. For instance, imagine a code-searching tool similar to Github's which highlights the first match (and only the first match) of the search term in all matching documents. There is no point in wasting disk space to store tokens whose terms appear earlier in the document; such tokens will not affect which document match a particular search term, and they will not be displayed in the search results.

I would be happy to implement a token filter that does this; I just want to confirm there is interest before sending a PR. Thanks

**Comment by mschoch** [comment]
If implemented as a token filter, then the score of the document will be affected because by filtering out tokens, you end up reducing the frequency of the term (it would always be 1).

**Comment by ethantkoenig** [comment]
Fair point, but in my use case that is a trade-off I am willing to make to save disk usage.

Please let me know whether you would like me to send a PR (or not, this is your project and I'll respect your decision).

**Comment by mschoch** [comment]
If you're actually going to use it as described I'm fine with adding it.  If it is a theoretical contribution that someone might need, I would prefer to not include it at this time.

**Comment by ethantkoenig** [comment]
Okay, for the record my (actual) use-case is essentially the example I gave above; implementing code search for https://github.com/go-gitea/gitea/
