### ISSUE TITLE
Replace boltdb with bbolt

### ISSUE THREAD

**Issue by dc0d** [blevesearch/bleve#783]
Since _boltdb_ is no longer actively maintained, it seems proper to replace it with [**bbolt**](https://github.com/coreos/bbolt), a _boltdb_ fork maintained by _coreos_.

**Comment by networkimprov** [comment]
See https://github.com/etcd-io/bbolt/issues/124 re fsync() on MacOS. Also affects boltdb.

**Comment by coolaj86** [comment]
The upgrade to etcd-io/bbolt would also be of great benefit to [gitea](https://gitea.io). As is we'll likely need to create a fork just to replace the dependency. We can't use `go mod`s replace because the package name import is different.

Would you accept a PR for this?

**Comment by techknowlogick** [comment]
I've just submitted a PR for this #1018

**Comment by steveyen** [comment]
Thanks for the P.  travis-CI looks a bit unhappy with it, though, with a concurrent modification test failure at https://travis-ci.org/blevesearch/bleve/builds/464794190?utm_source=github_status&utm_medium=notification

    === RUN   TestConcurrentUpdate
    fatal error: all goroutines are asleep - deadlock!

**Comment by techknowlogick** [comment]
@steveyen looks like they maybe changed some of bolt’s guarantees with the maintenance fork. Sadly I'll have to take a break from looking at it until the new year.

If anyone wants to take over the PR if they can't wait for me, let me know and I'll give you access to the PR.

**Comment by mschoch** [comment]
We have fixed the PR and merged it: #1134
