### ISSUE TITLE
fdatasync syscall occupy much time where index the document

### ISSUE THREAD

**Issue by hetao29** [blevesearch/bleve#827]
[trace.out.tar.gz](https://github.com/blevesearch/bleve/files/1814068/trace.out.tar.gz)

edit the file github.com/blevesearch/bleve/index_impl.go
```golang

  f, err := os.OpenFile("trace"+strconv.Itoa(ix)+".out", os.O_RDWR|os.O_CREATE, 0644)
    ix++;
    if err != nil {
        log.Fatal(err)
    }
    defer f.Close()
    log.Println("Trace started")

    end= time.Now().Unix();
    log.Println("Index End2:"+strconv.FormatInt(end,10)+",duration:"+strconv.FormatInt(end-start,10));
    trace.Start(f)
    err = i.i.Update(doc)
    trace.Stop()
    end= time.Now().Unix();
    log.Println("Index End2:"+strconv.FormatInt(end,10)+",duration:"+strconv.FormatInt(end-start,10));

```
go tool trace  -http=':8888' trace.out

the open the http://localhost:8888/syscall

**Comment by mschoch** [comment]
It is expected that calls to fsync or fdatasync will be slow and dominate the profile.

If you're using the boltdb kvsore (default) you can choose to disable sync using this option:

https://github.com/blevesearch/bleve/blob/master/index/store/boltdb/store.go#L64

But, you should only do this if you understand that it means you may lose data or end up with a corrupted index.  Sometimes for an index (not primary data store) that is acceptable.  Bleve has always defaulted to safely persisting data, and that won't change at least until the next major release.

**Comment by hetao29** [comment]
Thank you very much, could you tell me how to config it without edit the file directly.

**Comment by hetao29** [comment]
I find the usage from https://github.com/blevesearch/bleve/issues/529, like this
```golang
    config := map[string]interface{}{
        "nosync": false,
    }
    index, err := bleve.NewUsing("example.bleve", mapping, upsidedown.Name, boltdb.Name, config)

```

**Comment by mschoch** [comment]
Yes, that is the correct usage.
