### ISSUE TITLE
How to escape QueryString params?

### ISSUE THREAD

**Issue by themihai** [blevesearch/bleve#844]
I need to use URIs as query params / filters. The issue is that although the [documentation](http://www.blevesearch.com/docs/Query-String-Query/) states that certain characters should be escaped I couldn't find any `Escape` function in the library so I built one but for some reasons the query fails to return the expected results.  I wonder if there is an issue with my Escape function or bleve's unescaping. Below is a test case.

```

package main

import (
	"github.com/blevesearch/bleve"
	//"github.com/blevesearch/bleve/search"
	"github.com/blevesearch/bleve/search/query"

	"bytes"
	"flag"
	log "github.com/golang/glog"
)

type Data struct {
	ID      string
	Message string
	URI     string
}

func main() {
	flag.Parse()
	defer log.Flush()

	mapping := bleve.NewIndexMapping()
	index, err := bleve.New("example.bleve", mapping)
	if err != nil {
		panic(err)
	}
	d := Data{
		ID:      "someID",
		Message: "Hello",
		URI:     `https://www.google.co.uk/search?q=google+search&oq={}///\}ie=UTF-8`,
	}
	if err := index.Index(d.ID, d); err != nil {
		panic(err)
	}

	//index, _ := bleve.Open("example.bleve")
	query := query.NewQueryStringQuery("URI:" + Escape(d.URI))
	searchRequest := bleve.NewSearchRequest(query)
	result, _ := index.Search(searchRequest)
	log.Errorf("total hits %v", result.Total)
}

func Escape(s string) string {
	ra := []string{"+", "-", "=",
		"&", "|", ">",
		"<", "!", "(", ")", "{",
		"}", "[", "]", "^",
		`~`, `*`, `?`, `:`, `\\`, `/`, `\`, ` `}
	exists := func(v string) bool {
		for _, s := range ra {
			if v == s {
				return true
			}
		}
		return false
	}
	buf := bytes.NewBuffer(nil)
	var prevBack bool
	for _, v := range s {
		if prevBack || !exists(string(v)) {
			buf.WriteString(string(v))
			prevBack = false
		} else {
			buf.WriteString(`\`)
			buf.WriteString(string(v))
			if string(v) == `\` {
				prevBack = true
			}
		}
	}
	return buf.String()
}

```

**Comment by mschoch** [comment]
The problem in this example is that the URI field is analyzed using the default analyzer of the default mapping (which is the "standard" analyzer).

The standard analyzer transforms that URL into several tokens:


Position | Term | Start | End
-- | -- | -- | --
1 | https | 0 | 5
2 | www.google.co.uk | 8 | 24
3 | search | 25 | 31
4 | q | 32 | 33
5 | google | 34 | 40
6 | search | 41 | 47
7 | oq | 48 | 50
8 | ie | 58 | 60
9 | utf | 61 | 64
10 | 8 | 65 | 66

Because of this, it is impossible for a search to match the entire URL.  If you only want to support exact matching of the entire URL, you should index that field using the "keyword" analyzer.

**Comment by themihai** [comment]
How can I use different analyzers for different fields? I believe an idiomatic way would be by using specific struct tags but I can't find any such documentation.

**Comment by mschoch** [comment]
We've moved away from struct tags as configuring analyzers is often complex.

This example is a bit more complex, but it does also show configuring a field to use the keyword analyzer: https://github.com/blevesearch/beer-search/blob/master/mapping_example1.go#L39-L62

**Comment by themihai** [comment]
It works now but I find it quite difficult scale/maintain. However it makes sense considering bleve is more a library than a fully fledged search solution.
