### ISSUE TITLE
investigate consistent read snapshot support

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#90]
Search operations often make many separate read operations in sequence.  While maybe not strictly required, it is desirable for these operations to be operating on a single consistent view of the data.

LevelDB and Bolt have support for this.  We would need revamp the in memory store to support this.

**Comment by bsphere** [comment]
I implemented a Redis store for Bleve, but then realized that it requires a snapshot.. (tests failed)
any suggestions for actually using Redis with Bleve? it may be an option for high availability setup for Bleve..

**Comment by mschoch** [comment]
I'm not familiar enough with Redis to make any suggestions.  Typically distributed KV stores to not offer read isolation.  This is one of a few reasons that its generally easier to build a high availability search solution on top of bleve as opposed to underneath it.

Without read isolation there are two problems that can come up:

1.  Search with multiple clauses returns strange results because documents changed after some clauses have operated over that part of the key-space, but before other clauses have operated over that same part of the key-space.
2.  Documents were deleted after clauses executed, but before later stages of the query execute, like loading stored fields, etc.

**Comment by bsphere** [comment]
how do you build a HA solution on top of Bleve if the KV store is local on the node?

**Comment by mschoch** [comment]
We let bleve do what it does best, index/search data on a single node.  We have a layer above that which handles the distributed computing potion, and shards the index data across multiple nodes.  Searches are then done in a scatter/gather approach.  Architecturally this is very similar to the way that Elasticsearch builds on top of Lucene.

Our work doing this is also open-sourced here:  https://github.com/couchbaselabs/cbft

NOTE: we're focusing on using this with Couchbase as the input, but the abstractions are in place such that the data can come from anywhere (could even be directly from a REST API).  So, with some additional code and different packaging you could also build an Elasticsearch clone with it.

**Comment by bsphere** [comment]
so this is a solution for sharding the indexes between multiple nodes,
what can be a solution for HA setup?

**Comment by mschoch** [comment]
Perhaps we're not using the same terminology.  Please define your requirements for an HA setup.

**Comment by bsphere** [comment]
replication of the data set, so queries can reach to a random node by a load balancer

**Comment by mschoch** [comment]
Yes, cbft handles that as well.  When configuring the index you can specify the number of replica copies, and also rack/zone preferences/priorities.  The nodes run services independently of where the index data is stored, so any node running the search service could field a request, even if none of the data for the indexing you're searching is local.  I'm also going to CC @steveyen as he can offer more details about the implementation.
