### ISSUE TITLE
scorch docvalues panic in loadDvChunk()

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#906]
There was a panic on bleve commit 2d5ae21650, which has now been reverted in https://github.com/blevesearch/bleve/commit/761a2694251bc08e3280dd80403ee4c8434f95d0.

The link to the change... https://github.com/blevesearch/bleve/commit/2d5ae21650e05d26a3876b318b860546ab970a9b

More info on the panic...

panic: runtime error: slice bounds out of range

goroutine 487 [running]:
panic(0x18c9980, 0x2045020)
    /Users/steveyen/.cbdepscache/exploded/x86_64/go-1.9.3/go/src/runtime/panic.go:540 +0x45e fp=0xc445d1d238 sp=0xc445d1d190 pc=0x102d37e
runtime.panicslice()
    /Users/steveyen/.cbdepscache/exploded/x86_64/go-1.9.3/go/src/runtime/panic.go:35 +0x5e fp=0xc445d1d258 sp=0xc445d1d238 pc=0x102beee
github.com/blevesearch/bleve/index/scorch/segment/zap.(*docValueReader).loadDvChunk(0xc431870d80, 0x1, 0xc434889ee0, 0x8, 0x0)
    /Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/docvalues.go:149 +0x3d8 fp=0xc445d1d2e0\
 sp=0xc445d1d258 pc=0x11a5578
github.com/blevesearch/bleve/index/scorch/segment/zap.(*docValueReader).iterateAllDocValues(0xc431870d80, 0xc434889ee0, 0xc4299a34c0, 0xc427aad8e0, 0xc4\
2ffee301)
    /Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/docvalues.go:157 +0x148 fp=0xc445d1d380\
 sp=0xc445d1d2e0 pc=0x11a5708
github.com/blevesearch/bleve/index/scorch/segment/zap.persistMergedRest(0xc43cea1260, 0x2, 0x2, 0xc43cea1250, 0x2, 0x2, 0xc425c38000, 0x42, 0x42, 0xc433\
2c0c60, ...)
    /Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/merge.go:361 +0x2052 fp=0xc445d1d7c0 sp\
=0xc445d1d380 pc=0x11aaaf2
github.com/blevesearch/bleve/index/scorch/segment/zap.MergeToWriter(0xc43cea1260, 0x2, 0x2, 0xc43cea1250, 0x2, 0x2, 0x400, 0xc42c767260, 0xc42082d2c0, 0\
xc4362cf988, ...)
    /Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/merge.go:119 +0x2db fp=0xc445d1d900 sp=\
0xc445d1d7c0 pc=0x11a845b
github.com/blevesearch/bleve/index/scorch/segment/zap.Merge(0xc43cea1240, 0x2, 0x2, 0xc43cea1250, 0x2, 0x2, 0xc42082d2c0, 0x91, 0x400, 0xc420024e50, ...\
)
    /Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/segment/zap/merge.go:65 +0x31a fp=0xc445d1da70 sp=0\
xc445d1d900 pc=0x11a7caa
github.com/blevesearch/bleve/index/scorch.(*Scorch).planMergeAtSnapshot(0xc4204be000, 0xc4201ef4d0, 0xc4206423c0, 0x0, 0x0)
    /Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/merge.go:198 +0xd73 fp=0xc445d1de00 sp=0xc445d1da70\
 pc=0x11f2c83
github.com/blevesearch/bleve/index/scorch.(*Scorch).mergerLoop(0xc4204be000)
    /Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/merge.go:61 +0x237 fp=0xc445d1dfd8 sp=0xc445d1de00 \
pc=0x11f1887
runtime.goexit()
    /Users/steveyen/.cbdepscache/exploded/x86_64/go-1.9.3/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc445d1dfe0 sp=0xc445d1dfd8 pc=0x105def1
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
    /Users/steveyen/dev/couchbase-server.vulcan/godeps/src/github.com/blevesearch/bleve/index/scorch/scorch.go:142 +0x12f

**Comment by steveyen** [comment]
A couple notes / ideas on this to track down (may or not bear fruit)...

a) the chunkedContentCoder has a requirement or API assumption that Add() will be invoked with docNums that never go downwards (the next docNum is >= the last docNum), so need to double check that this is actually the case with the merging optimization.  See here...

https://github.com/blevesearch/bleve/commit/2d5ae21650e05d26a3876b318b860546ab970a9b#diff-cb9b3f4cc7e69e32b20d38043abc0e49R365

b) after adding more printf()'s, it appears that sometimes a chunk might be zero sized.  Here...

https://github.com/blevesearch/bleve/commit/2d5ae21650e05d26a3876b318b860546ab970a9b#diff-5995b778f7ab14fe2d974d648b0c514fR127

...the start & end offsets are both nonzero and also equal to each other (start == end).  The docValueReader codepaths doesn't seem to handle this possible case of an empty chunk.

Note sure how the start & end offsets because equal, though, and why this condition wasn't triggered in older codepaths that were "before the reverted change".  If situation #a happens, that might possibly be the explanation, but need to think about it more.

**Comment by steveyen** [comment]
> Hey @steveyen , I've already verified (a) to be true.

Hi @abhinavdangeti -- double checking on that, can you provide a bit more detail on this #a situation?

That is, I attempted by own verification of theory #a (whether chunkedContentCoder.Add() was sometimes incorrectly invoked with a docNum < a previous docNum), and didn't see it happening.  That is, I put a panic() in there looking for this situation, and it didn't panic.

Change gears, a PR for situation #b is up for review -- https://github.com/blevesearch/bleve/pull/908, and with that fix my tests are now passing.

But, there's a slight mystery... in that I don't think I have a 100% explanation of why my testing was running into empty docvalue chunks with @abhinavdangeti's docvalues-optimization commit, but didn't seemingly run into empty docvalue chunks before that commit.

**Comment by abhinavdangeti** [comment]
That's exactly the same thing I did - placed a panic if a docnum less than the previous was encountered, and the process never panic'ed. I've verified your PR #908 to work as well..
