### ISSUE TITLE
Query language: OR query

### ISSUE THREAD

**Issue by themihai** [blevesearch/bleve#917]
I'm trying to execute a query such this `(+description:water +can:false ) OR  description:fire`.
 Return documents that match both `description:water` and `can:false` and documents that match `description:fire`. 
 Are such queries supported by the query language?

**Comment by mschoch** [comment]
Our query string does not support parentheses for group.  All clauses preceded with + MUST be satisfied, queries with - MUST NOT be satisfied, and without either prefix the SHOULD be satisfied (meaning they score higher if they are satisfied).

If you need total control over the grouping of the clauses, you can build it programmatically using the Conjunction and Disjunciton queries.

In your case, the query you described can be build as follows:

- Disjuncion
  - Conjunction
    - Match 'water' in field 'description'
    - Match 'false' in field 'can'
  - Match 'fire' in field 'description'

**Comment by themihai** [comment]
I'm using bleve behind a web server/API. It looks like I have to build an extension on top of the current query language to support Disjunction/Conjunction.
