### ISSUE TITLE
Go get github.com/blevesearch/bleve/... and go build failing after the new update to dict.go

### ISSUE THREAD

**Issue by vandanaramesh14** [blevesearch/bleve#927]
When I run go get github.com/blevesearch/bleve/... as well as any go build command, it fails as shown below. I assume it is with an update to the file : github.com\blevesearch\bleve\index\scorch\segment\zap\dict.go

<img width="714" alt="issue" src="https://user-images.githubusercontent.com/16014814/39643679-251df45a-4ff3-11e8-81b6-d3a4ce729200.png">

**Comment by mschoch** [comment]
You need to update vellum, Reader was added in a recent commit.
