### ISSUE TITLE
Cannot use configurable analyzers

### ISSUE THREAD

**Issue by abclogin** [blevesearch/bleve#945]
1) I try to use custom analyzer.
2) I pass my config for the analyzer using bleve.NewUsing().

But here
https://github.com/blevesearch/bleve/blob/e734ecadbb7b098e31f4ed8b5ba6bebf04574fbb/index_impl.go#L65 call Validate with default (empty) config.

AnalyzerConstructor gets empty config always.

And other configurable analyzers cannot be configure also

**Comment by mschoch** [comment]
I don't understand the issue you're reporting.  The link you linked to will call Validate on the mapping that you passed in.  Can you provide a complete example that illustrates the problem?

**Comment by steveyen** [comment]
Hi y'all -- been a little bit of time on this, so gonna mark this closed.  If there's more clarification, please reopen!  -- cheers, steve
